/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateProcYm311pk0ReqistYm311requestNoRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pReqdat")
    private Date preqdat;

    @JsonProperty("pFromwrh")
    private String pfromwrh;

    @JsonProperty("pTowrh")
    private String ptowrh;

    @JsonProperty("pYRNMIXCODE")
    private String pyrnmixcode;

    @JsonProperty("pPalWgt")
    private BigDecimal ppalWgt;

    @JsonProperty("pPALQTY")
    private Integer ppalqty;

    @JsonProperty("pNUMCON")
    private Integer pnumcon;

    @JsonProperty("pQTYREQN")
    private BigDecimal pqtyreqn;

    @JsonProperty("pREMARKS")
    private String premarks;

    @JsonProperty("pREQPALLETID")
    private String preqpalletid;

    @JsonProperty("pORDNUM")
    private String pordnum;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public Date getPreqdat() {
        return this.preqdat;
    }

    public void setPreqdat(Date preqdat) {
        this.preqdat = preqdat;
    }

    public String getPfromwrh() {
        return this.pfromwrh;
    }

    public void setPfromwrh(String pfromwrh) {
        this.pfromwrh = pfromwrh;
    }

    public String getPtowrh() {
        return this.ptowrh;
    }

    public void setPtowrh(String ptowrh) {
        this.ptowrh = ptowrh;
    }

    public String getPyrnmixcode() {
        return this.pyrnmixcode;
    }

    public void setPyrnmixcode(String pyrnmixcode) {
        this.pyrnmixcode = pyrnmixcode;
    }

    public BigDecimal getPpalWgt() {
        return this.ppalWgt;
    }

    public void setPpalWgt(BigDecimal ppalWgt) {
        this.ppalWgt = ppalWgt;
    }

    public Integer getPpalqty() {
        return this.ppalqty;
    }

    public void setPpalqty(Integer ppalqty) {
        this.ppalqty = ppalqty;
    }

    public Integer getPnumcon() {
        return this.pnumcon;
    }

    public void setPnumcon(Integer pnumcon) {
        this.pnumcon = pnumcon;
    }

    public BigDecimal getPqtyreqn() {
        return this.pqtyreqn;
    }

    public void setPqtyreqn(BigDecimal pqtyreqn) {
        this.pqtyreqn = pqtyreqn;
    }

    public String getPremarks() {
        return this.premarks;
    }

    public void setPremarks(String premarks) {
        this.premarks = premarks;
    }

    public String getPreqpalletid() {
        return this.preqpalletid;
    }

    public void setPreqpalletid(String preqpalletid) {
        this.preqpalletid = preqpalletid;
    }

    public String getPordnum() {
        return this.pordnum;
    }

    public void setPordnum(String pordnum) {
        this.pordnum = pordnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm311pk0ReqistYm311requestNoRequest)) return false;
        final CreateProcYm311pk0ReqistYm311requestNoRequest createProcYm311pk0reqistYm311requestNoRequest = (CreateProcYm311pk0ReqistYm311requestNoRequest) o;
        return Objects.equals(getPprgid(), createProcYm311pk0reqistYm311requestNoRequest.getPprgid()) &&
                Objects.equals(getPreqdat(), createProcYm311pk0reqistYm311requestNoRequest.getPreqdat()) &&
                Objects.equals(getPfromwrh(), createProcYm311pk0reqistYm311requestNoRequest.getPfromwrh()) &&
                Objects.equals(getPtowrh(), createProcYm311pk0reqistYm311requestNoRequest.getPtowrh()) &&
                Objects.equals(getPyrnmixcode(), createProcYm311pk0reqistYm311requestNoRequest.getPyrnmixcode()) &&
                Objects.equals(getPpalWgt(), createProcYm311pk0reqistYm311requestNoRequest.getPpalWgt()) &&
                Objects.equals(getPpalqty(), createProcYm311pk0reqistYm311requestNoRequest.getPpalqty()) &&
                Objects.equals(getPnumcon(), createProcYm311pk0reqistYm311requestNoRequest.getPnumcon()) &&
                Objects.equals(getPqtyreqn(), createProcYm311pk0reqistYm311requestNoRequest.getPqtyreqn()) &&
                Objects.equals(getPremarks(), createProcYm311pk0reqistYm311requestNoRequest.getPremarks()) &&
                Objects.equals(getPreqpalletid(), createProcYm311pk0reqistYm311requestNoRequest.getPreqpalletid()) &&
                Objects.equals(getPordnum(), createProcYm311pk0reqistYm311requestNoRequest.getPordnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPreqdat(),
                getPfromwrh(),
                getPtowrh(),
                getPyrnmixcode(),
                getPpalWgt(),
                getPpalqty(),
                getPnumcon(),
                getPqtyreqn(),
                getPremarks(),
                getPreqpalletid(),
                getPordnum());
    }
}