/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CreateProcYm250pk0YnsalesYm340addyrnslsResponse implements Serializable {


    @ColumnAlias("pOutDN")
    private Integer poutDn;

    public Integer getPoutDn() {
        return this.poutDn;
    }

    public void setPoutDn(Integer poutDn) {
        this.poutDn = poutDn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm250pk0YnsalesYm340addyrnslsResponse)) return false;
        final CreateProcYm250pk0YnsalesYm340addyrnslsResponse createProcYm250pk0ynsalesYm340addyrnslsResponse = (CreateProcYm250pk0YnsalesYm340addyrnslsResponse) o;
        return Objects.equals(getPoutDn(), createProcYm250pk0ynsalesYm340addyrnslsResponse.getPoutDn());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutDn());
    }
}