/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CreateProcYm311pk0ReqistYm311requestNoResponse implements Serializable {


    @ColumnAlias("pOutReqNo")
    private String poutReqNo;

    public String getPoutReqNo() {
        return this.poutReqNo;
    }

    public void setPoutReqNo(String poutReqNo) {
        this.poutReqNo = poutReqNo;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm311pk0ReqistYm311requestNoResponse)) return false;
        final CreateProcYm311pk0ReqistYm311requestNoResponse createProcYm311pk0reqistYm311requestNoResponse = (CreateProcYm311pk0ReqistYm311requestNoResponse) o;
        return Objects.equals(getPoutReqNo(), createProcYm311pk0reqistYm311requestNoResponse.getPoutReqNo());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutReqNo());
    }
}