/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateProcYm1000wpk0YntransfrmYm430addMulYrnRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pSrcWrhnum")
    private String psrcWrhnum;

    @JsonProperty("pSource")
    private String psource;

    @JsonProperty("pDest")
    private String pdest;

    @JsonProperty("pDestDel")
    private String pdestDel;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPsrcWrhnum() {
        return this.psrcWrhnum;
    }

    public void setPsrcWrhnum(String psrcWrhnum) {
        this.psrcWrhnum = psrcWrhnum;
    }

    public String getPsource() {
        return this.psource;
    }

    public void setPsource(String psource) {
        this.psource = psource;
    }

    public String getPdest() {
        return this.pdest;
    }

    public void setPdest(String pdest) {
        this.pdest = pdest;
    }

    public String getPdestDel() {
        return this.pdestDel;
    }

    public void setPdestDel(String pdestDel) {
        this.pdestDel = pdestDel;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm1000wpk0YntransfrmYm430addMulYrnRequest)) return false;
        final CreateProcYm1000wpk0YntransfrmYm430addMulYrnRequest createProcYm1000wpk0yntransfrmYm430addMulYrnRequest = (CreateProcYm1000wpk0YntransfrmYm430addMulYrnRequest) o;
        return Objects.equals(getPprgid(), createProcYm1000wpk0yntransfrmYm430addMulYrnRequest.getPprgid()) &&
                Objects.equals(getPsrcWrhnum(), createProcYm1000wpk0yntransfrmYm430addMulYrnRequest.getPsrcWrhnum()) &&
                Objects.equals(getPsource(), createProcYm1000wpk0yntransfrmYm430addMulYrnRequest.getPsource()) &&
                Objects.equals(getPdest(), createProcYm1000wpk0yntransfrmYm430addMulYrnRequest.getPdest()) &&
                Objects.equals(getPdestDel(), createProcYm1000wpk0yntransfrmYm430addMulYrnRequest.getPdestDel());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPsrcWrhnum(),
                getPsource(),
                getPdest(),
                getPdestDel());
    }
}