/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateProcYm1000wpk0YntransfrmYm560conCarRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pPalletId")
    private String ppalletId;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPpalletId() {
        return this.ppalletId;
    }

    public void setPpalletId(String ppalletId) {
        this.ppalletId = ppalletId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm1000wpk0YntransfrmYm560conCarRequest)) return false;
        final CreateProcYm1000wpk0YntransfrmYm560conCarRequest createProcYm1000wpk0yntransfrmYm560conCarRequest = (CreateProcYm1000wpk0YntransfrmYm560conCarRequest) o;
        return Objects.equals(getPprgid(), createProcYm1000wpk0yntransfrmYm560conCarRequest.getPprgid()) &&
                Objects.equals(getPpalletId(), createProcYm1000wpk0yntransfrmYm560conCarRequest.getPpalletId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPpalletId());
    }
}