/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateProcYm1311pk0Ym100insFinishRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pYrncod")
    private String pyrncod;

    @JsonProperty("pYrnFinish")
    private String pyrnFinish;

    @JsonProperty("pSupMod")
    private String psupMod;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPyrncod() {
        return this.pyrncod;
    }

    public void setPyrncod(String pyrncod) {
        this.pyrncod = pyrncod;
    }

    public String getPyrnFinish() {
        return this.pyrnFinish;
    }

    public void setPyrnFinish(String pyrnFinish) {
        this.pyrnFinish = pyrnFinish;
    }

    public String getPsupMod() {
        return this.psupMod;
    }

    public void setPsupMod(String psupMod) {
        this.psupMod = psupMod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm1311pk0Ym100insFinishRequest)) return false;
        final CreateProcYm1311pk0Ym100insFinishRequest createProcYm1311pk0ym100insFinishRequest = (CreateProcYm1311pk0Ym100insFinishRequest) o;
        return Objects.equals(getPprgid(), createProcYm1311pk0ym100insFinishRequest.getPprgid()) &&
                Objects.equals(getPyrncod(), createProcYm1311pk0ym100insFinishRequest.getPyrncod()) &&
                Objects.equals(getPyrnFinish(), createProcYm1311pk0ym100insFinishRequest.getPyrnFinish()) &&
                Objects.equals(getPsupMod(), createProcYm1311pk0ym100insFinishRequest.getPsupMod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPyrncod(),
                getPyrnFinish(),
                getPsupMod());
    }
}