/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateProcYm1000wpk0DelflrYm323addReturnYrnRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pWrhnum")
    private String pwrhnum;

    @JsonProperty("pRetby")
    private String pretby;

    @JsonProperty("pOrdnum")
    private String pordnum;

    @JsonProperty("pYrncod")
    private String pyrncod;

    @JsonProperty("pGrosswgt")
    private BigDecimal pgrosswgt;

    @JsonProperty("pReqnum")
    private Integer preqnum;

    @JsonProperty("pReqnseq")
    private Integer preqnseq;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPwrhnum() {
        return this.pwrhnum;
    }

    public void setPwrhnum(String pwrhnum) {
        this.pwrhnum = pwrhnum;
    }

    public String getPretby() {
        return this.pretby;
    }

    public void setPretby(String pretby) {
        this.pretby = pretby;
    }

    public String getPordnum() {
        return this.pordnum;
    }

    public void setPordnum(String pordnum) {
        this.pordnum = pordnum;
    }

    public String getPyrncod() {
        return this.pyrncod;
    }

    public void setPyrncod(String pyrncod) {
        this.pyrncod = pyrncod;
    }

    public BigDecimal getPgrosswgt() {
        return this.pgrosswgt;
    }

    public void setPgrosswgt(BigDecimal pgrosswgt) {
        this.pgrosswgt = pgrosswgt;
    }

    public Integer getPreqnum() {
        return this.preqnum;
    }

    public void setPreqnum(Integer preqnum) {
        this.preqnum = preqnum;
    }

    public Integer getPreqnseq() {
        return this.preqnseq;
    }

    public void setPreqnseq(Integer preqnseq) {
        this.preqnseq = preqnseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm1000wpk0DelflrYm323addReturnYrnRequest)) return false;
        final CreateProcYm1000wpk0DelflrYm323addReturnYrnRequest createProcYm1000wpk0delflrYm323addReturnYrnRequest = (CreateProcYm1000wpk0DelflrYm323addReturnYrnRequest) o;
        return Objects.equals(getPprgid(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPprgid()) &&
                Objects.equals(getPwrhnum(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPwrhnum()) &&
                Objects.equals(getPretby(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPretby()) &&
                Objects.equals(getPordnum(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPordnum()) &&
                Objects.equals(getPyrncod(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPyrncod()) &&
                Objects.equals(getPgrosswgt(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPgrosswgt()) &&
                Objects.equals(getPreqnum(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPreqnum()) &&
                Objects.equals(getPreqnseq(), createProcYm1000wpk0delflrYm323addReturnYrnRequest.getPreqnseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPwrhnum(),
                getPretby(),
                getPordnum(),
                getPyrncod(),
                getPgrosswgt(),
                getPreqnum(),
                getPreqnseq());
    }
}