/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CreateProcYm1000wpk0YntransfrmYm550addReqTrnsResponse implements Serializable {


    @ColumnAlias("pOutTrnnum")
    private String poutTrnnum;

    public String getPoutTrnnum() {
        return this.poutTrnnum;
    }

    public void setPoutTrnnum(String poutTrnnum) {
        this.poutTrnnum = poutTrnnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CreateProcYm1000wpk0YntransfrmYm550addReqTrnsResponse)) return false;
        final CreateProcYm1000wpk0YntransfrmYm550addReqTrnsResponse createProcYm1000wpk0yntransfrmYm550addReqTrnsResponse = (CreateProcYm1000wpk0YntransfrmYm550addReqTrnsResponse) o;
        return Objects.equals(getPoutTrnnum(), createProcYm1000wpk0yntransfrmYm550addReqTrnsResponse.getPoutTrnnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutTrnnum());
    }
}