/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm311pk0ReqistYm311viewRequestResponse implements Serializable {


    @ColumnAlias("pOutVR")
    private List<GetProcYm311pk0ReqistYm311viewRequestResponsePoutVr> poutVr;

    public List<GetProcYm311pk0ReqistYm311viewRequestResponsePoutVr> getPoutVr() {
        return this.poutVr;
    }

    public void setPoutVr(List<GetProcYm311pk0ReqistYm311viewRequestResponsePoutVr> poutVr) {
        this.poutVr = poutVr;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm311pk0ReqistYm311viewRequestResponse)) return false;
        final GetProcYm311pk0ReqistYm311viewRequestResponse getProcYm311pk0reqistYm311viewRequestResponse = (GetProcYm311pk0ReqistYm311viewRequestResponse) o;
        return Objects.equals(getPoutVr(), getProcYm311pk0reqistYm311viewRequestResponse.getPoutVr());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutVr());
    }
}