/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnreqnYm142detmixResponsePoutDetmix implements Serializable {


    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("YRNSEQ")
    private Byte yrnseq;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("NYRNCNT")
    private String nyrncnt;

    @ColumnAlias("YRNLOT")
    private String yrnlot;

    @ColumnAlias("NFYRNCPS")
    private String nfyrncps;

    @ColumnAlias("W_QTYREQN")
    private BigDecimal wqtyreqn;

    @ColumnAlias("W_SUMQTYREQN")
    private BigDecimal wsumqtyreqn;

    @ColumnAlias("MIXRATIO")
    private BigDecimal mixratio;

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public Byte getYrnseq() {
        return this.yrnseq;
    }

    public void setYrnseq(Byte yrnseq) {
        this.yrnseq = yrnseq;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public String getNyrncnt() {
        return this.nyrncnt;
    }

    public void setNyrncnt(String nyrncnt) {
        this.nyrncnt = nyrncnt;
    }

    public String getYrnlot() {
        return this.yrnlot;
    }

    public void setYrnlot(String yrnlot) {
        this.yrnlot = yrnlot;
    }

    public String getNfyrncps() {
        return this.nfyrncps;
    }

    public void setNfyrncps(String nfyrncps) {
        this.nfyrncps = nfyrncps;
    }

    public BigDecimal getWqtyreqn() {
        return this.wqtyreqn;
    }

    public void setWqtyreqn(BigDecimal wqtyreqn) {
        this.wqtyreqn = wqtyreqn;
    }

    public BigDecimal getWsumqtyreqn() {
        return this.wsumqtyreqn;
    }

    public void setWsumqtyreqn(BigDecimal wsumqtyreqn) {
        this.wsumqtyreqn = wsumqtyreqn;
    }

    public BigDecimal getMixratio() {
        return this.mixratio;
    }

    public void setMixratio(BigDecimal mixratio) {
        this.mixratio = mixratio;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnreqnYm142detmixResponsePoutDetmix)) return false;
        final GetProcYm1000wpk0YnreqnYm142detmixResponsePoutDetmix getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix = (GetProcYm1000wpk0YnreqnYm142detmixResponsePoutDetmix) o;
        return Objects.equals(getYrnmixcode(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getYrnmixcode()) &&
                Objects.equals(getYrnseq(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getYrnseq()) &&
                Objects.equals(getYrncod(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getYrncod()) &&
                Objects.equals(getYrnori(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getYrnori()) &&
                Objects.equals(getNyrncnt(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getNyrncnt()) &&
                Objects.equals(getYrnlot(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getYrnlot()) &&
                Objects.equals(getNfyrncps(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getNfyrncps()) &&
                Objects.equals(getWqtyreqn(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getWqtyreqn()) &&
                Objects.equals(getWsumqtyreqn(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getWsumqtyreqn()) &&
                Objects.equals(getMixratio(), getProcYm1000wpk0ynreqnYm142detmixResponsePoutDetmix.getMixratio());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrnmixcode(),
                getYrnseq(),
                getYrncod(),
                getYrnori(),
                getNyrncnt(),
                getYrnlot(),
                getNfyrncps(),
                getWqtyreqn(),
                getWsumqtyreqn(),
                getMixratio());
    }
}