/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnretYm160yrnRetResponsePoutYrnret implements Serializable {


    @ColumnAlias("RETNUM")
    private String retnum;

    @ColumnAlias("YNRETID")
    private String ynretid;

    @ColumnAlias("RET_ORDNUM")
    private String retOrdnum;

    @ColumnAlias("RET_FABSEQ")
    private Byte retFabseq;

    @ColumnAlias("RET_YRNID")
    private Byte retYrnid;

    @ColumnAlias("RET_KMCHCOD")
    private String retKmchcod;

    @ColumnAlias("PALLETID")
    private String palletid;

    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("WRHNUM")
    private String wrhnum;

    @ColumnAlias("NUMCON")
    private Short numcon;

    @ColumnAlias("NUMCAR")
    private Short numcar;

    @ColumnAlias("KGSRET")
    private Double kgsret;

    @ColumnAlias("RETBY")
    private String retby;

    @ColumnAlias("RETDAT")
    private LocalDateTime retdat;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("DISCARDKGS")
    private String discardkgs;

    @ColumnAlias("KGSMADEAVAIL")
    private Double kgsmadeavail;

    @ColumnAlias("AVAILBY")
    private String availby;

    @ColumnAlias("AVAILDAT")
    private LocalDateTime availdat;

    public String getRetnum() {
        return this.retnum;
    }

    public void setRetnum(String retnum) {
        this.retnum = retnum;
    }

    public String getYnretid() {
        return this.ynretid;
    }

    public void setYnretid(String ynretid) {
        this.ynretid = ynretid;
    }

    public String getRetOrdnum() {
        return this.retOrdnum;
    }

    public void setRetOrdnum(String retOrdnum) {
        this.retOrdnum = retOrdnum;
    }

    public Byte getRetFabseq() {
        return this.retFabseq;
    }

    public void setRetFabseq(Byte retFabseq) {
        this.retFabseq = retFabseq;
    }

    public Byte getRetYrnid() {
        return this.retYrnid;
    }

    public void setRetYrnid(Byte retYrnid) {
        this.retYrnid = retYrnid;
    }

    public String getRetKmchcod() {
        return this.retKmchcod;
    }

    public void setRetKmchcod(String retKmchcod) {
        this.retKmchcod = retKmchcod;
    }

    public String getPalletid() {
        return this.palletid;
    }

    public void setPalletid(String palletid) {
        this.palletid = palletid;
    }

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public String getWrhnum() {
        return this.wrhnum;
    }

    public void setWrhnum(String wrhnum) {
        this.wrhnum = wrhnum;
    }

    public Short getNumcon() {
        return this.numcon;
    }

    public void setNumcon(Short numcon) {
        this.numcon = numcon;
    }

    public Short getNumcar() {
        return this.numcar;
    }

    public void setNumcar(Short numcar) {
        this.numcar = numcar;
    }

    public Double getKgsret() {
        return this.kgsret;
    }

    public void setKgsret(Double kgsret) {
        this.kgsret = kgsret;
    }

    public String getRetby() {
        return this.retby;
    }

    public void setRetby(String retby) {
        this.retby = retby;
    }

    public LocalDateTime getRetdat() {
        return this.retdat;
    }

    public void setRetdat(LocalDateTime retdat) {
        this.retdat = retdat;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getDiscardkgs() {
        return this.discardkgs;
    }

    public void setDiscardkgs(String discardkgs) {
        this.discardkgs = discardkgs;
    }

    public Double getKgsmadeavail() {
        return this.kgsmadeavail;
    }

    public void setKgsmadeavail(Double kgsmadeavail) {
        this.kgsmadeavail = kgsmadeavail;
    }

    public String getAvailby() {
        return this.availby;
    }

    public void setAvailby(String availby) {
        this.availby = availby;
    }

    public LocalDateTime getAvaildat() {
        return this.availdat;
    }

    public void setAvaildat(LocalDateTime availdat) {
        this.availdat = availdat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnretYm160yrnRetResponsePoutYrnret)) return false;
        final GetProcYm1000wpk0YnretYm160yrnRetResponsePoutYrnret getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret = (GetProcYm1000wpk0YnretYm160yrnRetResponsePoutYrnret) o;
        return Objects.equals(getRetnum(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetnum()) &&
                Objects.equals(getYnretid(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getYnretid()) &&
                Objects.equals(getRetOrdnum(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetOrdnum()) &&
                Objects.equals(getRetFabseq(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetFabseq()) &&
                Objects.equals(getRetYrnid(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetYrnid()) &&
                Objects.equals(getRetKmchcod(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetKmchcod()) &&
                Objects.equals(getPalletid(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getPalletid()) &&
                Objects.equals(getYrnmixcode(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getYrnmixcode()) &&
                Objects.equals(getWrhnum(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getWrhnum()) &&
                Objects.equals(getNumcon(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getNumcon()) &&
                Objects.equals(getNumcar(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getNumcar()) &&
                Objects.equals(getKgsret(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getKgsret()) &&
                Objects.equals(getRetby(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetby()) &&
                Objects.equals(getRetdat(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRetdat()) &&
                Objects.equals(getRemarks(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getRemarks()) &&
                Objects.equals(getDiscardkgs(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getDiscardkgs()) &&
                Objects.equals(getKgsmadeavail(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getKgsmadeavail()) &&
                Objects.equals(getAvailby(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getAvailby()) &&
                Objects.equals(getAvaildat(), getProcYm1000wpk0ynretYm160yrnRetResponsePoutYrnret.getAvaildat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRetnum(),
                getYnretid(),
                getRetOrdnum(),
                getRetFabseq(),
                getRetYrnid(),
                getRetKmchcod(),
                getPalletid(),
                getYrnmixcode(),
                getWrhnum(),
                getNumcon(),
                getNumcar(),
                getKgsret(),
                getRetby(),
                getRetdat(),
                getRemarks(),
                getDiscardkgs(),
                getKgsmadeavail(),
                getAvailby(),
                getAvaildat());
    }
}