/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn implements Serializable {


    @ColumnAlias("NYRNCNT")
    private String nyrncnt;

    @ColumnAlias("NFYRNCPS")
    private String nfyrncps;

    @ColumnAlias("YRNLOT")
    private String yrnlot;

    @ColumnAlias("YRNORI")
    private String yrnori;

    public String getNyrncnt() {
        return this.nyrncnt;
    }

    public void setNyrncnt(String nyrncnt) {
        this.nyrncnt = nyrncnt;
    }

    public String getNfyrncps() {
        return this.nfyrncps;
    }

    public void setNfyrncps(String nfyrncps) {
        this.nfyrncps = nfyrncps;
    }

    public String getYrnlot() {
        return this.yrnlot;
    }

    public void setYrnlot(String yrnlot) {
        this.yrnlot = yrnlot;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn)) return false;
        final GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn getProcYm1000wpk0delflrYm323nonbaseResponsePoutYrn = (GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn) o;
        return Objects.equals(getNyrncnt(), getProcYm1000wpk0delflrYm323nonbaseResponsePoutYrn.getNyrncnt()) &&
                Objects.equals(getNfyrncps(), getProcYm1000wpk0delflrYm323nonbaseResponsePoutYrn.getNfyrncps()) &&
                Objects.equals(getYrnlot(), getProcYm1000wpk0delflrYm323nonbaseResponsePoutYrn.getYrnlot()) &&
                Objects.equals(getYrnori(), getProcYm1000wpk0delflrYm323nonbaseResponsePoutYrn.getYrnori());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNyrncnt(),
                getNfyrncps(),
                getYrnlot(),
                getYrnori());
    }
}