/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm311pk0ReqistYm311rgfromWrhResponsePoutRgfromWrh implements Serializable {


    @ColumnAlias("STRCOD")
    private String strcod;

    @ColumnAlias("STRDES")
    private String strdes;

    public String getStrcod() {
        return this.strcod;
    }

    public void setStrcod(String strcod) {
        this.strcod = strcod;
    }

    public String getStrdes() {
        return this.strdes;
    }

    public void setStrdes(String strdes) {
        this.strdes = strdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm311pk0ReqistYm311rgfromWrhResponsePoutRgfromWrh)) return false;
        final GetProcYm311pk0ReqistYm311rgfromWrhResponsePoutRgfromWrh getProcYm311pk0reqistYm311rgfromWrhResponsePoutRgfromWrh = (GetProcYm311pk0ReqistYm311rgfromWrhResponsePoutRgfromWrh) o;
        return Objects.equals(getStrcod(), getProcYm311pk0reqistYm311rgfromWrhResponsePoutRgfromWrh.getStrcod()) &&
                Objects.equals(getStrdes(), getProcYm311pk0reqistYm311rgfromWrhResponsePoutRgfromWrh.getStrdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStrcod(),
                getStrdes());
    }
}