/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm560listofReqnoResponsePoutReqno implements Serializable {


    @ColumnAlias("TRNREQNO")
    private String trnreqno;

    @ColumnAlias("TRNREQSEQ")
    private Short trnreqseq;

    @ColumnAlias("SRCYRNCOD")
    private String srcyrncod;

    @ColumnAlias("DESTYRNCOD")
    private String destyrncod;

    @ColumnAlias("QTYRES")
    private Double qtyres;

    @ColumnAlias("QTYTRANSFORMED")
    private Double qtytransformed;

    @ColumnAlias("NETQTY")
    private BigInteger netqty;

    @ColumnAlias("WRHNUM")
    private String wrhnum;

    @ColumnAlias("TRNTYP")
    private String trntyp;

    public String getTrnreqno() {
        return this.trnreqno;
    }

    public void setTrnreqno(String trnreqno) {
        this.trnreqno = trnreqno;
    }

    public Short getTrnreqseq() {
        return this.trnreqseq;
    }

    public void setTrnreqseq(Short trnreqseq) {
        this.trnreqseq = trnreqseq;
    }

    public String getSrcyrncod() {
        return this.srcyrncod;
    }

    public void setSrcyrncod(String srcyrncod) {
        this.srcyrncod = srcyrncod;
    }

    public String getDestyrncod() {
        return this.destyrncod;
    }

    public void setDestyrncod(String destyrncod) {
        this.destyrncod = destyrncod;
    }

    public Double getQtyres() {
        return this.qtyres;
    }

    public void setQtyres(Double qtyres) {
        this.qtyres = qtyres;
    }

    public Double getQtytransformed() {
        return this.qtytransformed;
    }

    public void setQtytransformed(Double qtytransformed) {
        this.qtytransformed = qtytransformed;
    }

    public BigInteger getNetqty() {
        return this.netqty;
    }

    public void setNetqty(BigInteger netqty) {
        this.netqty = netqty;
    }

    public String getWrhnum() {
        return this.wrhnum;
    }

    public void setWrhnum(String wrhnum) {
        this.wrhnum = wrhnum;
    }

    public String getTrntyp() {
        return this.trntyp;
    }

    public void setTrntyp(String trntyp) {
        this.trntyp = trntyp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm560listofReqnoResponsePoutReqno)) return false;
        final GetProcYm1000wpk0YntransfrmYm560listofReqnoResponsePoutReqno getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno = (GetProcYm1000wpk0YntransfrmYm560listofReqnoResponsePoutReqno) o;
        return Objects.equals(getTrnreqno(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getTrnreqno()) &&
                Objects.equals(getTrnreqseq(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getTrnreqseq()) &&
                Objects.equals(getSrcyrncod(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getSrcyrncod()) &&
                Objects.equals(getDestyrncod(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getDestyrncod()) &&
                Objects.equals(getQtyres(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getQtyres()) &&
                Objects.equals(getQtytransformed(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getQtytransformed()) &&
                Objects.equals(getNetqty(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getNetqty()) &&
                Objects.equals(getWrhnum(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getWrhnum()) &&
                Objects.equals(getTrntyp(), getProcYm1000wpk0yntransfrmYm560listofReqnoResponsePoutReqno.getTrntyp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnreqno(),
                getTrnreqseq(),
                getSrcyrncod(),
                getDestyrncod(),
                getQtyres(),
                getQtytransformed(),
                getNetqty(),
                getWrhnum(),
                getTrntyp());
    }
}