/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm4000pk0Ym410masterResponse implements Serializable {


    @ColumnAlias("pOutMaster")
    private List<GetProcYm4000pk0Ym410masterResponsePoutMaster> poutMaster;

    public List<GetProcYm4000pk0Ym410masterResponsePoutMaster> getPoutMaster() {
        return this.poutMaster;
    }

    public void setPoutMaster(List<GetProcYm4000pk0Ym410masterResponsePoutMaster> poutMaster) {
        this.poutMaster = poutMaster;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm4000pk0Ym410masterResponse)) return false;
        final GetProcYm4000pk0Ym410masterResponse getProcYm4000pk0ym410masterResponse = (GetProcYm4000pk0Ym410masterResponse) o;
        return Objects.equals(getPoutMaster(), getProcYm4000pk0ym410masterResponse.getPoutMaster());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutMaster());
    }
}