/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnretYm160dplyRetnumResponse implements Serializable {


    @ColumnAlias("pOutretnum")
    private List<GetProcYm1000wpk0YnretYm160dplyRetnumResponsePoutretnum> poutretnum;

    public List<GetProcYm1000wpk0YnretYm160dplyRetnumResponsePoutretnum> getPoutretnum() {
        return this.poutretnum;
    }

    public void setPoutretnum(List<GetProcYm1000wpk0YnretYm160dplyRetnumResponsePoutretnum> poutretnum) {
        this.poutretnum = poutretnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnretYm160dplyRetnumResponse)) return false;
        final GetProcYm1000wpk0YnretYm160dplyRetnumResponse getProcYm1000wpk0ynretYm160dplyRetnumResponse = (GetProcYm1000wpk0YnretYm160dplyRetnumResponse) o;
        return Objects.equals(getPoutretnum(), getProcYm1000wpk0ynretYm160dplyRetnumResponse.getPoutretnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutretnum());
    }
}