/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm560dlgOpnResponse implements Serializable {


    @ColumnAlias("pOutpaltyp")
    private String poutpaltyp;

    @ColumnAlias("pOutconwgt")
    private BigDecimal poutconwgt;

    @ColumnAlias("pOutconcar")
    private BigDecimal poutconcar;

    @ColumnAlias("pOutCarpal")
    private BigDecimal poutCarpal;

    @ColumnAlias("pOutnumcon")
    private BigDecimal poutnumcon;

    @ColumnAlias("pOutqty")
    private BigDecimal poutqty;

    @ColumnAlias("pOutcontrolqty")
    private BigDecimal poutcontrolqty;

    public String getPoutpaltyp() {
        return this.poutpaltyp;
    }

    public void setPoutpaltyp(String poutpaltyp) {
        this.poutpaltyp = poutpaltyp;
    }

    public BigDecimal getPoutconwgt() {
        return this.poutconwgt;
    }

    public void setPoutconwgt(BigDecimal poutconwgt) {
        this.poutconwgt = poutconwgt;
    }

    public BigDecimal getPoutconcar() {
        return this.poutconcar;
    }

    public void setPoutconcar(BigDecimal poutconcar) {
        this.poutconcar = poutconcar;
    }

    public BigDecimal getPoutCarpal() {
        return this.poutCarpal;
    }

    public void setPoutCarpal(BigDecimal poutCarpal) {
        this.poutCarpal = poutCarpal;
    }

    public BigDecimal getPoutnumcon() {
        return this.poutnumcon;
    }

    public void setPoutnumcon(BigDecimal poutnumcon) {
        this.poutnumcon = poutnumcon;
    }

    public BigDecimal getPoutqty() {
        return this.poutqty;
    }

    public void setPoutqty(BigDecimal poutqty) {
        this.poutqty = poutqty;
    }

    public BigDecimal getPoutcontrolqty() {
        return this.poutcontrolqty;
    }

    public void setPoutcontrolqty(BigDecimal poutcontrolqty) {
        this.poutcontrolqty = poutcontrolqty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm560dlgOpnResponse)) return false;
        final GetProcYm1000wpk0YntransfrmYm560dlgOpnResponse getProcYm1000wpk0yntransfrmYm560dlgOpnResponse = (GetProcYm1000wpk0YntransfrmYm560dlgOpnResponse) o;
        return Objects.equals(getPoutpaltyp(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutpaltyp()) &&
                Objects.equals(getPoutconwgt(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutconwgt()) &&
                Objects.equals(getPoutconcar(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutconcar()) &&
                Objects.equals(getPoutCarpal(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutCarpal()) &&
                Objects.equals(getPoutnumcon(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutnumcon()) &&
                Objects.equals(getPoutqty(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutqty()) &&
                Objects.equals(getPoutcontrolqty(), getProcYm1000wpk0yntransfrmYm560dlgOpnResponse.getPoutcontrolqty());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutpaltyp(),
                getPoutconwgt(),
                getPoutconcar(),
                getPoutCarpal(),
                getPoutnumcon(),
                getPoutqty(),
                getPoutcontrolqty());
    }
}