/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100yrnQltyDesResponse implements Serializable {


    @ColumnAlias("pOutYrnQltyDes")
    private List<GetProcYm1311pk0Ym100yrnQltyDesResponsePoutYrnQltyDes> poutYrnQltyDes;

    public List<GetProcYm1311pk0Ym100yrnQltyDesResponsePoutYrnQltyDes> getPoutYrnQltyDes() {
        return this.poutYrnQltyDes;
    }

    public void setPoutYrnQltyDes(List<GetProcYm1311pk0Ym100yrnQltyDesResponsePoutYrnQltyDes> poutYrnQltyDes) {
        this.poutYrnQltyDes = poutYrnQltyDes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100yrnQltyDesResponse)) return false;
        final GetProcYm1311pk0Ym100yrnQltyDesResponse getProcYm1311pk0ym100yrnQltyDesResponse = (GetProcYm1311pk0Ym100yrnQltyDesResponse) o;
        return Objects.equals(getPoutYrnQltyDes(), getProcYm1311pk0ym100yrnQltyDesResponse.getPoutYrnQltyDes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYrnQltyDes());
    }
}