/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm560qryTrnNumResponsePoutTrnnumdel implements Serializable {


    @ColumnAlias("TRNNUM")
    private String trnnum;

    @ColumnAlias("TRNSEQ")
    private Short trnseq;

    @ColumnAlias("REQNO")
    private String reqno;

    @ColumnAlias("REQSEQ")
    private Short reqseq;

    @ColumnAlias("WRHNUM")
    private String wrhnum;

    @ColumnAlias("SRCYRNCOD")
    private String srcyrncod;

    @ColumnAlias("DESTYRNCOD")
    private String destyrncod;

    @ColumnAlias("SRCPALLETID")
    private String srcpalletid;

    @ColumnAlias("DESTPALLETID")
    private String destpalletid;

    @ColumnAlias("QTY")
    private Double qty;

    @ColumnAlias("TRNTYP")
    private String trntyp;

    @ColumnAlias("ITEMDES")
    private String itemdes;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("MODBY")
    private String modby;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    public String getTrnnum() {
        return this.trnnum;
    }

    public void setTrnnum(String trnnum) {
        this.trnnum = trnnum;
    }

    public Short getTrnseq() {
        return this.trnseq;
    }

    public void setTrnseq(Short trnseq) {
        this.trnseq = trnseq;
    }

    public String getReqno() {
        return this.reqno;
    }

    public void setReqno(String reqno) {
        this.reqno = reqno;
    }

    public Short getReqseq() {
        return this.reqseq;
    }

    public void setReqseq(Short reqseq) {
        this.reqseq = reqseq;
    }

    public String getWrhnum() {
        return this.wrhnum;
    }

    public void setWrhnum(String wrhnum) {
        this.wrhnum = wrhnum;
    }

    public String getSrcyrncod() {
        return this.srcyrncod;
    }

    public void setSrcyrncod(String srcyrncod) {
        this.srcyrncod = srcyrncod;
    }

    public String getDestyrncod() {
        return this.destyrncod;
    }

    public void setDestyrncod(String destyrncod) {
        this.destyrncod = destyrncod;
    }

    public String getSrcpalletid() {
        return this.srcpalletid;
    }

    public void setSrcpalletid(String srcpalletid) {
        this.srcpalletid = srcpalletid;
    }

    public String getDestpalletid() {
        return this.destpalletid;
    }

    public void setDestpalletid(String destpalletid) {
        this.destpalletid = destpalletid;
    }

    public Double getQty() {
        return this.qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    public String getTrntyp() {
        return this.trntyp;
    }

    public void setTrntyp(String trntyp) {
        this.trntyp = trntyp;
    }

    public String getItemdes() {
        return this.itemdes;
    }

    public void setItemdes(String itemdes) {
        this.itemdes = itemdes;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getModby() {
        return this.modby;
    }

    public void setModby(String modby) {
        this.modby = modby;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm560qryTrnNumResponsePoutTrnnumdel)) return false;
        final GetProcYm1000wpk0YntransfrmYm560qryTrnNumResponsePoutTrnnumdel getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel = (GetProcYm1000wpk0YntransfrmYm560qryTrnNumResponsePoutTrnnumdel) o;
        return Objects.equals(getTrnnum(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getTrnnum()) &&
                Objects.equals(getTrnseq(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getTrnseq()) &&
                Objects.equals(getReqno(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getReqno()) &&
                Objects.equals(getReqseq(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getReqseq()) &&
                Objects.equals(getWrhnum(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getWrhnum()) &&
                Objects.equals(getSrcyrncod(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getSrcyrncod()) &&
                Objects.equals(getDestyrncod(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getDestyrncod()) &&
                Objects.equals(getSrcpalletid(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getSrcpalletid()) &&
                Objects.equals(getDestpalletid(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getDestpalletid()) &&
                Objects.equals(getQty(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getQty()) &&
                Objects.equals(getTrntyp(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getTrntyp()) &&
                Objects.equals(getItemdes(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getItemdes()) &&
                Objects.equals(getRemarks(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getRemarks()) &&
                Objects.equals(getModby(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getModby()) &&
                Objects.equals(getModdat(), getProcYm1000wpk0yntransfrmYm560qryTrnNumResponsePoutTrnnumdel.getModdat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnnum(),
                getTrnseq(),
                getReqno(),
                getReqseq(),
                getWrhnum(),
                getSrcyrncod(),
                getDestyrncod(),
                getSrcpalletid(),
                getDestpalletid(),
                getQty(),
                getTrntyp(),
                getItemdes(),
                getRemarks(),
                getModby(),
                getModdat());
    }
}