/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100cpyScntResponse implements Serializable {


    @ColumnAlias("pOutSCnt")
    private List<GetProcYm1311pk0Ym100cpyScntResponsePoutScnt> poutScnt;

    public List<GetProcYm1311pk0Ym100cpyScntResponsePoutScnt> getPoutScnt() {
        return this.poutScnt;
    }

    public void setPoutScnt(List<GetProcYm1311pk0Ym100cpyScntResponsePoutScnt> poutScnt) {
        this.poutScnt = poutScnt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100cpyScntResponse)) return false;
        final GetProcYm1311pk0Ym100cpyScntResponse getProcYm1311pk0ym100cpyScntResponse = (GetProcYm1311pk0Ym100cpyScntResponse) o;
        return Objects.equals(getPoutScnt(), getProcYm1311pk0ym100cpyScntResponse.getPoutScnt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutScnt());
    }
}