/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm4000pk0Ym410masterResponsePoutMaster implements Serializable {


    @ColumnAlias("CONTRACTID")
    private String contractid;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("CONTAINERNUM")
    private String containernum;

    @ColumnAlias("YNITEMNO")
    private Byte ynitemno;

    @ColumnAlias("CONTAINER_SEQ")
    private Short containerSeq;

    @ColumnAlias("RLOTNUM")
    private String rlotnum;

    @ColumnAlias("YRNCNT")
    private String yrncnt;

    @ColumnAlias("YRNCPS")
    private String yrncps;

    @ColumnAlias("YRNCLR")
    private String yrnclr;

    public String getContractid() {
        return this.contractid;
    }

    public void setContractid(String contractid) {
        this.contractid = contractid;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getContainernum() {
        return this.containernum;
    }

    public void setContainernum(String containernum) {
        this.containernum = containernum;
    }

    public Byte getYnitemno() {
        return this.ynitemno;
    }

    public void setYnitemno(Byte ynitemno) {
        this.ynitemno = ynitemno;
    }

    public Short getContainerSeq() {
        return this.containerSeq;
    }

    public void setContainerSeq(Short containerSeq) {
        this.containerSeq = containerSeq;
    }

    public String getRlotnum() {
        return this.rlotnum;
    }

    public void setRlotnum(String rlotnum) {
        this.rlotnum = rlotnum;
    }

    public String getYrncnt() {
        return this.yrncnt;
    }

    public void setYrncnt(String yrncnt) {
        this.yrncnt = yrncnt;
    }

    public String getYrncps() {
        return this.yrncps;
    }

    public void setYrncps(String yrncps) {
        this.yrncps = yrncps;
    }

    public String getYrnclr() {
        return this.yrnclr;
    }

    public void setYrnclr(String yrnclr) {
        this.yrnclr = yrnclr;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm4000pk0Ym410masterResponsePoutMaster)) return false;
        final GetProcYm4000pk0Ym410masterResponsePoutMaster getProcYm4000pk0ym410masterResponsePoutMaster = (GetProcYm4000pk0Ym410masterResponsePoutMaster) o;
        return Objects.equals(getContractid(), getProcYm4000pk0ym410masterResponsePoutMaster.getContractid()) &&
                Objects.equals(getYrncod(), getProcYm4000pk0ym410masterResponsePoutMaster.getYrncod()) &&
                Objects.equals(getContainernum(), getProcYm4000pk0ym410masterResponsePoutMaster.getContainernum()) &&
                Objects.equals(getYnitemno(), getProcYm4000pk0ym410masterResponsePoutMaster.getYnitemno()) &&
                Objects.equals(getContainerSeq(), getProcYm4000pk0ym410masterResponsePoutMaster.getContainerSeq()) &&
                Objects.equals(getRlotnum(), getProcYm4000pk0ym410masterResponsePoutMaster.getRlotnum()) &&
                Objects.equals(getYrncnt(), getProcYm4000pk0ym410masterResponsePoutMaster.getYrncnt()) &&
                Objects.equals(getYrncps(), getProcYm4000pk0ym410masterResponsePoutMaster.getYrncps()) &&
                Objects.equals(getYrnclr(), getProcYm4000pk0ym410masterResponsePoutMaster.getYrnclr());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContractid(),
                getYrncod(),
                getContainernum(),
                getYnitemno(),
                getContainerSeq(),
                getRlotnum(),
                getYrncnt(),
                getYrncps(),
                getYrnclr());
    }
}