/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000pk0Ym285recptSeqResponse implements Serializable {


    @ColumnAlias("pOutRecptSeq")
    private List<GetProcYm1000pk0Ym285recptSeqResponsePoutRecptSeq> poutRecptSeq;

    public List<GetProcYm1000pk0Ym285recptSeqResponsePoutRecptSeq> getPoutRecptSeq() {
        return this.poutRecptSeq;
    }

    public void setPoutRecptSeq(List<GetProcYm1000pk0Ym285recptSeqResponsePoutRecptSeq> poutRecptSeq) {
        this.poutRecptSeq = poutRecptSeq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000pk0Ym285recptSeqResponse)) return false;
        final GetProcYm1000pk0Ym285recptSeqResponse getProcYm1000pk0ym285recptSeqResponse = (GetProcYm1000pk0Ym285recptSeqResponse) o;
        return Objects.equals(getPoutRecptSeq(), getProcYm1000pk0ym285recptSeqResponse.getPoutRecptSeq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutRecptSeq());
    }
}