/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm560dplyTrnnumResponsePoutAllTrnnum implements Serializable {


    @ColumnAlias("TRNNUM")
    private String trnnum;

    @ColumnAlias("TRNSEQ")
    private Short trnseq;

    @ColumnAlias("REQNO")
    private String reqno;

    @ColumnAlias("SRCPALLETID")
    private String srcpalletid;

    @ColumnAlias("SRCYRNCOD")
    private String srcyrncod;

    @ColumnAlias("W_DESTYRNCOD")
    private String wdestyrncod;

    @ColumnAlias("DESTPALLETID")
    private String destpalletid;

    @ColumnAlias("WRHNUM")
    private String wrhnum;

    @ColumnAlias("QTY")
    private Double qty;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("MODBY")
    private String modby;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    public String getTrnnum() {
        return this.trnnum;
    }

    public void setTrnnum(String trnnum) {
        this.trnnum = trnnum;
    }

    public Short getTrnseq() {
        return this.trnseq;
    }

    public void setTrnseq(Short trnseq) {
        this.trnseq = trnseq;
    }

    public String getReqno() {
        return this.reqno;
    }

    public void setReqno(String reqno) {
        this.reqno = reqno;
    }

    public String getSrcpalletid() {
        return this.srcpalletid;
    }

    public void setSrcpalletid(String srcpalletid) {
        this.srcpalletid = srcpalletid;
    }

    public String getSrcyrncod() {
        return this.srcyrncod;
    }

    public void setSrcyrncod(String srcyrncod) {
        this.srcyrncod = srcyrncod;
    }

    public String getWdestyrncod() {
        return this.wdestyrncod;
    }

    public void setWdestyrncod(String wdestyrncod) {
        this.wdestyrncod = wdestyrncod;
    }

    public String getDestpalletid() {
        return this.destpalletid;
    }

    public void setDestpalletid(String destpalletid) {
        this.destpalletid = destpalletid;
    }

    public String getWrhnum() {
        return this.wrhnum;
    }

    public void setWrhnum(String wrhnum) {
        this.wrhnum = wrhnum;
    }

    public Double getQty() {
        return this.qty;
    }

    public void setQty(Double qty) {
        this.qty = qty;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getModby() {
        return this.modby;
    }

    public void setModby(String modby) {
        this.modby = modby;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm560dplyTrnnumResponsePoutAllTrnnum)) return false;
        final GetProcYm1000wpk0YntransfrmYm560dplyTrnnumResponsePoutAllTrnnum getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum = (GetProcYm1000wpk0YntransfrmYm560dplyTrnnumResponsePoutAllTrnnum) o;
        return Objects.equals(getTrnnum(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getTrnnum()) &&
                Objects.equals(getTrnseq(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getTrnseq()) &&
                Objects.equals(getReqno(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getReqno()) &&
                Objects.equals(getSrcpalletid(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getSrcpalletid()) &&
                Objects.equals(getSrcyrncod(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getSrcyrncod()) &&
                Objects.equals(getWdestyrncod(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getWdestyrncod()) &&
                Objects.equals(getDestpalletid(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getDestpalletid()) &&
                Objects.equals(getWrhnum(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getWrhnum()) &&
                Objects.equals(getQty(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getQty()) &&
                Objects.equals(getRemarks(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getRemarks()) &&
                Objects.equals(getModby(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getModby()) &&
                Objects.equals(getModdat(), getProcYm1000wpk0yntransfrmYm560dplyTrnnumResponsePoutAllTrnnum.getModdat());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnnum(),
                getTrnseq(),
                getReqno(),
                getSrcpalletid(),
                getSrcyrncod(),
                getWdestyrncod(),
                getDestpalletid(),
                getWrhnum(),
                getQty(),
                getRemarks(),
                getModby(),
                getModdat());
    }
}