/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000pk0DelflrYm322lstOfWrhnumResponsePoutLstOfWrhnum implements Serializable {


    @ColumnAlias("STRCOD")
    private String strcod;

    public String getStrcod() {
        return this.strcod;
    }

    public void setStrcod(String strcod) {
        this.strcod = strcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000pk0DelflrYm322lstOfWrhnumResponsePoutLstOfWrhnum)) return false;
        final GetProcYm1000pk0DelflrYm322lstOfWrhnumResponsePoutLstOfWrhnum getProcYm1000pk0delflrYm322lstOfWrhnumResponsePoutLstOfWrhnum = (GetProcYm1000pk0DelflrYm322lstOfWrhnumResponsePoutLstOfWrhnum) o;
        return Objects.equals(getStrcod(), getProcYm1000pk0delflrYm322lstOfWrhnumResponsePoutLstOfWrhnum.getStrcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStrcod());
    }
}