/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0DelflrYm323nonbaseResponse implements Serializable {


    @ColumnAlias("pOutYrn")
    private List<GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn> poutYrn;

    @ColumnAlias("pOutblnce")
    private List<GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutblnce> poutblnce;

    public List<GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn> getPoutYrn() {
        return this.poutYrn;
    }

    public void setPoutYrn(List<GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutYrn> poutYrn) {
        this.poutYrn = poutYrn;
    }

    public List<GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutblnce> getPoutblnce() {
        return this.poutblnce;
    }

    public void setPoutblnce(List<GetProcYm1000wpk0DelflrYm323nonbaseResponsePoutblnce> poutblnce) {
        this.poutblnce = poutblnce;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0DelflrYm323nonbaseResponse)) return false;
        final GetProcYm1000wpk0DelflrYm323nonbaseResponse getProcYm1000wpk0delflrYm323nonbaseResponse = (GetProcYm1000wpk0DelflrYm323nonbaseResponse) o;
        return Objects.equals(getPoutYrn(), getProcYm1000wpk0delflrYm323nonbaseResponse.getPoutYrn()) &&
                Objects.equals(getPoutblnce(), getProcYm1000wpk0delflrYm323nonbaseResponse.getPoutblnce());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYrn(),
                getPoutblnce());
    }
}