/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm560vldtReqnoResponsePoutReqnoDel implements Serializable {


    @ColumnAlias("TRNREQNO")
    private String trnreqno;

    @ColumnAlias("SRCYRNCOD")
    private String srcyrncod;

    @ColumnAlias("DESTYRNCOD")
    private String destyrncod;

    @ColumnAlias("WRHNUM")
    private String wrhnum;

    @ColumnAlias("TRNREQSEQ")
    private Short trnreqseq;

    @ColumnAlias("TRNTYP")
    private String trntyp;

    public String getTrnreqno() {
        return this.trnreqno;
    }

    public void setTrnreqno(String trnreqno) {
        this.trnreqno = trnreqno;
    }

    public String getSrcyrncod() {
        return this.srcyrncod;
    }

    public void setSrcyrncod(String srcyrncod) {
        this.srcyrncod = srcyrncod;
    }

    public String getDestyrncod() {
        return this.destyrncod;
    }

    public void setDestyrncod(String destyrncod) {
        this.destyrncod = destyrncod;
    }

    public String getWrhnum() {
        return this.wrhnum;
    }

    public void setWrhnum(String wrhnum) {
        this.wrhnum = wrhnum;
    }

    public Short getTrnreqseq() {
        return this.trnreqseq;
    }

    public void setTrnreqseq(Short trnreqseq) {
        this.trnreqseq = trnreqseq;
    }

    public String getTrntyp() {
        return this.trntyp;
    }

    public void setTrntyp(String trntyp) {
        this.trntyp = trntyp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm560vldtReqnoResponsePoutReqnoDel)) return false;
        final GetProcYm1000wpk0YntransfrmYm560vldtReqnoResponsePoutReqnoDel getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel = (GetProcYm1000wpk0YntransfrmYm560vldtReqnoResponsePoutReqnoDel) o;
        return Objects.equals(getTrnreqno(), getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel.getTrnreqno()) &&
                Objects.equals(getSrcyrncod(), getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel.getSrcyrncod()) &&
                Objects.equals(getDestyrncod(), getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel.getDestyrncod()) &&
                Objects.equals(getWrhnum(), getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel.getWrhnum()) &&
                Objects.equals(getTrnreqseq(), getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel.getTrnreqseq()) &&
                Objects.equals(getTrntyp(), getProcYm1000wpk0yntransfrmYm560vldtReqnoResponsePoutReqnoDel.getTrntyp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnreqno(),
                getSrcyrncod(),
                getDestyrncod(),
                getWrhnum(),
                getTrnreqseq(),
                getTrntyp());
    }
}