/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm311pk0ReqistYm311vldPalletIdResponse implements Serializable {


    @ColumnAlias("pOutNumcon")
    private Integer poutNumcon;

    @ColumnAlias("pOutPalqty")
    private Integer poutPalqty;

    @ColumnAlias("pQtyreqn")
    private BigDecimal pqtyreqn;

    public Integer getPoutNumcon() {
        return this.poutNumcon;
    }

    public void setPoutNumcon(Integer poutNumcon) {
        this.poutNumcon = poutNumcon;
    }

    public Integer getPoutPalqty() {
        return this.poutPalqty;
    }

    public void setPoutPalqty(Integer poutPalqty) {
        this.poutPalqty = poutPalqty;
    }

    public BigDecimal getPqtyreqn() {
        return this.pqtyreqn;
    }

    public void setPqtyreqn(BigDecimal pqtyreqn) {
        this.pqtyreqn = pqtyreqn;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm311pk0ReqistYm311vldPalletIdResponse)) return false;
        final GetProcYm311pk0ReqistYm311vldPalletIdResponse getProcYm311pk0reqistYm311vldPalletIdResponse = (GetProcYm311pk0ReqistYm311vldPalletIdResponse) o;
        return Objects.equals(getPoutNumcon(), getProcYm311pk0reqistYm311vldPalletIdResponse.getPoutNumcon()) &&
                Objects.equals(getPoutPalqty(), getProcYm311pk0reqistYm311vldPalletIdResponse.getPoutPalqty()) &&
                Objects.equals(getPqtyreqn(), getProcYm311pk0reqistYm311vldPalletIdResponse.getPqtyreqn());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutNumcon(),
                getPoutPalqty(),
                getPqtyreqn());
    }
}