/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0DelflrYm150rgfromWrhResponsePoutWrh implements Serializable {


    @ColumnAlias("STRCOD")
    private String strcod;

    @ColumnAlias("STRDES")
    private String strdes;

    public String getStrcod() {
        return this.strcod;
    }

    public void setStrcod(String strcod) {
        this.strcod = strcod;
    }

    public String getStrdes() {
        return this.strdes;
    }

    public void setStrdes(String strdes) {
        this.strdes = strdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0DelflrYm150rgfromWrhResponsePoutWrh)) return false;
        final GetProcYm1000wpk0DelflrYm150rgfromWrhResponsePoutWrh getProcYm1000wpk0delflrYm150rgfromWrhResponsePoutWrh = (GetProcYm1000wpk0DelflrYm150rgfromWrhResponsePoutWrh) o;
        return Objects.equals(getStrcod(), getProcYm1000wpk0delflrYm150rgfromWrhResponsePoutWrh.getStrcod()) &&
                Objects.equals(getStrdes(), getProcYm1000wpk0delflrYm150rgfromWrhResponsePoutWrh.getStrdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStrcod(),
                getStrdes());
    }
}