/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm430rgreqnumResponsePoutReqnum implements Serializable {


    @ColumnAlias("PALSEQ")
    private String palseq;

    public String getPalseq() {
        return this.palseq;
    }

    public void setPalseq(String palseq) {
        this.palseq = palseq;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm430rgreqnumResponsePoutReqnum)) return false;
        final GetProcYm1000wpk0YntransfrmYm430rgreqnumResponsePoutReqnum getProcYm1000wpk0yntransfrmYm430rgreqnumResponsePoutReqnum = (GetProcYm1000wpk0YntransfrmYm430rgreqnumResponsePoutReqnum) o;
        return Objects.equals(getPalseq(), getProcYm1000wpk0yntransfrmYm430rgreqnumResponsePoutReqnum.getPalseq());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPalseq());
    }
}