/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100accessKnt150Response implements Serializable {


    @ColumnAlias("pOutCount")
    private String poutCount;

    public String getPoutCount() {
        return this.poutCount;
    }

    public void setPoutCount(String poutCount) {
        this.poutCount = poutCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100accessKnt150Response)) return false;
        final GetProcYm1311pk0Ym100accessKnt150Response getProcYm1311pk0ym100accessKnt150response = (GetProcYm1311pk0Ym100accessKnt150Response) o;
        return Objects.equals(getPoutCount(), getProcYm1311pk0ym100accessKnt150response.getPoutCount());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutCount());
    }
}