/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100cpyYrnCodFieldsResponse implements Serializable {


    @ColumnAlias("pYrncnt")
    private String pyrncnt;

    @ColumnAlias("pYrntype")
    private String pyrntype;

    @ColumnAlias("pPly")
    private String pply;

    @ColumnAlias("pRawmaterial")
    private String prawmaterial;

    @ColumnAlias("pYrncat")
    private String pyrncat;

    @ColumnAlias("pOutRawMat")
    private List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat> poutRawMat;

    @ColumnAlias("pOutYrncatdes")
    private List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutYrncatdes> poutYrncatdes;

    @ColumnAlias("pOutYrntypedes")
    private List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutYrntypedes> poutYrntypedes;

    public String getPyrncnt() {
        return this.pyrncnt;
    }

    public void setPyrncnt(String pyrncnt) {
        this.pyrncnt = pyrncnt;
    }

    public String getPyrntype() {
        return this.pyrntype;
    }

    public void setPyrntype(String pyrntype) {
        this.pyrntype = pyrntype;
    }

    public String getPply() {
        return this.pply;
    }

    public void setPply(String pply) {
        this.pply = pply;
    }

    public String getPrawmaterial() {
        return this.prawmaterial;
    }

    public void setPrawmaterial(String prawmaterial) {
        this.prawmaterial = prawmaterial;
    }

    public String getPyrncat() {
        return this.pyrncat;
    }

    public void setPyrncat(String pyrncat) {
        this.pyrncat = pyrncat;
    }

    public List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat> getPoutRawMat() {
        return this.poutRawMat;
    }

    public void setPoutRawMat(List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat> poutRawMat) {
        this.poutRawMat = poutRawMat;
    }

    public List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutYrncatdes> getPoutYrncatdes() {
        return this.poutYrncatdes;
    }

    public void setPoutYrncatdes(List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutYrncatdes> poutYrncatdes) {
        this.poutYrncatdes = poutYrncatdes;
    }

    public List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutYrntypedes> getPoutYrntypedes() {
        return this.poutYrntypedes;
    }

    public void setPoutYrntypedes(List<GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutYrntypedes> poutYrntypedes) {
        this.poutYrntypedes = poutYrntypedes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100cpyYrnCodFieldsResponse)) return false;
        final GetProcYm1311pk0Ym100cpyYrnCodFieldsResponse getProcYm1311pk0ym100cpyYrnCodFieldsResponse = (GetProcYm1311pk0Ym100cpyYrnCodFieldsResponse) o;
        return Objects.equals(getPyrncnt(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPyrncnt()) &&
                Objects.equals(getPyrntype(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPyrntype()) &&
                Objects.equals(getPply(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPply()) &&
                Objects.equals(getPrawmaterial(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPrawmaterial()) &&
                Objects.equals(getPyrncat(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPyrncat()) &&
                Objects.equals(getPoutRawMat(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPoutRawMat()) &&
                Objects.equals(getPoutYrncatdes(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPoutYrncatdes()) &&
                Objects.equals(getPoutYrntypedes(), getProcYm1311pk0ym100cpyYrnCodFieldsResponse.getPoutYrntypedes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPyrncnt(),
                getPyrntype(),
                getPply(),
                getPrawmaterial(),
                getPyrncat(),
                getPoutRawMat(),
                getPoutYrncatdes(),
                getPoutYrntypedes());
    }
}