/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm311pk0ReqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode implements Serializable {


    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("DISPLAYYRNMIXCODE")
    private String displayyrnmixcode;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("NYRNCNT")
    private String nyrncnt;

    @ColumnAlias("YRNLOT")
    private String yrnlot;

    @ColumnAlias("NFYRNCPS")
    private String nfyrncps;

    @ColumnAlias("NYRNCLR")
    private String nyrnclr;

    @ColumnAlias("QTYAVAIL")
    private Double qtyavail;

    @ColumnAlias("QTYAVAIL")
    private Double qtyavail_1;

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public String getDisplayyrnmixcode() {
        return this.displayyrnmixcode;
    }

    public void setDisplayyrnmixcode(String displayyrnmixcode) {
        this.displayyrnmixcode = displayyrnmixcode;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public String getNyrncnt() {
        return this.nyrncnt;
    }

    public void setNyrncnt(String nyrncnt) {
        this.nyrncnt = nyrncnt;
    }

    public String getYrnlot() {
        return this.yrnlot;
    }

    public void setYrnlot(String yrnlot) {
        this.yrnlot = yrnlot;
    }

    public String getNfyrncps() {
        return this.nfyrncps;
    }

    public void setNfyrncps(String nfyrncps) {
        this.nfyrncps = nfyrncps;
    }

    public String getNyrnclr() {
        return this.nyrnclr;
    }

    public void setNyrnclr(String nyrnclr) {
        this.nyrnclr = nyrnclr;
    }

    public Double getQtyavail() {
        return this.qtyavail;
    }

    public void setQtyavail(Double qtyavail) {
        this.qtyavail = qtyavail;
    }

    public Double getQtyavail_1() {
        return this.qtyavail_1;
    }

    public void setQtyavail_1(Double qtyavail_1) {
        this.qtyavail_1 = qtyavail_1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm311pk0ReqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode)) return false;
        final GetProcYm311pk0ReqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode = (GetProcYm311pk0ReqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode) o;
        return Objects.equals(getYrnmixcode(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getYrnmixcode()) &&
                Objects.equals(getDisplayyrnmixcode(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getDisplayyrnmixcode()) &&
                Objects.equals(getYrncod(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getYrncod()) &&
                Objects.equals(getYrnori(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getYrnori()) &&
                Objects.equals(getNyrncnt(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getNyrncnt()) &&
                Objects.equals(getYrnlot(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getYrnlot()) &&
                Objects.equals(getNfyrncps(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getNfyrncps()) &&
                Objects.equals(getNyrnclr(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getNyrnclr()) &&
                Objects.equals(getQtyavail(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getQtyavail()) &&
                Objects.equals(getQtyavail_1(), getProcYm311pk0reqistYm311rgyrnMixCodeResponsePoutRgyrnMixCode.getQtyavail_1());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrnmixcode(),
                getDisplayyrnmixcode(),
                getYrncod(),
                getYrnori(),
                getNyrncnt(),
                getYrnlot(),
                getNfyrncps(),
                getNyrnclr(),
                getQtyavail(),
                getQtyavail_1());
    }
}