/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm4000pk0Ym405prnDesResponse implements Serializable {


    @ColumnAlias("pOutPrnDes")
    private List<GetProcYm4000pk0Ym405prnDesResponsePoutPrnDes> poutPrnDes;

    public List<GetProcYm4000pk0Ym405prnDesResponsePoutPrnDes> getPoutPrnDes() {
        return this.poutPrnDes;
    }

    public void setPoutPrnDes(List<GetProcYm4000pk0Ym405prnDesResponsePoutPrnDes> poutPrnDes) {
        this.poutPrnDes = poutPrnDes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm4000pk0Ym405prnDesResponse)) return false;
        final GetProcYm4000pk0Ym405prnDesResponse getProcYm4000pk0ym405prnDesResponse = (GetProcYm4000pk0Ym405prnDesResponse) o;
        return Objects.equals(getPoutPrnDes(), getProcYm4000pk0ym405prnDesResponse.getPoutPrnDes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutPrnDes());
    }
}