/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm311pk0IstYm312viewTrnsfrHisResponsePoutTrnsfrHis implements Serializable {


    @ColumnAlias("REQNUM")
    private String reqnum;

    @ColumnAlias("TRNNUM")
    private Integer trnnum;

    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("TRNDATE")
    private LocalDateTime trndate;

    @ColumnAlias("FROMWRH")
    private String fromwrh;

    @ColumnAlias("TOWRH")
    private String towrh;

    @ColumnAlias("TRANQTY")
    private Float tranqty;

    @ColumnAlias("QTYREC")
    private Float qtyrec;

    @ColumnAlias("NUMCON")
    private Short numcon;

    @ColumnAlias("DELBY")
    private String delby;

    @ColumnAlias("LORRYID")
    private String lorryid;

    @ColumnAlias("DRIVER")
    private String driver;

    @ColumnAlias("RECBY")
    private String recby;

    @ColumnAlias("DATEREC")
    private LocalDateTime daterec;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("MANUALDN")
    private String manualdn;

    @ColumnAlias("PACKLISTID")
    private String packlistid;

    @ColumnAlias("SEQNUM")
    private Short seqnum;

    @ColumnAlias("PALLETID")
    private String palletid;

    @ColumnAlias("STKUOM")
    private String stkuom;

    @ColumnAlias("STKQTY")
    private Short stkqty;

    @ColumnAlias("W_DESC")
    private String wdesc;

    public String getReqnum() {
        return this.reqnum;
    }

    public void setReqnum(String reqnum) {
        this.reqnum = reqnum;
    }

    public Integer getTrnnum() {
        return this.trnnum;
    }

    public void setTrnnum(Integer trnnum) {
        this.trnnum = trnnum;
    }

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public LocalDateTime getTrndate() {
        return this.trndate;
    }

    public void setTrndate(LocalDateTime trndate) {
        this.trndate = trndate;
    }

    public String getFromwrh() {
        return this.fromwrh;
    }

    public void setFromwrh(String fromwrh) {
        this.fromwrh = fromwrh;
    }

    public String getTowrh() {
        return this.towrh;
    }

    public void setTowrh(String towrh) {
        this.towrh = towrh;
    }

    public Float getTranqty() {
        return this.tranqty;
    }

    public void setTranqty(Float tranqty) {
        this.tranqty = tranqty;
    }

    public Float getQtyrec() {
        return this.qtyrec;
    }

    public void setQtyrec(Float qtyrec) {
        this.qtyrec = qtyrec;
    }

    public Short getNumcon() {
        return this.numcon;
    }

    public void setNumcon(Short numcon) {
        this.numcon = numcon;
    }

    public String getDelby() {
        return this.delby;
    }

    public void setDelby(String delby) {
        this.delby = delby;
    }

    public String getLorryid() {
        return this.lorryid;
    }

    public void setLorryid(String lorryid) {
        this.lorryid = lorryid;
    }

    public String getDriver() {
        return this.driver;
    }

    public void setDriver(String driver) {
        this.driver = driver;
    }

    public String getRecby() {
        return this.recby;
    }

    public void setRecby(String recby) {
        this.recby = recby;
    }

    public LocalDateTime getDaterec() {
        return this.daterec;
    }

    public void setDaterec(LocalDateTime daterec) {
        this.daterec = daterec;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getManualdn() {
        return this.manualdn;
    }

    public void setManualdn(String manualdn) {
        this.manualdn = manualdn;
    }

    public String getPacklistid() {
        return this.packlistid;
    }

    public void setPacklistid(String packlistid) {
        this.packlistid = packlistid;
    }

    public Short getSeqnum() {
        return this.seqnum;
    }

    public void setSeqnum(Short seqnum) {
        this.seqnum = seqnum;
    }

    public String getPalletid() {
        return this.palletid;
    }

    public void setPalletid(String palletid) {
        this.palletid = palletid;
    }

    public String getStkuom() {
        return this.stkuom;
    }

    public void setStkuom(String stkuom) {
        this.stkuom = stkuom;
    }

    public Short getStkqty() {
        return this.stkqty;
    }

    public void setStkqty(Short stkqty) {
        this.stkqty = stkqty;
    }

    public String getWdesc() {
        return this.wdesc;
    }

    public void setWdesc(String wdesc) {
        this.wdesc = wdesc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm311pk0IstYm312viewTrnsfrHisResponsePoutTrnsfrHis)) return false;
        final GetProcYm311pk0IstYm312viewTrnsfrHisResponsePoutTrnsfrHis getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis = (GetProcYm311pk0IstYm312viewTrnsfrHisResponsePoutTrnsfrHis) o;
        return Objects.equals(getReqnum(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getReqnum()) &&
                Objects.equals(getTrnnum(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getTrnnum()) &&
                Objects.equals(getYrnmixcode(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getYrnmixcode()) &&
                Objects.equals(getTrndate(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getTrndate()) &&
                Objects.equals(getFromwrh(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getFromwrh()) &&
                Objects.equals(getTowrh(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getTowrh()) &&
                Objects.equals(getTranqty(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getTranqty()) &&
                Objects.equals(getQtyrec(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getQtyrec()) &&
                Objects.equals(getNumcon(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getNumcon()) &&
                Objects.equals(getDelby(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getDelby()) &&
                Objects.equals(getLorryid(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getLorryid()) &&
                Objects.equals(getDriver(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getDriver()) &&
                Objects.equals(getRecby(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getRecby()) &&
                Objects.equals(getDaterec(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getDaterec()) &&
                Objects.equals(getRemarks(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getRemarks()) &&
                Objects.equals(getManualdn(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getManualdn()) &&
                Objects.equals(getPacklistid(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getPacklistid()) &&
                Objects.equals(getSeqnum(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getSeqnum()) &&
                Objects.equals(getPalletid(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getPalletid()) &&
                Objects.equals(getStkuom(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getStkuom()) &&
                Objects.equals(getStkqty(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getStkqty()) &&
                Objects.equals(getWdesc(), getProcYm311pk0istYm312viewTrnsfrHisResponsePoutTrnsfrHis.getWdesc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getReqnum(),
                getTrnnum(),
                getYrnmixcode(),
                getTrndate(),
                getFromwrh(),
                getTowrh(),
                getTranqty(),
                getQtyrec(),
                getNumcon(),
                getDelby(),
                getLorryid(),
                getDriver(),
                getRecby(),
                getDaterec(),
                getRemarks(),
                getManualdn(),
                getPacklistid(),
                getSeqnum(),
                getPalletid(),
                getStkuom(),
                getStkqty(),
                getWdesc());
    }
}