/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100rgrpurclrseqResponsePoutRgrpurclrseq implements Serializable {


    @ColumnAlias("PURCLRSEQ")
    private Byte purclrseq;

    @ColumnAlias("PURCLRDES")
    private String purclrdes;

    public Byte getPurclrseq() {
        return this.purclrseq;
    }

    public void setPurclrseq(Byte purclrseq) {
        this.purclrseq = purclrseq;
    }

    public String getPurclrdes() {
        return this.purclrdes;
    }

    public void setPurclrdes(String purclrdes) {
        this.purclrdes = purclrdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100rgrpurclrseqResponsePoutRgrpurclrseq)) return false;
        final GetProcYm1311pk0Ym100rgrpurclrseqResponsePoutRgrpurclrseq getProcYm1311pk0ym100rgrpurclrseqResponsePoutRgrpurclrseq = (GetProcYm1311pk0Ym100rgrpurclrseqResponsePoutRgrpurclrseq) o;
        return Objects.equals(getPurclrseq(), getProcYm1311pk0ym100rgrpurclrseqResponsePoutRgrpurclrseq.getPurclrseq()) &&
                Objects.equals(getPurclrdes(), getProcYm1311pk0ym100rgrpurclrseqResponsePoutRgrpurclrseq.getPurclrdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPurclrseq(),
                getPurclrdes());
    }
}