/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnretYm160vldtYnretidResponse implements Serializable {


    @ColumnAlias("pOutOrdnum")
    private String poutOrdnum;

    @ColumnAlias("pOutfabseq")
    private Integer poutfabseq;

    @ColumnAlias("pOutYrnid")
    private Integer poutYrnid;

    @ColumnAlias("pOutKmchcod")
    private String poutKmchcod;

    public String getPoutOrdnum() {
        return this.poutOrdnum;
    }

    public void setPoutOrdnum(String poutOrdnum) {
        this.poutOrdnum = poutOrdnum;
    }

    public Integer getPoutfabseq() {
        return this.poutfabseq;
    }

    public void setPoutfabseq(Integer poutfabseq) {
        this.poutfabseq = poutfabseq;
    }

    public Integer getPoutYrnid() {
        return this.poutYrnid;
    }

    public void setPoutYrnid(Integer poutYrnid) {
        this.poutYrnid = poutYrnid;
    }

    public String getPoutKmchcod() {
        return this.poutKmchcod;
    }

    public void setPoutKmchcod(String poutKmchcod) {
        this.poutKmchcod = poutKmchcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnretYm160vldtYnretidResponse)) return false;
        final GetProcYm1000wpk0YnretYm160vldtYnretidResponse getProcYm1000wpk0ynretYm160vldtYnretidResponse = (GetProcYm1000wpk0YnretYm160vldtYnretidResponse) o;
        return Objects.equals(getPoutOrdnum(), getProcYm1000wpk0ynretYm160vldtYnretidResponse.getPoutOrdnum()) &&
                Objects.equals(getPoutfabseq(), getProcYm1000wpk0ynretYm160vldtYnretidResponse.getPoutfabseq()) &&
                Objects.equals(getPoutYrnid(), getProcYm1000wpk0ynretYm160vldtYnretidResponse.getPoutYrnid()) &&
                Objects.equals(getPoutKmchcod(), getProcYm1000wpk0ynretYm160vldtYnretidResponse.getPoutKmchcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutOrdnum(),
                getPoutfabseq(),
                getPoutYrnid(),
                getPoutKmchcod());
    }
}