/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YntransfrmYm430destPalResponsePoutDestpal implements Serializable {


    @ColumnAlias("PALMODNUM")
    private String palmodnum;

    @ColumnAlias("DESTPALLET_SEQ")
    private Short destpalletSeq;

    @ColumnAlias("DESTPALLETID")
    private String destpalletid;

    public String getPalmodnum() {
        return this.palmodnum;
    }

    public void setPalmodnum(String palmodnum) {
        this.palmodnum = palmodnum;
    }

    public Short getDestpalletSeq() {
        return this.destpalletSeq;
    }

    public void setDestpalletSeq(Short destpalletSeq) {
        this.destpalletSeq = destpalletSeq;
    }

    public String getDestpalletid() {
        return this.destpalletid;
    }

    public void setDestpalletid(String destpalletid) {
        this.destpalletid = destpalletid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YntransfrmYm430destPalResponsePoutDestpal)) return false;
        final GetProcYm1000wpk0YntransfrmYm430destPalResponsePoutDestpal getProcYm1000wpk0yntransfrmYm430destPalResponsePoutDestpal = (GetProcYm1000wpk0YntransfrmYm430destPalResponsePoutDestpal) o;
        return Objects.equals(getPalmodnum(), getProcYm1000wpk0yntransfrmYm430destPalResponsePoutDestpal.getPalmodnum()) &&
                Objects.equals(getDestpalletSeq(), getProcYm1000wpk0yntransfrmYm430destPalResponsePoutDestpal.getDestpalletSeq()) &&
                Objects.equals(getDestpalletid(), getProcYm1000wpk0yntransfrmYm430destPalResponsePoutDestpal.getDestpalletid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPalmodnum(),
                getDestpalletSeq(),
                getDestpalletid());
    }
}