/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat implements Serializable {


    @ColumnAlias("MAINDES")
    private String maindes;

    @ColumnAlias("SUBDES")
    private String subdes;

    public String getMaindes() {
        return this.maindes;
    }

    public void setMaindes(String maindes) {
        this.maindes = maindes;
    }

    public String getSubdes() {
        return this.subdes;
    }

    public void setSubdes(String subdes) {
        this.subdes = subdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat)) return false;
        final GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat getProcYm1311pk0ym100cpyYrnCodFieldsResponsePoutRawMat = (GetProcYm1311pk0Ym100cpyYrnCodFieldsResponsePoutRawMat) o;
        return Objects.equals(getMaindes(), getProcYm1311pk0ym100cpyYrnCodFieldsResponsePoutRawMat.getMaindes()) &&
                Objects.equals(getSubdes(), getProcYm1311pk0ym100cpyYrnCodFieldsResponsePoutRawMat.getSubdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMaindes(),
                getSubdes());
    }
}