/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0Ym100fibCdesResponsePoutFibCdes implements Serializable {


    @ColumnAlias("NYRNCDES")
    private String nyrncdes;

    public String getNyrncdes() {
        return this.nyrncdes;
    }

    public void setNyrncdes(String nyrncdes) {
        this.nyrncdes = nyrncdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0Ym100fibCdesResponsePoutFibCdes)) return false;
        final GetProcYm1311pk0Ym100fibCdesResponsePoutFibCdes getProcYm1311pk0ym100fibCdesResponsePoutFibCdes = (GetProcYm1311pk0Ym100fibCdesResponsePoutFibCdes) o;
        return Objects.equals(getNyrncdes(), getProcYm1311pk0ym100fibCdesResponsePoutFibCdes.getNyrncdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNyrncdes());
    }
}