/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1311pk0YrntextfldResponse implements Serializable {


    @ColumnAlias("pOutSts")
    private String poutSts;

    public String getPoutSts() {
        return this.poutSts;
    }

    public void setPoutSts(String poutSts) {
        this.poutSts = poutSts;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1311pk0YrntextfldResponse)) return false;
        final GetProcYm1311pk0YrntextfldResponse getProcYm1311pk0yrntextfldResponse = (GetProcYm1311pk0YrntextfldResponse) o;
        return Objects.equals(getPoutSts(), getProcYm1311pk0yrntextfldResponse.getPoutSts());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutSts());
    }
}