/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnreqnYm144vldtNumfedResponse implements Serializable {


    @ColumnAlias("pPalwgt")
    private BigDecimal ppalwgt;

    @ColumnAlias("pExtotpal")
    private BigDecimal pextotpal;

    @ColumnAlias("pTotpal")
    private BigDecimal ptotpal;

    public BigDecimal getPpalwgt() {
        return this.ppalwgt;
    }

    public void setPpalwgt(BigDecimal ppalwgt) {
        this.ppalwgt = ppalwgt;
    }

    public BigDecimal getPextotpal() {
        return this.pextotpal;
    }

    public void setPextotpal(BigDecimal pextotpal) {
        this.pextotpal = pextotpal;
    }

    public BigDecimal getPtotpal() {
        return this.ptotpal;
    }

    public void setPtotpal(BigDecimal ptotpal) {
        this.ptotpal = ptotpal;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnreqnYm144vldtNumfedResponse)) return false;
        final GetProcYm1000wpk0YnreqnYm144vldtNumfedResponse getProcYm1000wpk0ynreqnYm144vldtNumfedResponse = (GetProcYm1000wpk0YnreqnYm144vldtNumfedResponse) o;
        return Objects.equals(getPpalwgt(), getProcYm1000wpk0ynreqnYm144vldtNumfedResponse.getPpalwgt()) &&
                Objects.equals(getPextotpal(), getProcYm1000wpk0ynreqnYm144vldtNumfedResponse.getPextotpal()) &&
                Objects.equals(getPtotpal(), getProcYm1000wpk0ynreqnYm144vldtNumfedResponse.getPtotpal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPpalwgt(),
                getPextotpal(),
                getPtotpal());
    }
}