/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0DelflrYm322calBalanceResponse implements Serializable {


    @ColumnAlias("pOutbalance")
    private BigDecimal poutbalance;

    @ColumnAlias("pOutreqcon")
    private BigDecimal poutreqcon;

    public BigDecimal getPoutbalance() {
        return this.poutbalance;
    }

    public void setPoutbalance(BigDecimal poutbalance) {
        this.poutbalance = poutbalance;
    }

    public BigDecimal getPoutreqcon() {
        return this.poutreqcon;
    }

    public void setPoutreqcon(BigDecimal poutreqcon) {
        this.poutreqcon = poutreqcon;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0DelflrYm322calBalanceResponse)) return false;
        final GetProcYm1000wpk0DelflrYm322calBalanceResponse getProcYm1000wpk0delflrYm322calBalanceResponse = (GetProcYm1000wpk0DelflrYm322calBalanceResponse) o;
        return Objects.equals(getPoutbalance(), getProcYm1000wpk0delflrYm322calBalanceResponse.getPoutbalance()) &&
                Objects.equals(getPoutreqcon(), getProcYm1000wpk0delflrYm322calBalanceResponse.getPoutreqcon());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutbalance(),
                getPoutreqcon());
    }
}