/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnreqnYm144rgyrnIdResponsePoutYrnid implements Serializable {


    @ColumnAlias("YRNID")
    private Short yrnid;

    @ColumnAlias("ALCSEQ")
    private Short alcseq;

    @ColumnAlias("QTYALC")
    private BigDecimal qtyalc;

    public Short getYrnid() {
        return this.yrnid;
    }

    public void setYrnid(Short yrnid) {
        this.yrnid = yrnid;
    }

    public Short getAlcseq() {
        return this.alcseq;
    }

    public void setAlcseq(Short alcseq) {
        this.alcseq = alcseq;
    }

    public BigDecimal getQtyalc() {
        return this.qtyalc;
    }

    public void setQtyalc(BigDecimal qtyalc) {
        this.qtyalc = qtyalc;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnreqnYm144rgyrnIdResponsePoutYrnid)) return false;
        final GetProcYm1000wpk0YnreqnYm144rgyrnIdResponsePoutYrnid getProcYm1000wpk0ynreqnYm144rgyrnIdResponsePoutYrnid = (GetProcYm1000wpk0YnreqnYm144rgyrnIdResponsePoutYrnid) o;
        return Objects.equals(getYrnid(), getProcYm1000wpk0ynreqnYm144rgyrnIdResponsePoutYrnid.getYrnid()) &&
                Objects.equals(getAlcseq(), getProcYm1000wpk0ynreqnYm144rgyrnIdResponsePoutYrnid.getAlcseq()) &&
                Objects.equals(getQtyalc(), getProcYm1000wpk0ynreqnYm144rgyrnIdResponsePoutYrnid.getQtyalc());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrnid(),
                getAlcseq(),
                getQtyalc());
    }
}