/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetProcYm1000wpk0YnreqnYm142masterResponsePoutmaster implements Serializable {


    @ColumnAlias("REQNSEQ")
    private Byte reqnseq;

    @ColumnAlias("YRNIDSEQ")
    private Byte yrnidseq;

    @ColumnAlias("WRHNUM")
    private String wrhnum;

    @ColumnAlias("REQNUM")
    private Integer reqnum;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("YRNID")
    private Short yrnid;

    @ColumnAlias("ALCSEQ")
    private Short alcseq;

    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("KMCHCOD")
    private String kmchcod;

    @ColumnAlias("W_KMCHFLRID")
    private String wkmchflrid;

    @ColumnAlias("QTYREQN")
    private Double qtyreqn;

    @ColumnAlias("TOTQTYDEL")
    private Double totqtydel;

    @ColumnAlias("TOTQTYRET")
    private Double totqtyret;

    @ColumnAlias("W_TOTNETQTYDEL")
    private BigDecimal wtotnetqtydel;

    @ColumnAlias("W_TOTQTYREQ")
    private BigDecimal wtotqtyreq;

    @ColumnAlias("W_TOTQTYDEL")
    private BigDecimal wtotqtydel;

    @ColumnAlias("W_TOTQTYRET")
    private BigDecimal wtotqtyret;

    @ColumnAlias("W_TOTAL_NETQTYDEL")
    private BigDecimal wtotalNetqtydel;

    @ColumnAlias("W_SUMTOTPAL")
    private BigDecimal wsumtotpal;

    @ColumnAlias("W_TOTPALDEL")
    private BigDecimal wtotpaldel;

    @ColumnAlias("TOTPAL")
    private Byte totpal;

    @ColumnAlias("TOTPALDEL")
    private Byte totpaldel;

    @ColumnAlias("DATEREQ")
    private LocalDateTime datereq;

    @ColumnAlias("USRID")
    private String usrid;

    public Byte getReqnseq() {
        return this.reqnseq;
    }

    public void setReqnseq(Byte reqnseq) {
        this.reqnseq = reqnseq;
    }

    public Byte getYrnidseq() {
        return this.yrnidseq;
    }

    public void setYrnidseq(Byte yrnidseq) {
        this.yrnidseq = yrnidseq;
    }

    public String getWrhnum() {
        return this.wrhnum;
    }

    public void setWrhnum(String wrhnum) {
        this.wrhnum = wrhnum;
    }

    public Integer getReqnum() {
        return this.reqnum;
    }

    public void setReqnum(Integer reqnum) {
        this.reqnum = reqnum;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public Short getYrnid() {
        return this.yrnid;
    }

    public void setYrnid(Short yrnid) {
        this.yrnid = yrnid;
    }

    public Short getAlcseq() {
        return this.alcseq;
    }

    public void setAlcseq(Short alcseq) {
        this.alcseq = alcseq;
    }

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getKmchcod() {
        return this.kmchcod;
    }

    public void setKmchcod(String kmchcod) {
        this.kmchcod = kmchcod;
    }

    public String getWkmchflrid() {
        return this.wkmchflrid;
    }

    public void setWkmchflrid(String wkmchflrid) {
        this.wkmchflrid = wkmchflrid;
    }

    public Double getQtyreqn() {
        return this.qtyreqn;
    }

    public void setQtyreqn(Double qtyreqn) {
        this.qtyreqn = qtyreqn;
    }

    public Double getTotqtydel() {
        return this.totqtydel;
    }

    public void setTotqtydel(Double totqtydel) {
        this.totqtydel = totqtydel;
    }

    public Double getTotqtyret() {
        return this.totqtyret;
    }

    public void setTotqtyret(Double totqtyret) {
        this.totqtyret = totqtyret;
    }

    public BigDecimal getWtotnetqtydel() {
        return this.wtotnetqtydel;
    }

    public void setWtotnetqtydel(BigDecimal wtotnetqtydel) {
        this.wtotnetqtydel = wtotnetqtydel;
    }

    public BigDecimal getWtotqtyreq() {
        return this.wtotqtyreq;
    }

    public void setWtotqtyreq(BigDecimal wtotqtyreq) {
        this.wtotqtyreq = wtotqtyreq;
    }

    public BigDecimal getWtotqtydel() {
        return this.wtotqtydel;
    }

    public void setWtotqtydel(BigDecimal wtotqtydel) {
        this.wtotqtydel = wtotqtydel;
    }

    public BigDecimal getWtotqtyret() {
        return this.wtotqtyret;
    }

    public void setWtotqtyret(BigDecimal wtotqtyret) {
        this.wtotqtyret = wtotqtyret;
    }

    public BigDecimal getWtotalNetqtydel() {
        return this.wtotalNetqtydel;
    }

    public void setWtotalNetqtydel(BigDecimal wtotalNetqtydel) {
        this.wtotalNetqtydel = wtotalNetqtydel;
    }

    public BigDecimal getWsumtotpal() {
        return this.wsumtotpal;
    }

    public void setWsumtotpal(BigDecimal wsumtotpal) {
        this.wsumtotpal = wsumtotpal;
    }

    public BigDecimal getWtotpaldel() {
        return this.wtotpaldel;
    }

    public void setWtotpaldel(BigDecimal wtotpaldel) {
        this.wtotpaldel = wtotpaldel;
    }

    public Byte getTotpal() {
        return this.totpal;
    }

    public void setTotpal(Byte totpal) {
        this.totpal = totpal;
    }

    public Byte getTotpaldel() {
        return this.totpaldel;
    }

    public void setTotpaldel(Byte totpaldel) {
        this.totpaldel = totpaldel;
    }

    public LocalDateTime getDatereq() {
        return this.datereq;
    }

    public void setDatereq(LocalDateTime datereq) {
        this.datereq = datereq;
    }

    public String getUsrid() {
        return this.usrid;
    }

    public void setUsrid(String usrid) {
        this.usrid = usrid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetProcYm1000wpk0YnreqnYm142masterResponsePoutmaster)) return false;
        final GetProcYm1000wpk0YnreqnYm142masterResponsePoutmaster getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster = (GetProcYm1000wpk0YnreqnYm142masterResponsePoutmaster) o;
        return Objects.equals(getReqnseq(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getReqnseq()) &&
                Objects.equals(getYrnidseq(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getYrnidseq()) &&
                Objects.equals(getWrhnum(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWrhnum()) &&
                Objects.equals(getReqnum(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getReqnum()) &&
                Objects.equals(getOrdnum(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getOrdnum()) &&
                Objects.equals(getFabseq(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getFabseq()) &&
                Objects.equals(getYrnid(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getYrnid()) &&
                Objects.equals(getAlcseq(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getAlcseq()) &&
                Objects.equals(getYrnmixcode(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getYrnmixcode()) &&
                Objects.equals(getYrncod(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getYrncod()) &&
                Objects.equals(getKmchcod(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getKmchcod()) &&
                Objects.equals(getWkmchflrid(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWkmchflrid()) &&
                Objects.equals(getQtyreqn(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getQtyreqn()) &&
                Objects.equals(getTotqtydel(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getTotqtydel()) &&
                Objects.equals(getTotqtyret(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getTotqtyret()) &&
                Objects.equals(getWtotnetqtydel(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWtotnetqtydel()) &&
                Objects.equals(getWtotqtyreq(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWtotqtyreq()) &&
                Objects.equals(getWtotqtydel(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWtotqtydel()) &&
                Objects.equals(getWtotqtyret(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWtotqtyret()) &&
                Objects.equals(getWtotalNetqtydel(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWtotalNetqtydel()) &&
                Objects.equals(getWsumtotpal(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWsumtotpal()) &&
                Objects.equals(getWtotpaldel(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getWtotpaldel()) &&
                Objects.equals(getTotpal(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getTotpal()) &&
                Objects.equals(getTotpaldel(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getTotpaldel()) &&
                Objects.equals(getDatereq(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getDatereq()) &&
                Objects.equals(getUsrid(), getProcYm1000wpk0ynreqnYm142masterResponsePoutmaster.getUsrid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getReqnseq(),
                getYrnidseq(),
                getWrhnum(),
                getReqnum(),
                getOrdnum(),
                getFabseq(),
                getYrnid(),
                getAlcseq(),
                getYrnmixcode(),
                getYrncod(),
                getKmchcod(),
                getWkmchflrid(),
                getQtyreqn(),
                getTotqtydel(),
                getTotqtyret(),
                getWtotnetqtydel(),
                getWtotqtyreq(),
                getWtotqtydel(),
                getWtotqtyret(),
                getWtotalNetqtydel(),
                getWsumtotpal(),
                getWtotpaldel(),
                getTotpal(),
                getTotpaldel(),
                getDatereq(),
                getUsrid());
    }
}