/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class PorcYm1311pk0Ym100nyrnsubqltyeResponse implements Serializable {


    @ColumnAlias("poutNYRNSUBQLTYE")
    private List<PorcYm1311pk0Ym100nyrnsubqltyeResponsePoutNyrnsubqltye> poutNyrnsubqltye;

    public List<PorcYm1311pk0Ym100nyrnsubqltyeResponsePoutNyrnsubqltye> getPoutNyrnsubqltye() {
        return this.poutNyrnsubqltye;
    }

    public void setPoutNyrnsubqltye(List<PorcYm1311pk0Ym100nyrnsubqltyeResponsePoutNyrnsubqltye> poutNyrnsubqltye) {
        this.poutNyrnsubqltye = poutNyrnsubqltye;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PorcYm1311pk0Ym100nyrnsubqltyeResponse)) return false;
        final PorcYm1311pk0Ym100nyrnsubqltyeResponse porcYm1311pk0ym100nyrnsubqltyeResponse = (PorcYm1311pk0Ym100nyrnsubqltyeResponse) o;
        return Objects.equals(getPoutNyrnsubqltye(), porcYm1311pk0ym100nyrnsubqltyeResponse.getPoutNyrnsubqltye());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutNyrnsubqltye());
    }
}