/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym284validateReqnumResponse implements Serializable {


    @ColumnAlias("poutqtyreqn")
    private Float poutqtyreqn;

    @ColumnAlias("poutwrhnum")
    private String poutwrhnum;

    @ColumnAlias("pcartonqtyavail")
    private Float pcartonqtyavail;

    @ColumnAlias("premaintotransfer")
    private Float premaintotransfer;

    @ColumnAlias("pcartonedqty")
    private Float pcartonedqty;

    @ColumnAlias("ptotalcartonedqty")
    private Float ptotalcartonedqty;

    public Float getPoutqtyreqn() {
        return this.poutqtyreqn;
    }

    public void setPoutqtyreqn(Float poutqtyreqn) {
        this.poutqtyreqn = poutqtyreqn;
    }

    public String getPoutwrhnum() {
        return this.poutwrhnum;
    }

    public void setPoutwrhnum(String poutwrhnum) {
        this.poutwrhnum = poutwrhnum;
    }

    public Float getPcartonqtyavail() {
        return this.pcartonqtyavail;
    }

    public void setPcartonqtyavail(Float pcartonqtyavail) {
        this.pcartonqtyavail = pcartonqtyavail;
    }

    public Float getPremaintotransfer() {
        return this.premaintotransfer;
    }

    public void setPremaintotransfer(Float premaintotransfer) {
        this.premaintotransfer = premaintotransfer;
    }

    public Float getPcartonedqty() {
        return this.pcartonedqty;
    }

    public void setPcartonedqty(Float pcartonedqty) {
        this.pcartonedqty = pcartonedqty;
    }

    public Float getPtotalcartonedqty() {
        return this.ptotalcartonedqty;
    }

    public void setPtotalcartonedqty(Float ptotalcartonedqty) {
        this.ptotalcartonedqty = ptotalcartonedqty;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym284validateReqnumResponse)) return false;
        final ProcYm1311pk0Ym284validateReqnumResponse procYm1311pk0ym284validateReqnumResponse = (ProcYm1311pk0Ym284validateReqnumResponse) o;
        return Objects.equals(getPoutqtyreqn(), procYm1311pk0ym284validateReqnumResponse.getPoutqtyreqn()) &&
                Objects.equals(getPoutwrhnum(), procYm1311pk0ym284validateReqnumResponse.getPoutwrhnum()) &&
                Objects.equals(getPcartonqtyavail(), procYm1311pk0ym284validateReqnumResponse.getPcartonqtyavail()) &&
                Objects.equals(getPremaintotransfer(), procYm1311pk0ym284validateReqnumResponse.getPremaintotransfer()) &&
                Objects.equals(getPcartonedqty(), procYm1311pk0ym284validateReqnumResponse.getPcartonedqty()) &&
                Objects.equals(getPtotalcartonedqty(), procYm1311pk0ym284validateReqnumResponse.getPtotalcartonedqty());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutqtyreqn(),
                getPoutwrhnum(),
                getPcartonqtyavail(),
                getPremaintotransfer(),
                getPcartonedqty(),
                getPtotalcartonedqty());
    }
}