/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pk0Ym400rgYrnSubQltyBResponse implements Serializable {


    @ColumnAlias("pOutRgYrnSubQltyB")
    private List<ProcYm4000pk0Ym400rgYrnSubQltyBResponsePoutRgYrnSubQltyB> poutRgYrnSubQltyB;

    public List<ProcYm4000pk0Ym400rgYrnSubQltyBResponsePoutRgYrnSubQltyB> getPoutRgYrnSubQltyB() {
        return this.poutRgYrnSubQltyB;
    }

    public void setPoutRgYrnSubQltyB(List<ProcYm4000pk0Ym400rgYrnSubQltyBResponsePoutRgYrnSubQltyB> poutRgYrnSubQltyB) {
        this.poutRgYrnSubQltyB = poutRgYrnSubQltyB;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pk0Ym400rgYrnSubQltyBResponse)) return false;
        final ProcYm4000pk0Ym400rgYrnSubQltyBResponse procYm4000pk0ym400rgYrnSubQltyBresponse = (ProcYm4000pk0Ym400rgYrnSubQltyBResponse) o;
        return Objects.equals(getPoutRgYrnSubQltyB(), procYm4000pk0ym400rgYrnSubQltyBresponse.getPoutRgYrnSubQltyB());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutRgYrnSubQltyB());
    }
}