/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym100subcntcpsResponse implements Serializable {


    @ColumnAlias("poutYM100SUBCNTCPS")
    private List<ProcYm1311pk0Ym100subcntcpsResponsePoutYm100subcntcps> poutYm100subcntcps;

    public List<ProcYm1311pk0Ym100subcntcpsResponsePoutYm100subcntcps> getPoutYm100subcntcps() {
        return this.poutYm100subcntcps;
    }

    public void setPoutYm100subcntcps(List<ProcYm1311pk0Ym100subcntcpsResponsePoutYm100subcntcps> poutYm100subcntcps) {
        this.poutYm100subcntcps = poutYm100subcntcps;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym100subcntcpsResponse)) return false;
        final ProcYm1311pk0Ym100subcntcpsResponse procYm1311pk0ym100subcntcpsResponse = (ProcYm1311pk0Ym100subcntcpsResponse) o;
        return Objects.equals(getPoutYm100subcntcps(), procYm1311pk0ym100subcntcpsResponse.getPoutYm100subcntcps());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYm100subcntcps());
    }
}