/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pk0Ym400contdetResponsePoutContdet implements Serializable {


    @ColumnAlias("CONTRACTID")
    private String contractid;

    @ColumnAlias("YNITEMNO")
    private Byte ynitemno;

    @ColumnAlias("CONTAINER_SEQ")
    private Short containerSeq;

    @ColumnAlias("EXPRECDAT")
    private LocalDateTime exprecdat;

    @ColumnAlias("PLNKGS")
    private Double plnkgs;

    @ColumnAlias("SHPMOD")
    private String shpmod;

    @ColumnAlias("W_SHIPMOD")
    private String wshipmod;

    @ColumnAlias("CONTAINERQTY")
    private Byte containerqty;

    @ColumnAlias("CONTAINER_TYPE")
    private String containerType;

    @ColumnAlias("W_CONTAINER_TYPE")
    private String wcontainerType;

    @ColumnAlias("SHIPLINE")
    private String shipline;

    @ColumnAlias("CONTAINERNUM")
    private String containernum;

    @ColumnAlias("LADINGBILL")
    private String ladingbill;

    @ColumnAlias("VESSNAME")
    private String vessname;

    @ColumnAlias("VOYAGE")
    private String voyage;

    @ColumnAlias("EXPDEPARTUREDAT")
    private LocalDateTime expdeparturedat;

    @ColumnAlias("EXPARRIVALDAT")
    private LocalDateTime exparrivaldat;

    @ColumnAlias("ACTARRIVALDAT")
    private LocalDateTime actarrivaldat;

    @ColumnAlias("QTYREC")
    private Double qtyrec;

    @ColumnAlias("MANUDAT")
    private LocalDateTime manudat;

    @ColumnAlias("RLOTNUM")
    private String rlotnum;

    @ColumnAlias("FLRLOTNUM")
    private String flrlotnum;

    @ColumnAlias("FLRYRNORI")
    private String flryrnori;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("W_FLRLOTNUM")
    private String wflrlotnum;

    @ColumnAlias("W_FLRYRNORI")
    private String wflryrnori;

    @ColumnAlias("W_DATEREC")
    private String wdaterec;

    @ColumnAlias("W_TOTAL")
    private BigDecimal wtotal;

    @ColumnAlias("W_TOTQTYRCV")
    private BigDecimal wtotqtyrcv;

    @ColumnAlias("LC_DATE")
    private LocalDateTime lcDate;

    @ColumnAlias("LC_NO")
    private String lcNo;

    @ColumnAlias("PAID_STS")
    private String paidSts;

    @ColumnAlias("LC_STSDES")
    private String lcStsdes;

    public String getContractid() {
        return this.contractid;
    }

    public void setContractid(String contractid) {
        this.contractid = contractid;
    }

    public Byte getYnitemno() {
        return this.ynitemno;
    }

    public void setYnitemno(Byte ynitemno) {
        this.ynitemno = ynitemno;
    }

    public Short getContainerSeq() {
        return this.containerSeq;
    }

    public void setContainerSeq(Short containerSeq) {
        this.containerSeq = containerSeq;
    }

    public LocalDateTime getExprecdat() {
        return this.exprecdat;
    }

    public void setExprecdat(LocalDateTime exprecdat) {
        this.exprecdat = exprecdat;
    }

    public Double getPlnkgs() {
        return this.plnkgs;
    }

    public void setPlnkgs(Double plnkgs) {
        this.plnkgs = plnkgs;
    }

    public String getShpmod() {
        return this.shpmod;
    }

    public void setShpmod(String shpmod) {
        this.shpmod = shpmod;
    }

    public String getWshipmod() {
        return this.wshipmod;
    }

    public void setWshipmod(String wshipmod) {
        this.wshipmod = wshipmod;
    }

    public Byte getContainerqty() {
        return this.containerqty;
    }

    public void setContainerqty(Byte containerqty) {
        this.containerqty = containerqty;
    }

    public String getContainerType() {
        return this.containerType;
    }

    public void setContainerType(String containerType) {
        this.containerType = containerType;
    }

    public String getWcontainerType() {
        return this.wcontainerType;
    }

    public void setWcontainerType(String wcontainerType) {
        this.wcontainerType = wcontainerType;
    }

    public String getShipline() {
        return this.shipline;
    }

    public void setShipline(String shipline) {
        this.shipline = shipline;
    }

    public String getContainernum() {
        return this.containernum;
    }

    public void setContainernum(String containernum) {
        this.containernum = containernum;
    }

    public String getLadingbill() {
        return this.ladingbill;
    }

    public void setLadingbill(String ladingbill) {
        this.ladingbill = ladingbill;
    }

    public String getVessname() {
        return this.vessname;
    }

    public void setVessname(String vessname) {
        this.vessname = vessname;
    }

    public String getVoyage() {
        return this.voyage;
    }

    public void setVoyage(String voyage) {
        this.voyage = voyage;
    }

    public LocalDateTime getExpdeparturedat() {
        return this.expdeparturedat;
    }

    public void setExpdeparturedat(LocalDateTime expdeparturedat) {
        this.expdeparturedat = expdeparturedat;
    }

    public LocalDateTime getExparrivaldat() {
        return this.exparrivaldat;
    }

    public void setExparrivaldat(LocalDateTime exparrivaldat) {
        this.exparrivaldat = exparrivaldat;
    }

    public LocalDateTime getActarrivaldat() {
        return this.actarrivaldat;
    }

    public void setActarrivaldat(LocalDateTime actarrivaldat) {
        this.actarrivaldat = actarrivaldat;
    }

    public Double getQtyrec() {
        return this.qtyrec;
    }

    public void setQtyrec(Double qtyrec) {
        this.qtyrec = qtyrec;
    }

    public LocalDateTime getManudat() {
        return this.manudat;
    }

    public void setManudat(LocalDateTime manudat) {
        this.manudat = manudat;
    }

    public String getRlotnum() {
        return this.rlotnum;
    }

    public void setRlotnum(String rlotnum) {
        this.rlotnum = rlotnum;
    }

    public String getFlrlotnum() {
        return this.flrlotnum;
    }

    public void setFlrlotnum(String flrlotnum) {
        this.flrlotnum = flrlotnum;
    }

    public String getFlryrnori() {
        return this.flryrnori;
    }

    public void setFlryrnori(String flryrnori) {
        this.flryrnori = flryrnori;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getWflrlotnum() {
        return this.wflrlotnum;
    }

    public void setWflrlotnum(String wflrlotnum) {
        this.wflrlotnum = wflrlotnum;
    }

    public String getWflryrnori() {
        return this.wflryrnori;
    }

    public void setWflryrnori(String wflryrnori) {
        this.wflryrnori = wflryrnori;
    }

    public String getWdaterec() {
        return this.wdaterec;
    }

    public void setWdaterec(String wdaterec) {
        this.wdaterec = wdaterec;
    }

    public BigDecimal getWtotal() {
        return this.wtotal;
    }

    public void setWtotal(BigDecimal wtotal) {
        this.wtotal = wtotal;
    }

    public BigDecimal getWtotqtyrcv() {
        return this.wtotqtyrcv;
    }

    public void setWtotqtyrcv(BigDecimal wtotqtyrcv) {
        this.wtotqtyrcv = wtotqtyrcv;
    }

    public LocalDateTime getLcDate() {
        return this.lcDate;
    }

    public void setLcDate(LocalDateTime lcDate) {
        this.lcDate = lcDate;
    }

    public String getLcNo() {
        return this.lcNo;
    }

    public void setLcNo(String lcNo) {
        this.lcNo = lcNo;
    }

    public String getPaidSts() {
        return this.paidSts;
    }

    public void setPaidSts(String paidSts) {
        this.paidSts = paidSts;
    }

    public String getLcStsdes() {
        return this.lcStsdes;
    }

    public void setLcStsdes(String lcStsdes) {
        this.lcStsdes = lcStsdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pk0Ym400contdetResponsePoutContdet)) return false;
        final ProcYm4000pk0Ym400contdetResponsePoutContdet procYm4000pk0ym400contdetResponsePoutContdet = (ProcYm4000pk0Ym400contdetResponsePoutContdet) o;
        return Objects.equals(getContractid(), procYm4000pk0ym400contdetResponsePoutContdet.getContractid()) &&
                Objects.equals(getYnitemno(), procYm4000pk0ym400contdetResponsePoutContdet.getYnitemno()) &&
                Objects.equals(getContainerSeq(), procYm4000pk0ym400contdetResponsePoutContdet.getContainerSeq()) &&
                Objects.equals(getExprecdat(), procYm4000pk0ym400contdetResponsePoutContdet.getExprecdat()) &&
                Objects.equals(getPlnkgs(), procYm4000pk0ym400contdetResponsePoutContdet.getPlnkgs()) &&
                Objects.equals(getShpmod(), procYm4000pk0ym400contdetResponsePoutContdet.getShpmod()) &&
                Objects.equals(getWshipmod(), procYm4000pk0ym400contdetResponsePoutContdet.getWshipmod()) &&
                Objects.equals(getContainerqty(), procYm4000pk0ym400contdetResponsePoutContdet.getContainerqty()) &&
                Objects.equals(getContainerType(), procYm4000pk0ym400contdetResponsePoutContdet.getContainerType()) &&
                Objects.equals(getWcontainerType(), procYm4000pk0ym400contdetResponsePoutContdet.getWcontainerType()) &&
                Objects.equals(getShipline(), procYm4000pk0ym400contdetResponsePoutContdet.getShipline()) &&
                Objects.equals(getContainernum(), procYm4000pk0ym400contdetResponsePoutContdet.getContainernum()) &&
                Objects.equals(getLadingbill(), procYm4000pk0ym400contdetResponsePoutContdet.getLadingbill()) &&
                Objects.equals(getVessname(), procYm4000pk0ym400contdetResponsePoutContdet.getVessname()) &&
                Objects.equals(getVoyage(), procYm4000pk0ym400contdetResponsePoutContdet.getVoyage()) &&
                Objects.equals(getExpdeparturedat(), procYm4000pk0ym400contdetResponsePoutContdet.getExpdeparturedat()) &&
                Objects.equals(getExparrivaldat(), procYm4000pk0ym400contdetResponsePoutContdet.getExparrivaldat()) &&
                Objects.equals(getActarrivaldat(), procYm4000pk0ym400contdetResponsePoutContdet.getActarrivaldat()) &&
                Objects.equals(getQtyrec(), procYm4000pk0ym400contdetResponsePoutContdet.getQtyrec()) &&
                Objects.equals(getManudat(), procYm4000pk0ym400contdetResponsePoutContdet.getManudat()) &&
                Objects.equals(getRlotnum(), procYm4000pk0ym400contdetResponsePoutContdet.getRlotnum()) &&
                Objects.equals(getFlrlotnum(), procYm4000pk0ym400contdetResponsePoutContdet.getFlrlotnum()) &&
                Objects.equals(getFlryrnori(), procYm4000pk0ym400contdetResponsePoutContdet.getFlryrnori()) &&
                Objects.equals(getYrncod(), procYm4000pk0ym400contdetResponsePoutContdet.getYrncod()) &&
                Objects.equals(getWflrlotnum(), procYm4000pk0ym400contdetResponsePoutContdet.getWflrlotnum()) &&
                Objects.equals(getWflryrnori(), procYm4000pk0ym400contdetResponsePoutContdet.getWflryrnori()) &&
                Objects.equals(getWdaterec(), procYm4000pk0ym400contdetResponsePoutContdet.getWdaterec()) &&
                Objects.equals(getWtotal(), procYm4000pk0ym400contdetResponsePoutContdet.getWtotal()) &&
                Objects.equals(getWtotqtyrcv(), procYm4000pk0ym400contdetResponsePoutContdet.getWtotqtyrcv()) &&
                Objects.equals(getLcDate(), procYm4000pk0ym400contdetResponsePoutContdet.getLcDate()) &&
                Objects.equals(getLcNo(), procYm4000pk0ym400contdetResponsePoutContdet.getLcNo()) &&
                Objects.equals(getPaidSts(), procYm4000pk0ym400contdetResponsePoutContdet.getPaidSts()) &&
                Objects.equals(getLcStsdes(), procYm4000pk0ym400contdetResponsePoutContdet.getLcStsdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContractid(),
                getYnitemno(),
                getContainerSeq(),
                getExprecdat(),
                getPlnkgs(),
                getShpmod(),
                getWshipmod(),
                getContainerqty(),
                getContainerType(),
                getWcontainerType(),
                getShipline(),
                getContainernum(),
                getLadingbill(),
                getVessname(),
                getVoyage(),
                getExpdeparturedat(),
                getExparrivaldat(),
                getActarrivaldat(),
                getQtyrec(),
                getManudat(),
                getRlotnum(),
                getFlrlotnum(),
                getFlryrnori(),
                getYrncod(),
                getWflrlotnum(),
                getWflryrnori(),
                getWdaterec(),
                getWtotal(),
                getWtotqtyrcv(),
                getLcDate(),
                getLcNo(),
                getPaidSts(),
                getLcStsdes());
    }
}