/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm3600pkoYm345palletDetailsResponse implements Serializable {


    @ColumnAlias("pOutYM345PalletDetails")
    private List<ProcYm3600pkoYm345palletDetailsResponsePoutYm345palletDetails> poutYm345palletDetails;

    public List<ProcYm3600pkoYm345palletDetailsResponsePoutYm345palletDetails> getPoutYm345palletDetails() {
        return this.poutYm345palletDetails;
    }

    public void setPoutYm345palletDetails(List<ProcYm3600pkoYm345palletDetailsResponsePoutYm345palletDetails> poutYm345palletDetails) {
        this.poutYm345palletDetails = poutYm345palletDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm3600pkoYm345palletDetailsResponse)) return false;
        final ProcYm3600pkoYm345palletDetailsResponse procYm3600pkoYm345palletDetailsResponse = (ProcYm3600pkoYm345palletDetailsResponse) o;
        return Objects.equals(getPoutYm345palletDetails(), procYm3600pkoYm345palletDetailsResponse.getPoutYm345palletDetails());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYm345palletDetails());
    }
}