/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm40000pk0Ym400plistResponsePoutPlist implements Serializable {


    @ColumnAlias("CONTRACTID")
    private String contractid;

    @ColumnAlias("YNITEMNO")
    private Byte ynitemno;

    @ColumnAlias("CONTAINER_SEQ")
    private Short containerSeq;

    @ColumnAlias("PALLET_SEQ")
    private Short palletSeq;

    @ColumnAlias("PALLETCAT")
    private String palletcat;

    @ColumnAlias("W_PALLETCAT_DES")
    private String wpalletcatDes;

    @ColumnAlias("NUMPAL")
    private Short numpal;

    @ColumnAlias("CONWGT")
    private Float conwgt;

    @ColumnAlias("CONCAR")
    private Short concar;

    @ColumnAlias("CARPALL")
    private Short carpall;

    @ColumnAlias("NUMCONES")
    private Integer numcones;

    @ColumnAlias("QTYREC")
    private Double qtyrec;

    @ColumnAlias("MODID")
    private String modid;

    @ColumnAlias("MODDAT")
    private LocalDateTime moddat;

    @ColumnAlias("PALWGT")
    private Double palwgt;

    @ColumnAlias("TOTPALACK")
    private Short totpalack;

    @ColumnAlias("W_KGSACK")
    private BigInteger wkgsack;

    public String getContractid() {
        return this.contractid;
    }

    public void setContractid(String contractid) {
        this.contractid = contractid;
    }

    public Byte getYnitemno() {
        return this.ynitemno;
    }

    public void setYnitemno(Byte ynitemno) {
        this.ynitemno = ynitemno;
    }

    public Short getContainerSeq() {
        return this.containerSeq;
    }

    public void setContainerSeq(Short containerSeq) {
        this.containerSeq = containerSeq;
    }

    public Short getPalletSeq() {
        return this.palletSeq;
    }

    public void setPalletSeq(Short palletSeq) {
        this.palletSeq = palletSeq;
    }

    public String getPalletcat() {
        return this.palletcat;
    }

    public void setPalletcat(String palletcat) {
        this.palletcat = palletcat;
    }

    public String getWpalletcatDes() {
        return this.wpalletcatDes;
    }

    public void setWpalletcatDes(String wpalletcatDes) {
        this.wpalletcatDes = wpalletcatDes;
    }

    public Short getNumpal() {
        return this.numpal;
    }

    public void setNumpal(Short numpal) {
        this.numpal = numpal;
    }

    public Float getConwgt() {
        return this.conwgt;
    }

    public void setConwgt(Float conwgt) {
        this.conwgt = conwgt;
    }

    public Short getConcar() {
        return this.concar;
    }

    public void setConcar(Short concar) {
        this.concar = concar;
    }

    public Short getCarpall() {
        return this.carpall;
    }

    public void setCarpall(Short carpall) {
        this.carpall = carpall;
    }

    public Integer getNumcones() {
        return this.numcones;
    }

    public void setNumcones(Integer numcones) {
        this.numcones = numcones;
    }

    public Double getQtyrec() {
        return this.qtyrec;
    }

    public void setQtyrec(Double qtyrec) {
        this.qtyrec = qtyrec;
    }

    public String getModid() {
        return this.modid;
    }

    public void setModid(String modid) {
        this.modid = modid;
    }

    public LocalDateTime getModdat() {
        return this.moddat;
    }

    public void setModdat(LocalDateTime moddat) {
        this.moddat = moddat;
    }

    public Double getPalwgt() {
        return this.palwgt;
    }

    public void setPalwgt(Double palwgt) {
        this.palwgt = palwgt;
    }

    public Short getTotpalack() {
        return this.totpalack;
    }

    public void setTotpalack(Short totpalack) {
        this.totpalack = totpalack;
    }

    public BigInteger getWkgsack() {
        return this.wkgsack;
    }

    public void setWkgsack(BigInteger wkgsack) {
        this.wkgsack = wkgsack;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm40000pk0Ym400plistResponsePoutPlist)) return false;
        final ProcYm40000pk0Ym400plistResponsePoutPlist procYm40000pk0ym400plistResponsePoutPlist = (ProcYm40000pk0Ym400plistResponsePoutPlist) o;
        return Objects.equals(getContractid(), procYm40000pk0ym400plistResponsePoutPlist.getContractid()) &&
                Objects.equals(getYnitemno(), procYm40000pk0ym400plistResponsePoutPlist.getYnitemno()) &&
                Objects.equals(getContainerSeq(), procYm40000pk0ym400plistResponsePoutPlist.getContainerSeq()) &&
                Objects.equals(getPalletSeq(), procYm40000pk0ym400plistResponsePoutPlist.getPalletSeq()) &&
                Objects.equals(getPalletcat(), procYm40000pk0ym400plistResponsePoutPlist.getPalletcat()) &&
                Objects.equals(getWpalletcatDes(), procYm40000pk0ym400plistResponsePoutPlist.getWpalletcatDes()) &&
                Objects.equals(getNumpal(), procYm40000pk0ym400plistResponsePoutPlist.getNumpal()) &&
                Objects.equals(getConwgt(), procYm40000pk0ym400plistResponsePoutPlist.getConwgt()) &&
                Objects.equals(getConcar(), procYm40000pk0ym400plistResponsePoutPlist.getConcar()) &&
                Objects.equals(getCarpall(), procYm40000pk0ym400plistResponsePoutPlist.getCarpall()) &&
                Objects.equals(getNumcones(), procYm40000pk0ym400plistResponsePoutPlist.getNumcones()) &&
                Objects.equals(getQtyrec(), procYm40000pk0ym400plistResponsePoutPlist.getQtyrec()) &&
                Objects.equals(getModid(), procYm40000pk0ym400plistResponsePoutPlist.getModid()) &&
                Objects.equals(getModdat(), procYm40000pk0ym400plistResponsePoutPlist.getModdat()) &&
                Objects.equals(getPalwgt(), procYm40000pk0ym400plistResponsePoutPlist.getPalwgt()) &&
                Objects.equals(getTotpalack(), procYm40000pk0ym400plistResponsePoutPlist.getTotpalack()) &&
                Objects.equals(getWkgsack(), procYm40000pk0ym400plistResponsePoutPlist.getWkgsack());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContractid(),
                getYnitemno(),
                getContainerSeq(),
                getPalletSeq(),
                getPalletcat(),
                getWpalletcatDes(),
                getNumpal(),
                getConwgt(),
                getConcar(),
                getCarpall(),
                getNumcones(),
                getQtyrec(),
                getModid(),
                getModdat(),
                getPalwgt(),
                getTotpalack(),
                getWkgsack());
    }
}