/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym100cpstypResponsePoutYm100cpstyp implements Serializable {


    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("SUBCPSTYP")
    private String subcpstyp;

    @ColumnAlias("YRNFRAC")
    private Short yrnfrac;

    @ColumnAlias("SUBCPSSEQ")
    private Byte subcpsseq;

    @ColumnAlias("W_SUBCPSTYP_DES")
    private String wsubcpstypDes;

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getSubcpstyp() {
        return this.subcpstyp;
    }

    public void setSubcpstyp(String subcpstyp) {
        this.subcpstyp = subcpstyp;
    }

    public Short getYrnfrac() {
        return this.yrnfrac;
    }

    public void setYrnfrac(Short yrnfrac) {
        this.yrnfrac = yrnfrac;
    }

    public Byte getSubcpsseq() {
        return this.subcpsseq;
    }

    public void setSubcpsseq(Byte subcpsseq) {
        this.subcpsseq = subcpsseq;
    }

    public String getWsubcpstypDes() {
        return this.wsubcpstypDes;
    }

    public void setWsubcpstypDes(String wsubcpstypDes) {
        this.wsubcpstypDes = wsubcpstypDes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym100cpstypResponsePoutYm100cpstyp)) return false;
        final ProcYm1311pk0Ym100cpstypResponsePoutYm100cpstyp procYm1311pk0ym100cpstypResponsePoutYm100cpstyp = (ProcYm1311pk0Ym100cpstypResponsePoutYm100cpstyp) o;
        return Objects.equals(getYrncod(), procYm1311pk0ym100cpstypResponsePoutYm100cpstyp.getYrncod()) &&
                Objects.equals(getSubcpstyp(), procYm1311pk0ym100cpstypResponsePoutYm100cpstyp.getSubcpstyp()) &&
                Objects.equals(getYrnfrac(), procYm1311pk0ym100cpstypResponsePoutYm100cpstyp.getYrnfrac()) &&
                Objects.equals(getSubcpsseq(), procYm1311pk0ym100cpstypResponsePoutYm100cpstyp.getSubcpsseq()) &&
                Objects.equals(getWsubcpstypDes(), procYm1311pk0ym100cpstypResponsePoutYm100cpstyp.getWsubcpstypDes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrncod(),
                getSubcpstyp(),
                getYrnfrac(),
                getSubcpsseq(),
                getWsubcpstypDes());
    }
}