/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym360queryDetailsResponse implements Serializable {


    @ColumnAlias("poutQueryDetails")
    private List<ProcYm1311pk0Ym360queryDetailsResponsePoutQueryDetails> poutQueryDetails;

    public List<ProcYm1311pk0Ym360queryDetailsResponsePoutQueryDetails> getPoutQueryDetails() {
        return this.poutQueryDetails;
    }

    public void setPoutQueryDetails(List<ProcYm1311pk0Ym360queryDetailsResponsePoutQueryDetails> poutQueryDetails) {
        this.poutQueryDetails = poutQueryDetails;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym360queryDetailsResponse)) return false;
        final ProcYm1311pk0Ym360queryDetailsResponse procYm1311pk0ym360queryDetailsResponse = (ProcYm1311pk0Ym360queryDetailsResponse) o;
        return Objects.equals(getPoutQueryDetails(), procYm1311pk0ym360queryDetailsResponse.getPoutQueryDetails());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutQueryDetails());
    }
}