/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1000pkoYm122masterResponsePoutYm122master implements Serializable {


    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("NFCNTDES")
    private String nfcntdes;

    @ColumnAlias("YRNLOT")
    private String yrnlot;

    @ColumnAlias("NFYRNCPS")
    private String nfyrncps;

    @ColumnAlias("NYRNCLR")
    private String nyrnclr;

    @ColumnAlias("NYRNCDES")
    private String nyrncdes;

    @ColumnAlias("QTYAVAIL")
    private Double qtyavail;

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public String getNfcntdes() {
        return this.nfcntdes;
    }

    public void setNfcntdes(String nfcntdes) {
        this.nfcntdes = nfcntdes;
    }

    public String getYrnlot() {
        return this.yrnlot;
    }

    public void setYrnlot(String yrnlot) {
        this.yrnlot = yrnlot;
    }

    public String getNfyrncps() {
        return this.nfyrncps;
    }

    public void setNfyrncps(String nfyrncps) {
        this.nfyrncps = nfyrncps;
    }

    public String getNyrnclr() {
        return this.nyrnclr;
    }

    public void setNyrnclr(String nyrnclr) {
        this.nyrnclr = nyrnclr;
    }

    public String getNyrncdes() {
        return this.nyrncdes;
    }

    public void setNyrncdes(String nyrncdes) {
        this.nyrncdes = nyrncdes;
    }

    public Double getQtyavail() {
        return this.qtyavail;
    }

    public void setQtyavail(Double qtyavail) {
        this.qtyavail = qtyavail;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1000pkoYm122masterResponsePoutYm122master)) return false;
        final ProcYm1000pkoYm122masterResponsePoutYm122master procYm1000pkoYm122masterResponsePoutYm122master = (ProcYm1000pkoYm122masterResponsePoutYm122master) o;
        return Objects.equals(getYrncod(), procYm1000pkoYm122masterResponsePoutYm122master.getYrncod()) &&
                Objects.equals(getYrnori(), procYm1000pkoYm122masterResponsePoutYm122master.getYrnori()) &&
                Objects.equals(getNfcntdes(), procYm1000pkoYm122masterResponsePoutYm122master.getNfcntdes()) &&
                Objects.equals(getYrnlot(), procYm1000pkoYm122masterResponsePoutYm122master.getYrnlot()) &&
                Objects.equals(getNfyrncps(), procYm1000pkoYm122masterResponsePoutYm122master.getNfyrncps()) &&
                Objects.equals(getNyrnclr(), procYm1000pkoYm122masterResponsePoutYm122master.getNyrnclr()) &&
                Objects.equals(getNyrncdes(), procYm1000pkoYm122masterResponsePoutYm122master.getNyrncdes()) &&
                Objects.equals(getQtyavail(), procYm1000pkoYm122masterResponsePoutYm122master.getQtyavail());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrncod(),
                getYrnori(),
                getNfcntdes(),
                getYrnlot(),
                getNfyrncps(),
                getNyrnclr(),
                getNyrncdes(),
                getQtyavail());
    }
}