/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pk0Ym405masterResponsePoutMaster implements Serializable {


    @ColumnAlias("RLOTNUM")
    private String rlotnum;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("CONTAINERNUM")
    private String containernum;

    @ColumnAlias("VESSNAME")
    private String vessname;

    @ColumnAlias("VOYAGE")
    private String voyage;

    @ColumnAlias("YNITEMNO")
    private Byte ynitemno;

    @ColumnAlias("CONTAINER_SEQ")
    private Short containerSeq;

    @ColumnAlias("CONTRACTID")
    private String contractid;

    @ColumnAlias("YRNCNT")
    private String yrncnt;

    @ColumnAlias("YRNCPS")
    private String yrncps;

    @ColumnAlias("YRNCLR")
    private String yrnclr;

    @ColumnAlias("YRNCDES")
    private String yrncdes;

    @ColumnAlias("CONTRACTNO")
    private String contractno;

    @ColumnAlias("RYRNORI")
    private String ryrnori;

    public String getRlotnum() {
        return this.rlotnum;
    }

    public void setRlotnum(String rlotnum) {
        this.rlotnum = rlotnum;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getContainernum() {
        return this.containernum;
    }

    public void setContainernum(String containernum) {
        this.containernum = containernum;
    }

    public String getVessname() {
        return this.vessname;
    }

    public void setVessname(String vessname) {
        this.vessname = vessname;
    }

    public String getVoyage() {
        return this.voyage;
    }

    public void setVoyage(String voyage) {
        this.voyage = voyage;
    }

    public Byte getYnitemno() {
        return this.ynitemno;
    }

    public void setYnitemno(Byte ynitemno) {
        this.ynitemno = ynitemno;
    }

    public Short getContainerSeq() {
        return this.containerSeq;
    }

    public void setContainerSeq(Short containerSeq) {
        this.containerSeq = containerSeq;
    }

    public String getContractid() {
        return this.contractid;
    }

    public void setContractid(String contractid) {
        this.contractid = contractid;
    }

    public String getYrncnt() {
        return this.yrncnt;
    }

    public void setYrncnt(String yrncnt) {
        this.yrncnt = yrncnt;
    }

    public String getYrncps() {
        return this.yrncps;
    }

    public void setYrncps(String yrncps) {
        this.yrncps = yrncps;
    }

    public String getYrnclr() {
        return this.yrnclr;
    }

    public void setYrnclr(String yrnclr) {
        this.yrnclr = yrnclr;
    }

    public String getYrncdes() {
        return this.yrncdes;
    }

    public void setYrncdes(String yrncdes) {
        this.yrncdes = yrncdes;
    }

    public String getContractno() {
        return this.contractno;
    }

    public void setContractno(String contractno) {
        this.contractno = contractno;
    }

    public String getRyrnori() {
        return this.ryrnori;
    }

    public void setRyrnori(String ryrnori) {
        this.ryrnori = ryrnori;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pk0Ym405masterResponsePoutMaster)) return false;
        final ProcYm4000pk0Ym405masterResponsePoutMaster procYm4000pk0ym405masterResponsePoutMaster = (ProcYm4000pk0Ym405masterResponsePoutMaster) o;
        return Objects.equals(getRlotnum(), procYm4000pk0ym405masterResponsePoutMaster.getRlotnum()) &&
                Objects.equals(getYrncod(), procYm4000pk0ym405masterResponsePoutMaster.getYrncod()) &&
                Objects.equals(getContainernum(), procYm4000pk0ym405masterResponsePoutMaster.getContainernum()) &&
                Objects.equals(getVessname(), procYm4000pk0ym405masterResponsePoutMaster.getVessname()) &&
                Objects.equals(getVoyage(), procYm4000pk0ym405masterResponsePoutMaster.getVoyage()) &&
                Objects.equals(getYnitemno(), procYm4000pk0ym405masterResponsePoutMaster.getYnitemno()) &&
                Objects.equals(getContainerSeq(), procYm4000pk0ym405masterResponsePoutMaster.getContainerSeq()) &&
                Objects.equals(getContractid(), procYm4000pk0ym405masterResponsePoutMaster.getContractid()) &&
                Objects.equals(getYrncnt(), procYm4000pk0ym405masterResponsePoutMaster.getYrncnt()) &&
                Objects.equals(getYrncps(), procYm4000pk0ym405masterResponsePoutMaster.getYrncps()) &&
                Objects.equals(getYrnclr(), procYm4000pk0ym405masterResponsePoutMaster.getYrnclr()) &&
                Objects.equals(getYrncdes(), procYm4000pk0ym405masterResponsePoutMaster.getYrncdes()) &&
                Objects.equals(getContractno(), procYm4000pk0ym405masterResponsePoutMaster.getContractno()) &&
                Objects.equals(getRyrnori(), procYm4000pk0ym405masterResponsePoutMaster.getRyrnori());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRlotnum(),
                getYrncod(),
                getContainernum(),
                getVessname(),
                getVoyage(),
                getYnitemno(),
                getContainerSeq(),
                getContractid(),
                getYrncnt(),
                getYrncps(),
                getYrnclr(),
                getYrncdes(),
                getContractno(),
                getRyrnori());
    }
}