/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1000pkoYm285pallettypeResponse implements Serializable {


    @ColumnAlias("poutPALLETTYPE")
    private List<ProcYm1000pkoYm285pallettypeResponsePoutPallettype> poutPallettype;

    public List<ProcYm1000pkoYm285pallettypeResponsePoutPallettype> getPoutPallettype() {
        return this.poutPallettype;
    }

    public void setPoutPallettype(List<ProcYm1000pkoYm285pallettypeResponsePoutPallettype> poutPallettype) {
        this.poutPallettype = poutPallettype;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1000pkoYm285pallettypeResponse)) return false;
        final ProcYm1000pkoYm285pallettypeResponse procYm1000pkoYm285pallettypeResponse = (ProcYm1000pkoYm285pallettypeResponse) o;
        return Objects.equals(getPoutPallettype(), procYm1000pkoYm285pallettypeResponse.getPoutPallettype());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutPallettype());
    }
}