/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym284yarnPalletStickerResponse implements Serializable {


    @ColumnAlias("poutYarnPalletSticker")
    private List<ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker> poutYarnPalletSticker;

    public List<ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker> getPoutYarnPalletSticker() {
        return this.poutYarnPalletSticker;
    }

    public void setPoutYarnPalletSticker(List<ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker> poutYarnPalletSticker) {
        this.poutYarnPalletSticker = poutYarnPalletSticker;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym284yarnPalletStickerResponse)) return false;
        final ProcYm1311pk0Ym284yarnPalletStickerResponse procYm1311pk0ym284yarnPalletStickerResponse = (ProcYm1311pk0Ym284yarnPalletStickerResponse) o;
        return Objects.equals(getPoutYarnPalletSticker(), procYm1311pk0ym284yarnPalletStickerResponse.getPoutYarnPalletSticker());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYarnPalletSticker());
    }
}