/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym650wmatusercodeResponsePoutWmatusercode implements Serializable {


    @ColumnAlias("MATERIALCODE")
    private String materialcode;

    @ColumnAlias("MATUSERCODE")
    private String matusercode;

    @ColumnAlias("MATORI")
    private String matori;

    @ColumnAlias("MATCPS")
    private String matcps;

    @ColumnAlias("MATCLR")
    private String matclr;

    @ColumnAlias("MATCLRDES")
    private String matclrdes;

    @ColumnAlias("MATLENGTH")
    private Float matlength;

    @ColumnAlias("MATLENGTH_UOM")
    private String matlengthUom;

    @ColumnAlias("MATCTYCOD")
    private String matctycod;

    @ColumnAlias("MATCLRREF")
    private String matclrref;

    @ColumnAlias("MATDIAMETER")
    private Float matdiameter;

    @ColumnAlias("MATDIAMETER_UOM")
    private String matdiameterUom;

    @ColumnAlias("WGTUOM")
    private String wgtuom;

    public String getMaterialcode() {
        return this.materialcode;
    }

    public void setMaterialcode(String materialcode) {
        this.materialcode = materialcode;
    }

    public String getMatusercode() {
        return this.matusercode;
    }

    public void setMatusercode(String matusercode) {
        this.matusercode = matusercode;
    }

    public String getMatori() {
        return this.matori;
    }

    public void setMatori(String matori) {
        this.matori = matori;
    }

    public String getMatcps() {
        return this.matcps;
    }

    public void setMatcps(String matcps) {
        this.matcps = matcps;
    }

    public String getMatclr() {
        return this.matclr;
    }

    public void setMatclr(String matclr) {
        this.matclr = matclr;
    }

    public String getMatclrdes() {
        return this.matclrdes;
    }

    public void setMatclrdes(String matclrdes) {
        this.matclrdes = matclrdes;
    }

    public Float getMatlength() {
        return this.matlength;
    }

    public void setMatlength(Float matlength) {
        this.matlength = matlength;
    }

    public String getMatlengthUom() {
        return this.matlengthUom;
    }

    public void setMatlengthUom(String matlengthUom) {
        this.matlengthUom = matlengthUom;
    }

    public String getMatctycod() {
        return this.matctycod;
    }

    public void setMatctycod(String matctycod) {
        this.matctycod = matctycod;
    }

    public String getMatclrref() {
        return this.matclrref;
    }

    public void setMatclrref(String matclrref) {
        this.matclrref = matclrref;
    }

    public Float getMatdiameter() {
        return this.matdiameter;
    }

    public void setMatdiameter(Float matdiameter) {
        this.matdiameter = matdiameter;
    }

    public String getMatdiameterUom() {
        return this.matdiameterUom;
    }

    public void setMatdiameterUom(String matdiameterUom) {
        this.matdiameterUom = matdiameterUom;
    }

    public String getWgtuom() {
        return this.wgtuom;
    }

    public void setWgtuom(String wgtuom) {
        this.wgtuom = wgtuom;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym650wmatusercodeResponsePoutWmatusercode)) return false;
        final ProcYm1311pk0Ym650wmatusercodeResponsePoutWmatusercode procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode = (ProcYm1311pk0Ym650wmatusercodeResponsePoutWmatusercode) o;
        return Objects.equals(getMaterialcode(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMaterialcode()) &&
                Objects.equals(getMatusercode(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatusercode()) &&
                Objects.equals(getMatori(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatori()) &&
                Objects.equals(getMatcps(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatcps()) &&
                Objects.equals(getMatclr(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatclr()) &&
                Objects.equals(getMatclrdes(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatclrdes()) &&
                Objects.equals(getMatlength(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatlength()) &&
                Objects.equals(getMatlengthUom(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatlengthUom()) &&
                Objects.equals(getMatctycod(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatctycod()) &&
                Objects.equals(getMatclrref(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatclrref()) &&
                Objects.equals(getMatdiameter(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatdiameter()) &&
                Objects.equals(getMatdiameterUom(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getMatdiameterUom()) &&
                Objects.equals(getWgtuom(), procYm1311pk0ym650wmatusercodeResponsePoutWmatusercode.getWgtuom());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getMaterialcode(),
                getMatusercode(),
                getMatori(),
                getMatcps(),
                getMatclr(),
                getMatclrdes(),
                getMatlength(),
                getMatlengthUom(),
                getMatctycod(),
                getMatclrref(),
                getMatdiameter(),
                getMatdiameterUom(),
                getWgtuom());
    }
}