/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pk0Ym400rgfibreTypResponsePoutRgfibreTyp implements Serializable {


    @ColumnAlias("FIBRETYP")
    private String fibretyp;

    @ColumnAlias("FIBREDES")
    private String fibredes;

    public String getFibretyp() {
        return this.fibretyp;
    }

    public void setFibretyp(String fibretyp) {
        this.fibretyp = fibretyp;
    }

    public String getFibredes() {
        return this.fibredes;
    }

    public void setFibredes(String fibredes) {
        this.fibredes = fibredes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pk0Ym400rgfibreTypResponsePoutRgfibreTyp)) return false;
        final ProcYm4000pk0Ym400rgfibreTypResponsePoutRgfibreTyp procYm4000pk0ym400rgfibreTypResponsePoutRgfibreTyp = (ProcYm4000pk0Ym400rgfibreTypResponsePoutRgfibreTyp) o;
        return Objects.equals(getFibretyp(), procYm4000pk0ym400rgfibreTypResponsePoutRgfibreTyp.getFibretyp()) &&
                Objects.equals(getFibredes(), procYm4000pk0ym400rgfibreTypResponsePoutRgfibreTyp.getFibredes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFibretyp(),
                getFibredes());
    }
}