/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm3600pk0Ym360detailResponsePoutYm360detail implements Serializable {


    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("YRNID")
    private Short yrnid;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("FABIND")
    private String fabind;

    @ColumnAlias("FABTYP")
    private String fabtyp;

    @ColumnAlias("YRNSEQ")
    private Byte yrnseq;

    @ColumnAlias("W_YRNCOD")
    private String wyrncod;

    @ColumnAlias("QTYALC")
    private Double qtyalc;

    @ColumnAlias("QTYREQN")
    private Double qtyreqn;

    @ColumnAlias("QTYDEL")
    private Double qtydel;

    @ColumnAlias("QTYRET")
    private Double qtyret;

    @ColumnAlias("W_NETUSED")
    private BigDecimal wnetused;

    @ColumnAlias("KGSKNIT")
    private BigDecimal kgsknit;

    @ColumnAlias("W_KNTSTS")
    private String wkntsts;

    @ColumnAlias("TOTQTYALC")
    private BigDecimal totqtyalc;

    @ColumnAlias("TOTQTYREQ")
    private BigDecimal totqtyreq;

    @ColumnAlias("TOTQTYDEL")
    private BigDecimal totqtydel;

    @ColumnAlias("W_TQTYRET")
    private BigDecimal wtqtyret;

    @ColumnAlias("W_TNETUSED")
    private BigDecimal wtnetused;

    @ColumnAlias("TOTKGSKNIT")
    private BigDecimal totkgsknit;

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Short getYrnid() {
        return this.yrnid;
    }

    public void setYrnid(Short yrnid) {
        this.yrnid = yrnid;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabind() {
        return this.fabind;
    }

    public void setFabind(String fabind) {
        this.fabind = fabind;
    }

    public String getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(String fabtyp) {
        this.fabtyp = fabtyp;
    }

    public Byte getYrnseq() {
        return this.yrnseq;
    }

    public void setYrnseq(Byte yrnseq) {
        this.yrnseq = yrnseq;
    }

    public String getWyrncod() {
        return this.wyrncod;
    }

    public void setWyrncod(String wyrncod) {
        this.wyrncod = wyrncod;
    }

    public Double getQtyalc() {
        return this.qtyalc;
    }

    public void setQtyalc(Double qtyalc) {
        this.qtyalc = qtyalc;
    }

    public Double getQtyreqn() {
        return this.qtyreqn;
    }

    public void setQtyreqn(Double qtyreqn) {
        this.qtyreqn = qtyreqn;
    }

    public Double getQtydel() {
        return this.qtydel;
    }

    public void setQtydel(Double qtydel) {
        this.qtydel = qtydel;
    }

    public Double getQtyret() {
        return this.qtyret;
    }

    public void setQtyret(Double qtyret) {
        this.qtyret = qtyret;
    }

    public BigDecimal getWnetused() {
        return this.wnetused;
    }

    public void setWnetused(BigDecimal wnetused) {
        this.wnetused = wnetused;
    }

    public BigDecimal getKgsknit() {
        return this.kgsknit;
    }

    public void setKgsknit(BigDecimal kgsknit) {
        this.kgsknit = kgsknit;
    }

    public String getWkntsts() {
        return this.wkntsts;
    }

    public void setWkntsts(String wkntsts) {
        this.wkntsts = wkntsts;
    }

    public BigDecimal getTotqtyalc() {
        return this.totqtyalc;
    }

    public void setTotqtyalc(BigDecimal totqtyalc) {
        this.totqtyalc = totqtyalc;
    }

    public BigDecimal getTotqtyreq() {
        return this.totqtyreq;
    }

    public void setTotqtyreq(BigDecimal totqtyreq) {
        this.totqtyreq = totqtyreq;
    }

    public BigDecimal getTotqtydel() {
        return this.totqtydel;
    }

    public void setTotqtydel(BigDecimal totqtydel) {
        this.totqtydel = totqtydel;
    }

    public BigDecimal getWtqtyret() {
        return this.wtqtyret;
    }

    public void setWtqtyret(BigDecimal wtqtyret) {
        this.wtqtyret = wtqtyret;
    }

    public BigDecimal getWtnetused() {
        return this.wtnetused;
    }

    public void setWtnetused(BigDecimal wtnetused) {
        this.wtnetused = wtnetused;
    }

    public BigDecimal getTotkgsknit() {
        return this.totkgsknit;
    }

    public void setTotkgsknit(BigDecimal totkgsknit) {
        this.totkgsknit = totkgsknit;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm3600pk0Ym360detailResponsePoutYm360detail)) return false;
        final ProcYm3600pk0Ym360detailResponsePoutYm360detail procYm3600pk0ym360detailResponsePoutYm360detail = (ProcYm3600pk0Ym360detailResponsePoutYm360detail) o;
        return Objects.equals(getYrnmixcode(), procYm3600pk0ym360detailResponsePoutYm360detail.getYrnmixcode()) &&
                Objects.equals(getOrdnum(), procYm3600pk0ym360detailResponsePoutYm360detail.getOrdnum()) &&
                Objects.equals(getYrnid(), procYm3600pk0ym360detailResponsePoutYm360detail.getYrnid()) &&
                Objects.equals(getFabseq(), procYm3600pk0ym360detailResponsePoutYm360detail.getFabseq()) &&
                Objects.equals(getFabind(), procYm3600pk0ym360detailResponsePoutYm360detail.getFabind()) &&
                Objects.equals(getFabtyp(), procYm3600pk0ym360detailResponsePoutYm360detail.getFabtyp()) &&
                Objects.equals(getYrnseq(), procYm3600pk0ym360detailResponsePoutYm360detail.getYrnseq()) &&
                Objects.equals(getWyrncod(), procYm3600pk0ym360detailResponsePoutYm360detail.getWyrncod()) &&
                Objects.equals(getQtyalc(), procYm3600pk0ym360detailResponsePoutYm360detail.getQtyalc()) &&
                Objects.equals(getQtyreqn(), procYm3600pk0ym360detailResponsePoutYm360detail.getQtyreqn()) &&
                Objects.equals(getQtydel(), procYm3600pk0ym360detailResponsePoutYm360detail.getQtydel()) &&
                Objects.equals(getQtyret(), procYm3600pk0ym360detailResponsePoutYm360detail.getQtyret()) &&
                Objects.equals(getWnetused(), procYm3600pk0ym360detailResponsePoutYm360detail.getWnetused()) &&
                Objects.equals(getKgsknit(), procYm3600pk0ym360detailResponsePoutYm360detail.getKgsknit()) &&
                Objects.equals(getWkntsts(), procYm3600pk0ym360detailResponsePoutYm360detail.getWkntsts()) &&
                Objects.equals(getTotqtyalc(), procYm3600pk0ym360detailResponsePoutYm360detail.getTotqtyalc()) &&
                Objects.equals(getTotqtyreq(), procYm3600pk0ym360detailResponsePoutYm360detail.getTotqtyreq()) &&
                Objects.equals(getTotqtydel(), procYm3600pk0ym360detailResponsePoutYm360detail.getTotqtydel()) &&
                Objects.equals(getWtqtyret(), procYm3600pk0ym360detailResponsePoutYm360detail.getWtqtyret()) &&
                Objects.equals(getWtnetused(), procYm3600pk0ym360detailResponsePoutYm360detail.getWtnetused()) &&
                Objects.equals(getTotkgsknit(), procYm3600pk0ym360detailResponsePoutYm360detail.getTotkgsknit());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrnmixcode(),
                getOrdnum(),
                getYrnid(),
                getFabseq(),
                getFabind(),
                getFabtyp(),
                getYrnseq(),
                getWyrncod(),
                getQtyalc(),
                getQtyreqn(),
                getQtydel(),
                getQtyret(),
                getWnetused(),
                getKgsknit(),
                getWkntsts(),
                getTotqtyalc(),
                getTotqtyreq(),
                getTotqtydel(),
                getWtqtyret(),
                getWtnetused(),
                getTotkgsknit());
    }
}