/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym650materialsDesResponsePoutMaterialsDes implements Serializable {


    @ColumnAlias("TRNNUM")
    private String trnnum;

    @ColumnAlias("TRNSEQ")
    private Short trnseq;

    @ColumnAlias("MATERIALCODE")
    private String materialcode;

    @ColumnAlias("BALEQTY")
    private Double baleqty;

    @ColumnAlias("UNITWGT")
    private Double unitwgt;

    @ColumnAlias("TOTALWGT")
    private Double totalwgt;

    @ColumnAlias("WGTUOM")
    private String wgtuom;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("W_TOTAL_BALES")
    private Double wtotalBales;

    @ColumnAlias("W_TOTAL_WEIGHT")
    private Double wtotalWeight;

    @ColumnAlias("W_MATUSERCODE")
    private String wmatusercode;

    @ColumnAlias("UPDMATERIALCODE")
    private String updmaterialcode;

    @ColumnAlias("UPDITEMTYPE")
    private String upditemtype;

    @ColumnAlias("UPDMATUSERCODE")
    private String updmatusercode;

    @ColumnAlias("W_MATCPS")
    private String wmatcps;

    @ColumnAlias("W_MATCLR")
    private String wmatclr;

    @ColumnAlias("W_MATCLRDES")
    private String wmatclrdes;

    @ColumnAlias("W_MATCLRREF")
    private String wmatclrref;

    @ColumnAlias("W_MATORI")
    private String wmatori;

    @ColumnAlias("W_MATCTYCOD")
    private String wmatctycod;

    @ColumnAlias("W_MATLENGTH")
    private Float wmatlength;

    @ColumnAlias("W_MATLENGTH_UOM")
    private String wmatlengthUom;

    @ColumnAlias("W_MATDIAMETER")
    private Float wmatdiameter;

    @ColumnAlias("W_MATDIAMETER_UOM")
    private String wmatdiameterUom;

    public String getTrnnum() {
        return this.trnnum;
    }

    public void setTrnnum(String trnnum) {
        this.trnnum = trnnum;
    }

    public Short getTrnseq() {
        return this.trnseq;
    }

    public void setTrnseq(Short trnseq) {
        this.trnseq = trnseq;
    }

    public String getMaterialcode() {
        return this.materialcode;
    }

    public void setMaterialcode(String materialcode) {
        this.materialcode = materialcode;
    }

    public Double getBaleqty() {
        return this.baleqty;
    }

    public void setBaleqty(Double baleqty) {
        this.baleqty = baleqty;
    }

    public Double getUnitwgt() {
        return this.unitwgt;
    }

    public void setUnitwgt(Double unitwgt) {
        this.unitwgt = unitwgt;
    }

    public Double getTotalwgt() {
        return this.totalwgt;
    }

    public void setTotalwgt(Double totalwgt) {
        this.totalwgt = totalwgt;
    }

    public String getWgtuom() {
        return this.wgtuom;
    }

    public void setWgtuom(String wgtuom) {
        this.wgtuom = wgtuom;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Double getWtotalBales() {
        return this.wtotalBales;
    }

    public void setWtotalBales(Double wtotalBales) {
        this.wtotalBales = wtotalBales;
    }

    public Double getWtotalWeight() {
        return this.wtotalWeight;
    }

    public void setWtotalWeight(Double wtotalWeight) {
        this.wtotalWeight = wtotalWeight;
    }

    public String getWmatusercode() {
        return this.wmatusercode;
    }

    public void setWmatusercode(String wmatusercode) {
        this.wmatusercode = wmatusercode;
    }

    public String getUpdmaterialcode() {
        return this.updmaterialcode;
    }

    public void setUpdmaterialcode(String updmaterialcode) {
        this.updmaterialcode = updmaterialcode;
    }

    public String getUpditemtype() {
        return this.upditemtype;
    }

    public void setUpditemtype(String upditemtype) {
        this.upditemtype = upditemtype;
    }

    public String getUpdmatusercode() {
        return this.updmatusercode;
    }

    public void setUpdmatusercode(String updmatusercode) {
        this.updmatusercode = updmatusercode;
    }

    public String getWmatcps() {
        return this.wmatcps;
    }

    public void setWmatcps(String wmatcps) {
        this.wmatcps = wmatcps;
    }

    public String getWmatclr() {
        return this.wmatclr;
    }

    public void setWmatclr(String wmatclr) {
        this.wmatclr = wmatclr;
    }

    public String getWmatclrdes() {
        return this.wmatclrdes;
    }

    public void setWmatclrdes(String wmatclrdes) {
        this.wmatclrdes = wmatclrdes;
    }

    public String getWmatclrref() {
        return this.wmatclrref;
    }

    public void setWmatclrref(String wmatclrref) {
        this.wmatclrref = wmatclrref;
    }

    public String getWmatori() {
        return this.wmatori;
    }

    public void setWmatori(String wmatori) {
        this.wmatori = wmatori;
    }

    public String getWmatctycod() {
        return this.wmatctycod;
    }

    public void setWmatctycod(String wmatctycod) {
        this.wmatctycod = wmatctycod;
    }

    public Float getWmatlength() {
        return this.wmatlength;
    }

    public void setWmatlength(Float wmatlength) {
        this.wmatlength = wmatlength;
    }

    public String getWmatlengthUom() {
        return this.wmatlengthUom;
    }

    public void setWmatlengthUom(String wmatlengthUom) {
        this.wmatlengthUom = wmatlengthUom;
    }

    public Float getWmatdiameter() {
        return this.wmatdiameter;
    }

    public void setWmatdiameter(Float wmatdiameter) {
        this.wmatdiameter = wmatdiameter;
    }

    public String getWmatdiameterUom() {
        return this.wmatdiameterUom;
    }

    public void setWmatdiameterUom(String wmatdiameterUom) {
        this.wmatdiameterUom = wmatdiameterUom;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym650materialsDesResponsePoutMaterialsDes)) return false;
        final ProcYm1311pk0Ym650materialsDesResponsePoutMaterialsDes procYm1311pk0ym650materialsDesResponsePoutMaterialsDes = (ProcYm1311pk0Ym650materialsDesResponsePoutMaterialsDes) o;
        return Objects.equals(getTrnnum(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getTrnnum()) &&
                Objects.equals(getTrnseq(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getTrnseq()) &&
                Objects.equals(getMaterialcode(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getMaterialcode()) &&
                Objects.equals(getBaleqty(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getBaleqty()) &&
                Objects.equals(getUnitwgt(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getUnitwgt()) &&
                Objects.equals(getTotalwgt(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getTotalwgt()) &&
                Objects.equals(getWgtuom(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWgtuom()) &&
                Objects.equals(getRemarks(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getRemarks()) &&
                Objects.equals(getWtotalBales(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWtotalBales()) &&
                Objects.equals(getWtotalWeight(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWtotalWeight()) &&
                Objects.equals(getWmatusercode(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatusercode()) &&
                Objects.equals(getUpdmaterialcode(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getUpdmaterialcode()) &&
                Objects.equals(getUpditemtype(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getUpditemtype()) &&
                Objects.equals(getUpdmatusercode(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getUpdmatusercode()) &&
                Objects.equals(getWmatcps(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatcps()) &&
                Objects.equals(getWmatclr(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatclr()) &&
                Objects.equals(getWmatclrdes(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatclrdes()) &&
                Objects.equals(getWmatclrref(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatclrref()) &&
                Objects.equals(getWmatori(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatori()) &&
                Objects.equals(getWmatctycod(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatctycod()) &&
                Objects.equals(getWmatlength(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatlength()) &&
                Objects.equals(getWmatlengthUom(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatlengthUom()) &&
                Objects.equals(getWmatdiameter(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatdiameter()) &&
                Objects.equals(getWmatdiameterUom(), procYm1311pk0ym650materialsDesResponsePoutMaterialsDes.getWmatdiameterUom());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnnum(),
                getTrnseq(),
                getMaterialcode(),
                getBaleqty(),
                getUnitwgt(),
                getTotalwgt(),
                getWgtuom(),
                getRemarks(),
                getWtotalBales(),
                getWtotalWeight(),
                getWmatusercode(),
                getUpdmaterialcode(),
                getUpditemtype(),
                getUpdmatusercode(),
                getWmatcps(),
                getWmatclr(),
                getWmatclrdes(),
                getWmatclrref(),
                getWmatori(),
                getWmatctycod(),
                getWmatlength(),
                getWmatlengthUom(),
                getWmatdiameter(),
                getWmatdiameterUom());
    }
}