/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym650closedStockSummaryResponsePoutClosedStockSummary implements Serializable {


    @ColumnAlias("STRCODE")
    private String strcode;

    @ColumnAlias("MATERIALCODE")
    private String materialcode;

    @ColumnAlias("MATUSERCODE")
    private String matusercode;

    @ColumnAlias("STKMONTH")
    private String stkmonth;

    @ColumnAlias("STKYEAR")
    private Short stkyear;

    @ColumnAlias("BALE")
    private Double bale;

    @ColumnAlias("WEIGHT")
    private Double weight;

    public String getStrcode() {
        return this.strcode;
    }

    public void setStrcode(String strcode) {
        this.strcode = strcode;
    }

    public String getMaterialcode() {
        return this.materialcode;
    }

    public void setMaterialcode(String materialcode) {
        this.materialcode = materialcode;
    }

    public String getMatusercode() {
        return this.matusercode;
    }

    public void setMatusercode(String matusercode) {
        this.matusercode = matusercode;
    }

    public String getStkmonth() {
        return this.stkmonth;
    }

    public void setStkmonth(String stkmonth) {
        this.stkmonth = stkmonth;
    }

    public Short getStkyear() {
        return this.stkyear;
    }

    public void setStkyear(Short stkyear) {
        this.stkyear = stkyear;
    }

    public Double getBale() {
        return this.bale;
    }

    public void setBale(Double bale) {
        this.bale = bale;
    }

    public Double getWeight() {
        return this.weight;
    }

    public void setWeight(Double weight) {
        this.weight = weight;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym650closedStockSummaryResponsePoutClosedStockSummary)) return false;
        final ProcYm1311pk0Ym650closedStockSummaryResponsePoutClosedStockSummary procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary = (ProcYm1311pk0Ym650closedStockSummaryResponsePoutClosedStockSummary) o;
        return Objects.equals(getStrcode(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getStrcode()) &&
                Objects.equals(getMaterialcode(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getMaterialcode()) &&
                Objects.equals(getMatusercode(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getMatusercode()) &&
                Objects.equals(getStkmonth(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getStkmonth()) &&
                Objects.equals(getStkyear(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getStkyear()) &&
                Objects.equals(getBale(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getBale()) &&
                Objects.equals(getWeight(), procYm1311pk0ym650closedStockSummaryResponsePoutClosedStockSummary.getWeight());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStrcode(),
                getMaterialcode(),
                getMatusercode(),
                getStkmonth(),
                getStkyear(),
                getBale(),
                getWeight());
    }
}