/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym100fibredetResponsePoutYm100fibredet implements Serializable {


    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("FIBDETSEQ")
    private Byte fibdetseq;

    @ColumnAlias("FIBCPS")
    private String fibcps;

    @ColumnAlias("FIBCLR")
    private String fibclr;

    @ColumnAlias("FIBCDES")
    private String fibcdes;

    @ColumnAlias("FIBCLRREF")
    private String fibclrref;

    @ColumnAlias("FIBFRAC")
    private Float fibfrac;

    @ColumnAlias("W_SUM_FIBYRNFRAC")
    private Float wsumFibyrnfrac;

    @ColumnAlias("W_PRIORITYDECREASING")
    private String wprioritydecreasing;

    @ColumnAlias("FIBORIGIN")
    private String fiborigin;

    @ColumnAlias("CTYCOD")
    private String ctycod;

    @ColumnAlias("W_COUNTRY_DES")
    private String wcountryDes;

    @ColumnAlias("FIBDIAMETER")
    private Float fibdiameter;

    @ColumnAlias("FIBDIAMETER_UOM")
    private String fibdiameterUom;

    @ColumnAlias("FIBLENGTH_MM")
    private Float fiblengthMm;

    @ColumnAlias("SPFIBFDES")
    private String spfibfdes;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("MATERIALCODE")
    private String materialcode;

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public Byte getFibdetseq() {
        return this.fibdetseq;
    }

    public void setFibdetseq(Byte fibdetseq) {
        this.fibdetseq = fibdetseq;
    }

    public String getFibcps() {
        return this.fibcps;
    }

    public void setFibcps(String fibcps) {
        this.fibcps = fibcps;
    }

    public String getFibclr() {
        return this.fibclr;
    }

    public void setFibclr(String fibclr) {
        this.fibclr = fibclr;
    }

    public String getFibcdes() {
        return this.fibcdes;
    }

    public void setFibcdes(String fibcdes) {
        this.fibcdes = fibcdes;
    }

    public String getFibclrref() {
        return this.fibclrref;
    }

    public void setFibclrref(String fibclrref) {
        this.fibclrref = fibclrref;
    }

    public Float getFibfrac() {
        return this.fibfrac;
    }

    public void setFibfrac(Float fibfrac) {
        this.fibfrac = fibfrac;
    }

    public Float getWsumFibyrnfrac() {
        return this.wsumFibyrnfrac;
    }

    public void setWsumFibyrnfrac(Float wsumFibyrnfrac) {
        this.wsumFibyrnfrac = wsumFibyrnfrac;
    }

    public String getWprioritydecreasing() {
        return this.wprioritydecreasing;
    }

    public void setWprioritydecreasing(String wprioritydecreasing) {
        this.wprioritydecreasing = wprioritydecreasing;
    }

    public String getFiborigin() {
        return this.fiborigin;
    }

    public void setFiborigin(String fiborigin) {
        this.fiborigin = fiborigin;
    }

    public String getCtycod() {
        return this.ctycod;
    }

    public void setCtycod(String ctycod) {
        this.ctycod = ctycod;
    }

    public String getWcountryDes() {
        return this.wcountryDes;
    }

    public void setWcountryDes(String wcountryDes) {
        this.wcountryDes = wcountryDes;
    }

    public Float getFibdiameter() {
        return this.fibdiameter;
    }

    public void setFibdiameter(Float fibdiameter) {
        this.fibdiameter = fibdiameter;
    }

    public String getFibdiameterUom() {
        return this.fibdiameterUom;
    }

    public void setFibdiameterUom(String fibdiameterUom) {
        this.fibdiameterUom = fibdiameterUom;
    }

    public Float getFiblengthMm() {
        return this.fiblengthMm;
    }

    public void setFiblengthMm(Float fiblengthMm) {
        this.fiblengthMm = fiblengthMm;
    }

    public String getSpfibfdes() {
        return this.spfibfdes;
    }

    public void setSpfibfdes(String spfibfdes) {
        this.spfibfdes = spfibfdes;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getMaterialcode() {
        return this.materialcode;
    }

    public void setMaterialcode(String materialcode) {
        this.materialcode = materialcode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym100fibredetResponsePoutYm100fibredet)) return false;
        final ProcYm1311pk0Ym100fibredetResponsePoutYm100fibredet procYm1311pk0ym100fibredetResponsePoutYm100fibredet = (ProcYm1311pk0Ym100fibredetResponsePoutYm100fibredet) o;
        return Objects.equals(getYrncod(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getYrncod()) &&
                Objects.equals(getFibdetseq(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibdetseq()) &&
                Objects.equals(getFibcps(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibcps()) &&
                Objects.equals(getFibclr(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibclr()) &&
                Objects.equals(getFibcdes(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibcdes()) &&
                Objects.equals(getFibclrref(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibclrref()) &&
                Objects.equals(getFibfrac(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibfrac()) &&
                Objects.equals(getWsumFibyrnfrac(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getWsumFibyrnfrac()) &&
                Objects.equals(getWprioritydecreasing(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getWprioritydecreasing()) &&
                Objects.equals(getFiborigin(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFiborigin()) &&
                Objects.equals(getCtycod(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getCtycod()) &&
                Objects.equals(getWcountryDes(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getWcountryDes()) &&
                Objects.equals(getFibdiameter(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibdiameter()) &&
                Objects.equals(getFibdiameterUom(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFibdiameterUom()) &&
                Objects.equals(getFiblengthMm(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getFiblengthMm()) &&
                Objects.equals(getSpfibfdes(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getSpfibfdes()) &&
                Objects.equals(getRemarks(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getRemarks()) &&
                Objects.equals(getMaterialcode(), procYm1311pk0ym100fibredetResponsePoutYm100fibredet.getMaterialcode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrncod(),
                getFibdetseq(),
                getFibcps(),
                getFibclr(),
                getFibcdes(),
                getFibclrref(),
                getFibfrac(),
                getWsumFibyrnfrac(),
                getWprioritydecreasing(),
                getFiborigin(),
                getCtycod(),
                getWcountryDes(),
                getFibdiameter(),
                getFibdiameterUom(),
                getFiblengthMm(),
                getSpfibfdes(),
                getRemarks(),
                getMaterialcode());
    }
}