/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym650issueofMaterialsResponse implements Serializable {


    @ColumnAlias("poutIssueofMaterials")
    private List<ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials> poutIssueofMaterials;

    public List<ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials> getPoutIssueofMaterials() {
        return this.poutIssueofMaterials;
    }

    public void setPoutIssueofMaterials(List<ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials> poutIssueofMaterials) {
        this.poutIssueofMaterials = poutIssueofMaterials;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym650issueofMaterialsResponse)) return false;
        final ProcYm1311pk0Ym650issueofMaterialsResponse procYm1311pk0ym650issueofMaterialsResponse = (ProcYm1311pk0Ym650issueofMaterialsResponse) o;
        return Objects.equals(getPoutIssueofMaterials(), procYm1311pk0ym650issueofMaterialsResponse.getPoutIssueofMaterials());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutIssueofMaterials());
    }
}