/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1000pkoYm285insMasterResponse implements Serializable {


    @ColumnAlias("poutyrncod")
    private String poutyrncod;

    @ColumnAlias("poutRecpNum")
    private String poutRecpNum;

    public String getPoutyrncod() {
        return this.poutyrncod;
    }

    public void setPoutyrncod(String poutyrncod) {
        this.poutyrncod = poutyrncod;
    }

    public String getPoutRecpNum() {
        return this.poutRecpNum;
    }

    public void setPoutRecpNum(String poutRecpNum) {
        this.poutRecpNum = poutRecpNum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1000pkoYm285insMasterResponse)) return false;
        final ProcYm1000pkoYm285insMasterResponse procYm1000pkoYm285insMasterResponse = (ProcYm1000pkoYm285insMasterResponse) o;
        return Objects.equals(getPoutyrncod(), procYm1000pkoYm285insMasterResponse.getPoutyrncod()) &&
                Objects.equals(getPoutRecpNum(), procYm1000pkoYm285insMasterResponse.getPoutRecpNum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutyrncod(),
                getPoutRecpNum());
    }
}