/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym100nyrnsubqltybResponse implements Serializable {


    @ColumnAlias("poutNYRNSUBQLTYB")
    private List<ProcYm1311pk0Ym100nyrnsubqltybResponsePoutNyrnsubqltyb> poutNyrnsubqltyb;

    public List<ProcYm1311pk0Ym100nyrnsubqltybResponsePoutNyrnsubqltyb> getPoutNyrnsubqltyb() {
        return this.poutNyrnsubqltyb;
    }

    public void setPoutNyrnsubqltyb(List<ProcYm1311pk0Ym100nyrnsubqltybResponsePoutNyrnsubqltyb> poutNyrnsubqltyb) {
        this.poutNyrnsubqltyb = poutNyrnsubqltyb;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym100nyrnsubqltybResponse)) return false;
        final ProcYm1311pk0Ym100nyrnsubqltybResponse procYm1311pk0ym100nyrnsubqltybResponse = (ProcYm1311pk0Ym100nyrnsubqltybResponse) o;
        return Objects.equals(getPoutNyrnsubqltyb(), procYm1311pk0ym100nyrnsubqltybResponse.getPoutNyrnsubqltyb());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutNyrnsubqltyb());
    }
}