/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pk0Ym400fibreResponsePoutFibre implements Serializable {


    @ColumnAlias("FIBRETYP")
    private String fibretyp;

    @ColumnAlias("FIBREFRAC")
    private Short fibrefrac;

    @ColumnAlias("CONTRACTID")
    private String contractid;

    @ColumnAlias("YNITEMNO")
    private Byte ynitemno;

    @ColumnAlias("W_FIBRETYP_DES")
    private String wfibretypDes;

    public String getFibretyp() {
        return this.fibretyp;
    }

    public void setFibretyp(String fibretyp) {
        this.fibretyp = fibretyp;
    }

    public Short getFibrefrac() {
        return this.fibrefrac;
    }

    public void setFibrefrac(Short fibrefrac) {
        this.fibrefrac = fibrefrac;
    }

    public String getContractid() {
        return this.contractid;
    }

    public void setContractid(String contractid) {
        this.contractid = contractid;
    }

    public Byte getYnitemno() {
        return this.ynitemno;
    }

    public void setYnitemno(Byte ynitemno) {
        this.ynitemno = ynitemno;
    }

    public String getWfibretypDes() {
        return this.wfibretypDes;
    }

    public void setWfibretypDes(String wfibretypDes) {
        this.wfibretypDes = wfibretypDes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pk0Ym400fibreResponsePoutFibre)) return false;
        final ProcYm4000pk0Ym400fibreResponsePoutFibre procYm4000pk0ym400fibreResponsePoutFibre = (ProcYm4000pk0Ym400fibreResponsePoutFibre) o;
        return Objects.equals(getFibretyp(), procYm4000pk0ym400fibreResponsePoutFibre.getFibretyp()) &&
                Objects.equals(getFibrefrac(), procYm4000pk0ym400fibreResponsePoutFibre.getFibrefrac()) &&
                Objects.equals(getContractid(), procYm4000pk0ym400fibreResponsePoutFibre.getContractid()) &&
                Objects.equals(getYnitemno(), procYm4000pk0ym400fibreResponsePoutFibre.getYnitemno()) &&
                Objects.equals(getWfibretypDes(), procYm4000pk0ym400fibreResponsePoutFibre.getWfibretypDes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFibretyp(),
                getFibrefrac(),
                getContractid(),
                getYnitemno(),
                getWfibretypDes());
    }
}