/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pk0Ym400rgYrnSubQltyCResponsePoutRgYrnSubQltyC implements Serializable {


    @ColumnAlias("SUBQLTYCOD")
    private String subqltycod;

    @ColumnAlias("SUBQLTYDES")
    private String subqltydes;

    public String getSubqltycod() {
        return this.subqltycod;
    }

    public void setSubqltycod(String subqltycod) {
        this.subqltycod = subqltycod;
    }

    public String getSubqltydes() {
        return this.subqltydes;
    }

    public void setSubqltydes(String subqltydes) {
        this.subqltydes = subqltydes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pk0Ym400rgYrnSubQltyCResponsePoutRgYrnSubQltyC)) return false;
        final ProcYm4000pk0Ym400rgYrnSubQltyCResponsePoutRgYrnSubQltyC procYm4000pk0ym400rgYrnSubQltyCresponsePoutRgYrnSubQltyC = (ProcYm4000pk0Ym400rgYrnSubQltyCResponsePoutRgYrnSubQltyC) o;
        return Objects.equals(getSubqltycod(), procYm4000pk0ym400rgYrnSubQltyCresponsePoutRgYrnSubQltyC.getSubqltycod()) &&
                Objects.equals(getSubqltydes(), procYm4000pk0ym400rgYrnSubQltyCresponsePoutRgYrnSubQltyC.getSubqltydes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSubqltycod(),
                getSubqltydes());
    }
}