/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials implements Serializable {


    @ColumnAlias("TRNNUM")
    private String trnnum;

    @ColumnAlias("TRNTYP")
    private String trntyp;

    @ColumnAlias("FSTRCOD")
    private String fstrcod;

    @ColumnAlias("FLCNCOD")
    private String flcncod;

    @ColumnAlias("TSTRCOD")
    private String tstrcod;

    @ColumnAlias("TLCNCOD")
    private String tlcncod;

    @ColumnAlias("TRNDATE")
    private LocalDateTime trndate;

    @ColumnAlias("STATUS")
    private String status;

    @ColumnAlias("USRID")
    private String usrid;

    @ColumnAlias("USRDATE")
    private LocalDateTime usrdate;

    @ColumnAlias("REMARKS")
    private String remarks;

    @ColumnAlias("W_STOREIND")
    private String wstoreind;

    public String getTrnnum() {
        return this.trnnum;
    }

    public void setTrnnum(String trnnum) {
        this.trnnum = trnnum;
    }

    public String getTrntyp() {
        return this.trntyp;
    }

    public void setTrntyp(String trntyp) {
        this.trntyp = trntyp;
    }

    public String getFstrcod() {
        return this.fstrcod;
    }

    public void setFstrcod(String fstrcod) {
        this.fstrcod = fstrcod;
    }

    public String getFlcncod() {
        return this.flcncod;
    }

    public void setFlcncod(String flcncod) {
        this.flcncod = flcncod;
    }

    public String getTstrcod() {
        return this.tstrcod;
    }

    public void setTstrcod(String tstrcod) {
        this.tstrcod = tstrcod;
    }

    public String getTlcncod() {
        return this.tlcncod;
    }

    public void setTlcncod(String tlcncod) {
        this.tlcncod = tlcncod;
    }

    public LocalDateTime getTrndate() {
        return this.trndate;
    }

    public void setTrndate(LocalDateTime trndate) {
        this.trndate = trndate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getUsrid() {
        return this.usrid;
    }

    public void setUsrid(String usrid) {
        this.usrid = usrid;
    }

    public LocalDateTime getUsrdate() {
        return this.usrdate;
    }

    public void setUsrdate(LocalDateTime usrdate) {
        this.usrdate = usrdate;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public String getWstoreind() {
        return this.wstoreind;
    }

    public void setWstoreind(String wstoreind) {
        this.wstoreind = wstoreind;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials)) return false;
        final ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials = (ProcYm1311pk0Ym650issueofMaterialsResponsePoutIssueofMaterials) o;
        return Objects.equals(getTrnnum(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getTrnnum()) &&
                Objects.equals(getTrntyp(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getTrntyp()) &&
                Objects.equals(getFstrcod(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getFstrcod()) &&
                Objects.equals(getFlcncod(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getFlcncod()) &&
                Objects.equals(getTstrcod(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getTstrcod()) &&
                Objects.equals(getTlcncod(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getTlcncod()) &&
                Objects.equals(getTrndate(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getTrndate()) &&
                Objects.equals(getStatus(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getStatus()) &&
                Objects.equals(getUsrid(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getUsrid()) &&
                Objects.equals(getUsrdate(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getUsrdate()) &&
                Objects.equals(getRemarks(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getRemarks()) &&
                Objects.equals(getWstoreind(), procYm1311pk0ym650issueofMaterialsResponsePoutIssueofMaterials.getWstoreind());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnnum(),
                getTrntyp(),
                getFstrcod(),
                getFlcncod(),
                getTstrcod(),
                getTlcncod(),
                getTrndate(),
                getStatus(),
                getUsrid(),
                getUsrdate(),
                getRemarks(),
                getWstoreind());
    }
}