/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker implements Serializable {


    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("NYRNCDES")
    private String nyrncdes;

    @ColumnAlias("CONWGT")
    private Float conwgt;

    @ColumnAlias("NUMCON")
    private Short numcon;

    @ColumnAlias("CONECLR")
    private String coneclr;

    @ColumnAlias("LOTWISE")
    private String lotwise;

    @ColumnAlias("MANUDAT")
    private LocalDateTime manudat;

    @ColumnAlias("PALLETID")
    private String palletid;

    @ColumnAlias("GROSSWGT")
    private Double grosswgt;

    @ColumnAlias("CNTSYS")
    private String cntsys;

    @ColumnAlias("CNT")
    private String cnt;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("TAREWGT")
    private Double tarewgt;

    @ColumnAlias("W_CONWGT")
    private BigInteger wconwgt;

    @ColumnAlias("W_NETWGT")
    private Double wnetwgt;

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getNyrncdes() {
        return this.nyrncdes;
    }

    public void setNyrncdes(String nyrncdes) {
        this.nyrncdes = nyrncdes;
    }

    public Float getConwgt() {
        return this.conwgt;
    }

    public void setConwgt(Float conwgt) {
        this.conwgt = conwgt;
    }

    public Short getNumcon() {
        return this.numcon;
    }

    public void setNumcon(Short numcon) {
        this.numcon = numcon;
    }

    public String getConeclr() {
        return this.coneclr;
    }

    public void setConeclr(String coneclr) {
        this.coneclr = coneclr;
    }

    public String getLotwise() {
        return this.lotwise;
    }

    public void setLotwise(String lotwise) {
        this.lotwise = lotwise;
    }

    public LocalDateTime getManudat() {
        return this.manudat;
    }

    public void setManudat(LocalDateTime manudat) {
        this.manudat = manudat;
    }

    public String getPalletid() {
        return this.palletid;
    }

    public void setPalletid(String palletid) {
        this.palletid = palletid;
    }

    public Double getGrosswgt() {
        return this.grosswgt;
    }

    public void setGrosswgt(Double grosswgt) {
        this.grosswgt = grosswgt;
    }

    public String getCntsys() {
        return this.cntsys;
    }

    public void setCntsys(String cntsys) {
        this.cntsys = cntsys;
    }

    public String getCnt() {
        return this.cnt;
    }

    public void setCnt(String cnt) {
        this.cnt = cnt;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public Double getTarewgt() {
        return this.tarewgt;
    }

    public void setTarewgt(Double tarewgt) {
        this.tarewgt = tarewgt;
    }

    public BigInteger getWconwgt() {
        return this.wconwgt;
    }

    public void setWconwgt(BigInteger wconwgt) {
        this.wconwgt = wconwgt;
    }

    public Double getWnetwgt() {
        return this.wnetwgt;
    }

    public void setWnetwgt(Double wnetwgt) {
        this.wnetwgt = wnetwgt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker)) return false;
        final ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker = (ProcYm1311pk0Ym284yarnPalletStickerResponsePoutYarnPalletSticker) o;
        return Objects.equals(getYrncod(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getYrncod()) &&
                Objects.equals(getNyrncdes(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getNyrncdes()) &&
                Objects.equals(getConwgt(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getConwgt()) &&
                Objects.equals(getNumcon(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getNumcon()) &&
                Objects.equals(getConeclr(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getConeclr()) &&
                Objects.equals(getLotwise(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getLotwise()) &&
                Objects.equals(getManudat(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getManudat()) &&
                Objects.equals(getPalletid(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getPalletid()) &&
                Objects.equals(getGrosswgt(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getGrosswgt()) &&
                Objects.equals(getCntsys(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getCntsys()) &&
                Objects.equals(getCnt(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getCnt()) &&
                Objects.equals(getYrnori(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getYrnori()) &&
                Objects.equals(getTarewgt(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getTarewgt()) &&
                Objects.equals(getWconwgt(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getWconwgt()) &&
                Objects.equals(getWnetwgt(), procYm1311pk0ym284yarnPalletStickerResponsePoutYarnPalletSticker.getWnetwgt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getYrncod(),
                getNyrncdes(),
                getConwgt(),
                getNumcon(),
                getConeclr(),
                getLotwise(),
                getManudat(),
                getPalletid(),
                getGrosswgt(),
                getCntsys(),
                getCnt(),
                getYrnori(),
                getTarewgt(),
                getWconwgt(),
                getWnetwgt());
    }
}