/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc implements Serializable {


    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private Byte fabseq;

    @ColumnAlias("YRNID")
    private Short yrnid;

    @ColumnAlias("YRNIDSEQ")
    private Byte yrnidseq;

    @ColumnAlias("YRNMIXCODE")
    private String yrnmixcode;

    @ColumnAlias("YRNORI")
    private String yrnori;

    @ColumnAlias("NYRNCNT")
    private String nyrncnt;

    @ColumnAlias("YRNLOT")
    private String yrnlot;

    @ColumnAlias("NYRNCLR")
    private String nyrnclr;

    @ColumnAlias("YRNFRAC")
    private Short yrnfrac;

    @ColumnAlias("QTYALC")
    private Double qtyalc;

    @ColumnAlias("DATEALC")
    private LocalDateTime datealc;

    @ColumnAlias("DATEDEALC")
    private LocalDateTime datedealc;

    @ColumnAlias("ALCUSRID")
    private String alcusrid;

    @ColumnAlias("DEALCUSRID")
    private String dealcusrid;

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public Byte getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(Byte fabseq) {
        this.fabseq = fabseq;
    }

    public Short getYrnid() {
        return this.yrnid;
    }

    public void setYrnid(Short yrnid) {
        this.yrnid = yrnid;
    }

    public Byte getYrnidseq() {
        return this.yrnidseq;
    }

    public void setYrnidseq(Byte yrnidseq) {
        this.yrnidseq = yrnidseq;
    }

    public String getYrnmixcode() {
        return this.yrnmixcode;
    }

    public void setYrnmixcode(String yrnmixcode) {
        this.yrnmixcode = yrnmixcode;
    }

    public String getYrnori() {
        return this.yrnori;
    }

    public void setYrnori(String yrnori) {
        this.yrnori = yrnori;
    }

    public String getNyrncnt() {
        return this.nyrncnt;
    }

    public void setNyrncnt(String nyrncnt) {
        this.nyrncnt = nyrncnt;
    }

    public String getYrnlot() {
        return this.yrnlot;
    }

    public void setYrnlot(String yrnlot) {
        this.yrnlot = yrnlot;
    }

    public String getNyrnclr() {
        return this.nyrnclr;
    }

    public void setNyrnclr(String nyrnclr) {
        this.nyrnclr = nyrnclr;
    }

    public Short getYrnfrac() {
        return this.yrnfrac;
    }

    public void setYrnfrac(Short yrnfrac) {
        this.yrnfrac = yrnfrac;
    }

    public Double getQtyalc() {
        return this.qtyalc;
    }

    public void setQtyalc(Double qtyalc) {
        this.qtyalc = qtyalc;
    }

    public LocalDateTime getDatealc() {
        return this.datealc;
    }

    public void setDatealc(LocalDateTime datealc) {
        this.datealc = datealc;
    }

    public LocalDateTime getDatedealc() {
        return this.datedealc;
    }

    public void setDatedealc(LocalDateTime datedealc) {
        this.datedealc = datedealc;
    }

    public String getAlcusrid() {
        return this.alcusrid;
    }

    public void setAlcusrid(String alcusrid) {
        this.alcusrid = alcusrid;
    }

    public String getDealcusrid() {
        return this.dealcusrid;
    }

    public void setDealcusrid(String dealcusrid) {
        this.dealcusrid = dealcusrid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc)) return false;
        final ProcYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc = (ProcYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc) o;
        return Objects.equals(getOrdnum(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getOrdnum()) &&
                Objects.equals(getFabseq(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getFabseq()) &&
                Objects.equals(getYrnid(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getYrnid()) &&
                Objects.equals(getYrnidseq(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getYrnidseq()) &&
                Objects.equals(getYrnmixcode(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getYrnmixcode()) &&
                Objects.equals(getYrnori(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getYrnori()) &&
                Objects.equals(getNyrncnt(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getNyrncnt()) &&
                Objects.equals(getYrnlot(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getYrnlot()) &&
                Objects.equals(getNyrnclr(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getNyrnclr()) &&
                Objects.equals(getYrnfrac(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getYrnfrac()) &&
                Objects.equals(getQtyalc(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getQtyalc()) &&
                Objects.equals(getDatealc(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getDatealc()) &&
                Objects.equals(getDatedealc(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getDatedealc()) &&
                Objects.equals(getAlcusrid(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getAlcusrid()) &&
                Objects.equals(getDealcusrid(), procYm1000pkoYm130qryYrnDeallocationResponsePoutDeAlc.getDealcusrid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrdnum(),
                getFabseq(),
                getYrnid(),
                getYrnidseq(),
                getYrnmixcode(),
                getYrnori(),
                getNyrncnt(),
                getYrnlot(),
                getNyrnclr(),
                getYrnfrac(),
                getQtyalc(),
                getDatealc(),
                getDatedealc(),
                getAlcusrid(),
                getDealcusrid());
    }
}