/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1000pkoYm122detailResponsePoutYm122detail implements Serializable {


    @ColumnAlias("TRNSEQ")
    private BigDecimal trnseq;

    @ColumnAlias("USRDAT")
    private LocalDateTime usrdat;

    @ColumnAlias("TRNTYPE")
    private String trntype;

    @ColumnAlias("QTYIN")
    private BigDecimal qtyin;

    @ColumnAlias("QTYOUT")
    private BigDecimal qtyout;

    @ColumnAlias("REFTITLE")
    private String reftitle;

    @ColumnAlias("REFNUM")
    private String refnum;

    @ColumnAlias("ORDNUM")
    private String ordnum;

    @ColumnAlias("FABSEQ")
    private BigDecimal fabseq;

    @ColumnAlias("FABWGT")
    private String fabwgt;

    @ColumnAlias("FABTYP")
    private BigDecimal fabtyp;

    public BigDecimal getTrnseq() {
        return this.trnseq;
    }

    public void setTrnseq(BigDecimal trnseq) {
        this.trnseq = trnseq;
    }

    public LocalDateTime getUsrdat() {
        return this.usrdat;
    }

    public void setUsrdat(LocalDateTime usrdat) {
        this.usrdat = usrdat;
    }

    public String getTrntype() {
        return this.trntype;
    }

    public void setTrntype(String trntype) {
        this.trntype = trntype;
    }

    public BigDecimal getQtyin() {
        return this.qtyin;
    }

    public void setQtyin(BigDecimal qtyin) {
        this.qtyin = qtyin;
    }

    public BigDecimal getQtyout() {
        return this.qtyout;
    }

    public void setQtyout(BigDecimal qtyout) {
        this.qtyout = qtyout;
    }

    public String getReftitle() {
        return this.reftitle;
    }

    public void setReftitle(String reftitle) {
        this.reftitle = reftitle;
    }

    public String getRefnum() {
        return this.refnum;
    }

    public void setRefnum(String refnum) {
        this.refnum = refnum;
    }

    public String getOrdnum() {
        return this.ordnum;
    }

    public void setOrdnum(String ordnum) {
        this.ordnum = ordnum;
    }

    public BigDecimal getFabseq() {
        return this.fabseq;
    }

    public void setFabseq(BigDecimal fabseq) {
        this.fabseq = fabseq;
    }

    public String getFabwgt() {
        return this.fabwgt;
    }

    public void setFabwgt(String fabwgt) {
        this.fabwgt = fabwgt;
    }

    public BigDecimal getFabtyp() {
        return this.fabtyp;
    }

    public void setFabtyp(BigDecimal fabtyp) {
        this.fabtyp = fabtyp;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1000pkoYm122detailResponsePoutYm122detail)) return false;
        final ProcYm1000pkoYm122detailResponsePoutYm122detail procYm1000pkoYm122detailResponsePoutYm122detail = (ProcYm1000pkoYm122detailResponsePoutYm122detail) o;
        return Objects.equals(getTrnseq(), procYm1000pkoYm122detailResponsePoutYm122detail.getTrnseq()) &&
                Objects.equals(getUsrdat(), procYm1000pkoYm122detailResponsePoutYm122detail.getUsrdat()) &&
                Objects.equals(getTrntype(), procYm1000pkoYm122detailResponsePoutYm122detail.getTrntype()) &&
                Objects.equals(getQtyin(), procYm1000pkoYm122detailResponsePoutYm122detail.getQtyin()) &&
                Objects.equals(getQtyout(), procYm1000pkoYm122detailResponsePoutYm122detail.getQtyout()) &&
                Objects.equals(getReftitle(), procYm1000pkoYm122detailResponsePoutYm122detail.getReftitle()) &&
                Objects.equals(getRefnum(), procYm1000pkoYm122detailResponsePoutYm122detail.getRefnum()) &&
                Objects.equals(getOrdnum(), procYm1000pkoYm122detailResponsePoutYm122detail.getOrdnum()) &&
                Objects.equals(getFabseq(), procYm1000pkoYm122detailResponsePoutYm122detail.getFabseq()) &&
                Objects.equals(getFabwgt(), procYm1000pkoYm122detailResponsePoutYm122detail.getFabwgt()) &&
                Objects.equals(getFabtyp(), procYm1000pkoYm122detailResponsePoutYm122detail.getFabtyp());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getTrnseq(),
                getUsrdat(),
                getTrntype(),
                getQtyin(),
                getQtyout(),
                getReftitle(),
                getRefnum(),
                getOrdnum(),
                getFabseq(),
                getFabwgt(),
                getFabtyp());
    }
}