/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1000pkoYm122detailResponse implements Serializable {


    @ColumnAlias("pOutYM122Detail")
    private List<ProcYm1000pkoYm122detailResponsePoutYm122detail> poutYm122detail;

    public List<ProcYm1000pkoYm122detailResponsePoutYm122detail> getPoutYm122detail() {
        return this.poutYm122detail;
    }

    public void setPoutYm122detail(List<ProcYm1000pkoYm122detailResponsePoutYm122detail> poutYm122detail) {
        this.poutYm122detail = poutYm122detail;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1000pkoYm122detailResponse)) return false;
        final ProcYm1000pkoYm122detailResponse procYm1000pkoYm122detailResponse = (ProcYm1000pkoYm122detailResponse) o;
        return Objects.equals(getPoutYm122detail(), procYm1000pkoYm122detailResponse.getPoutYm122detail());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPoutYm122detail());
    }
}