/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm1311pk0Ym100fibreResponsePoutYm100fibre implements Serializable {


    @ColumnAlias("FIBRETYP")
    private String fibretyp;

    @ColumnAlias("FIBREFRAC")
    private Short fibrefrac;

    @ColumnAlias("YRNCOD")
    private String yrncod;

    @ColumnAlias("W_FIBRETYP_DES")
    private String wfibretypDes;

    public String getFibretyp() {
        return this.fibretyp;
    }

    public void setFibretyp(String fibretyp) {
        this.fibretyp = fibretyp;
    }

    public Short getFibrefrac() {
        return this.fibrefrac;
    }

    public void setFibrefrac(Short fibrefrac) {
        this.fibrefrac = fibrefrac;
    }

    public String getYrncod() {
        return this.yrncod;
    }

    public void setYrncod(String yrncod) {
        this.yrncod = yrncod;
    }

    public String getWfibretypDes() {
        return this.wfibretypDes;
    }

    public void setWfibretypDes(String wfibretypDes) {
        this.wfibretypDes = wfibretypDes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm1311pk0Ym100fibreResponsePoutYm100fibre)) return false;
        final ProcYm1311pk0Ym100fibreResponsePoutYm100fibre procYm1311pk0ym100fibreResponsePoutYm100fibre = (ProcYm1311pk0Ym100fibreResponsePoutYm100fibre) o;
        return Objects.equals(getFibretyp(), procYm1311pk0ym100fibreResponsePoutYm100fibre.getFibretyp()) &&
                Objects.equals(getFibrefrac(), procYm1311pk0ym100fibreResponsePoutYm100fibre.getFibrefrac()) &&
                Objects.equals(getYrncod(), procYm1311pk0ym100fibreResponsePoutYm100fibre.getYrncod()) &&
                Objects.equals(getWfibretypDes(), procYm1311pk0ym100fibreResponsePoutYm100fibre.getWfibretypDes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFibretyp(),
                getFibrefrac(),
                getYrncod(),
                getWfibretypDes());
    }
}