/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcYm4000pkoYm400subcntResponsePoutSubcnt implements Serializable {


    @ColumnAlias("CONTRACTID")
    private String contractid;

    @ColumnAlias("YNITEMNO")
    private Byte ynitemno;

    @ColumnAlias("SUBCNTSEQ")
    private Byte subcntseq;

    @ColumnAlias("SUBCNTSYS")
    private String subcntsys;

    @ColumnAlias("PLY")
    private Byte ply;

    @ColumnAlias("SUBCNT")
    private Short subcnt;

    @ColumnAlias("FILAMENT")
    private Short filament;

    @ColumnAlias("SUBCNTCPS")
    private String subcntcps;

    @ColumnAlias("SUBCNTDES")
    private String subcntdes;

    @ColumnAlias("W_MINPLY")
    private Byte wminply;

    @ColumnAlias("W_MAXPLY")
    private Byte wmaxply;

    @ColumnAlias("W_MINCNT")
    private Short wmincnt;

    @ColumnAlias("W_MAXCNT")
    private Short wmaxcnt;

    @ColumnAlias("W_MINFILAMENT")
    private Short wminfilament;

    @ColumnAlias("W_MAXFILAMENT")
    private Short wmaxfilament;

    @ColumnAlias("W_SUBCNTCPS_DES")
    private String wsubcntcpsDes;

    public String getContractid() {
        return this.contractid;
    }

    public void setContractid(String contractid) {
        this.contractid = contractid;
    }

    public Byte getYnitemno() {
        return this.ynitemno;
    }

    public void setYnitemno(Byte ynitemno) {
        this.ynitemno = ynitemno;
    }

    public Byte getSubcntseq() {
        return this.subcntseq;
    }

    public void setSubcntseq(Byte subcntseq) {
        this.subcntseq = subcntseq;
    }

    public String getSubcntsys() {
        return this.subcntsys;
    }

    public void setSubcntsys(String subcntsys) {
        this.subcntsys = subcntsys;
    }

    public Byte getPly() {
        return this.ply;
    }

    public void setPly(Byte ply) {
        this.ply = ply;
    }

    public Short getSubcnt() {
        return this.subcnt;
    }

    public void setSubcnt(Short subcnt) {
        this.subcnt = subcnt;
    }

    public Short getFilament() {
        return this.filament;
    }

    public void setFilament(Short filament) {
        this.filament = filament;
    }

    public String getSubcntcps() {
        return this.subcntcps;
    }

    public void setSubcntcps(String subcntcps) {
        this.subcntcps = subcntcps;
    }

    public String getSubcntdes() {
        return this.subcntdes;
    }

    public void setSubcntdes(String subcntdes) {
        this.subcntdes = subcntdes;
    }

    public Byte getWminply() {
        return this.wminply;
    }

    public void setWminply(Byte wminply) {
        this.wminply = wminply;
    }

    public Byte getWmaxply() {
        return this.wmaxply;
    }

    public void setWmaxply(Byte wmaxply) {
        this.wmaxply = wmaxply;
    }

    public Short getWmincnt() {
        return this.wmincnt;
    }

    public void setWmincnt(Short wmincnt) {
        this.wmincnt = wmincnt;
    }

    public Short getWmaxcnt() {
        return this.wmaxcnt;
    }

    public void setWmaxcnt(Short wmaxcnt) {
        this.wmaxcnt = wmaxcnt;
    }

    public Short getWminfilament() {
        return this.wminfilament;
    }

    public void setWminfilament(Short wminfilament) {
        this.wminfilament = wminfilament;
    }

    public Short getWmaxfilament() {
        return this.wmaxfilament;
    }

    public void setWmaxfilament(Short wmaxfilament) {
        this.wmaxfilament = wmaxfilament;
    }

    public String getWsubcntcpsDes() {
        return this.wsubcntcpsDes;
    }

    public void setWsubcntcpsDes(String wsubcntcpsDes) {
        this.wsubcntcpsDes = wsubcntcpsDes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcYm4000pkoYm400subcntResponsePoutSubcnt)) return false;
        final ProcYm4000pkoYm400subcntResponsePoutSubcnt procYm4000pkoYm400subcntResponsePoutSubcnt = (ProcYm4000pkoYm400subcntResponsePoutSubcnt) o;
        return Objects.equals(getContractid(), procYm4000pkoYm400subcntResponsePoutSubcnt.getContractid()) &&
                Objects.equals(getYnitemno(), procYm4000pkoYm400subcntResponsePoutSubcnt.getYnitemno()) &&
                Objects.equals(getSubcntseq(), procYm4000pkoYm400subcntResponsePoutSubcnt.getSubcntseq()) &&
                Objects.equals(getSubcntsys(), procYm4000pkoYm400subcntResponsePoutSubcnt.getSubcntsys()) &&
                Objects.equals(getPly(), procYm4000pkoYm400subcntResponsePoutSubcnt.getPly()) &&
                Objects.equals(getSubcnt(), procYm4000pkoYm400subcntResponsePoutSubcnt.getSubcnt()) &&
                Objects.equals(getFilament(), procYm4000pkoYm400subcntResponsePoutSubcnt.getFilament()) &&
                Objects.equals(getSubcntcps(), procYm4000pkoYm400subcntResponsePoutSubcnt.getSubcntcps()) &&
                Objects.equals(getSubcntdes(), procYm4000pkoYm400subcntResponsePoutSubcnt.getSubcntdes()) &&
                Objects.equals(getWminply(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWminply()) &&
                Objects.equals(getWmaxply(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWmaxply()) &&
                Objects.equals(getWmincnt(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWmincnt()) &&
                Objects.equals(getWmaxcnt(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWmaxcnt()) &&
                Objects.equals(getWminfilament(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWminfilament()) &&
                Objects.equals(getWmaxfilament(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWmaxfilament()) &&
                Objects.equals(getWsubcntcpsDes(), procYm4000pkoYm400subcntResponsePoutSubcnt.getWsubcntcpsDes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContractid(),
                getYnitemno(),
                getSubcntseq(),
                getSubcntsys(),
                getPly(),
                getSubcnt(),
                getFilament(),
                getSubcntcps(),
                getSubcntdes(),
                getWminply(),
                getWmaxply(),
                getWmincnt(),
                getWmaxcnt(),
                getWminfilament(),
                getWmaxfilament(),
                getWsubcntcpsDes());
    }
}