/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcYm1000wpk0YnreqnYm142cancelRequest implements Serializable {


    @JsonProperty("pReqnum")
    private BigDecimal preqnum;

    @JsonProperty("pReqnseq")
    private Integer preqnseq;

    @JsonProperty("pTotqtydel")
    private BigDecimal ptotqtydel;

    @JsonProperty("pQtyreqn")
    private BigDecimal pqtyreqn;

    @JsonProperty("pTotpaldel")
    private Integer ptotpaldel;

    @JsonProperty("pTotpal")
    private Integer ptotpal;

    @JsonProperty("pOrdnum")
    private String pordnum;

    @JsonProperty("pFabseq")
    private Integer pfabseq;

    @JsonProperty("pYrnid")
    private Integer pyrnid;

    @JsonProperty("pAlcseq")
    private Integer palcseq;

    @JsonProperty("pYrnmix")
    private String pyrnmix;

    @JsonProperty("pWrhnum")
    private String pwrhnum;

    public BigDecimal getPreqnum() {
        return this.preqnum;
    }

    public void setPreqnum(BigDecimal preqnum) {
        this.preqnum = preqnum;
    }

    public Integer getPreqnseq() {
        return this.preqnseq;
    }

    public void setPreqnseq(Integer preqnseq) {
        this.preqnseq = preqnseq;
    }

    public BigDecimal getPtotqtydel() {
        return this.ptotqtydel;
    }

    public void setPtotqtydel(BigDecimal ptotqtydel) {
        this.ptotqtydel = ptotqtydel;
    }

    public BigDecimal getPqtyreqn() {
        return this.pqtyreqn;
    }

    public void setPqtyreqn(BigDecimal pqtyreqn) {
        this.pqtyreqn = pqtyreqn;
    }

    public Integer getPtotpaldel() {
        return this.ptotpaldel;
    }

    public void setPtotpaldel(Integer ptotpaldel) {
        this.ptotpaldel = ptotpaldel;
    }

    public Integer getPtotpal() {
        return this.ptotpal;
    }

    public void setPtotpal(Integer ptotpal) {
        this.ptotpal = ptotpal;
    }

    public String getPordnum() {
        return this.pordnum;
    }

    public void setPordnum(String pordnum) {
        this.pordnum = pordnum;
    }

    public Integer getPfabseq() {
        return this.pfabseq;
    }

    public void setPfabseq(Integer pfabseq) {
        this.pfabseq = pfabseq;
    }

    public Integer getPyrnid() {
        return this.pyrnid;
    }

    public void setPyrnid(Integer pyrnid) {
        this.pyrnid = pyrnid;
    }

    public Integer getPalcseq() {
        return this.palcseq;
    }

    public void setPalcseq(Integer palcseq) {
        this.palcseq = palcseq;
    }

    public String getPyrnmix() {
        return this.pyrnmix;
    }

    public void setPyrnmix(String pyrnmix) {
        this.pyrnmix = pyrnmix;
    }

    public String getPwrhnum() {
        return this.pwrhnum;
    }

    public void setPwrhnum(String pwrhnum) {
        this.pwrhnum = pwrhnum;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcYm1000wpk0YnreqnYm142cancelRequest)) return false;
        final UpdateProcYm1000wpk0YnreqnYm142cancelRequest updateProcYm1000wpk0ynreqnYm142cancelRequest = (UpdateProcYm1000wpk0YnreqnYm142cancelRequest) o;
        return Objects.equals(getPreqnum(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPreqnum()) &&
                Objects.equals(getPreqnseq(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPreqnseq()) &&
                Objects.equals(getPtotqtydel(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPtotqtydel()) &&
                Objects.equals(getPqtyreqn(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPqtyreqn()) &&
                Objects.equals(getPtotpaldel(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPtotpaldel()) &&
                Objects.equals(getPtotpal(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPtotpal()) &&
                Objects.equals(getPordnum(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPordnum()) &&
                Objects.equals(getPfabseq(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPfabseq()) &&
                Objects.equals(getPyrnid(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPyrnid()) &&
                Objects.equals(getPalcseq(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPalcseq()) &&
                Objects.equals(getPyrnmix(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPyrnmix()) &&
                Objects.equals(getPwrhnum(), updateProcYm1000wpk0ynreqnYm142cancelRequest.getPwrhnum());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPreqnum(),
                getPreqnseq(),
                getPtotqtydel(),
                getPqtyreqn(),
                getPtotpaldel(),
                getPtotpal(),
                getPordnum(),
                getPfabseq(),
                getPyrnid(),
                getPalcseq(),
                getPyrnmix(),
                getPwrhnum());
    }
}