/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcYm1000wpk0YnretYm165kgsAvlRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pKgsAvl")
    private BigDecimal pkgsAvl;

    @JsonProperty("pRetnum")
    private String pretnum;

    @JsonProperty("pYrnmix")
    private String pyrnmix;

    @JsonProperty("pPalletid")
    private String ppalletid;

    @JsonProperty("pWrhnum")
    private String pwrhnum;

    @JsonProperty("pKgsret")
    private BigDecimal pkgsret;

    @JsonProperty("pKgsmadeava")
    private BigDecimal pkgsmadeava;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public BigDecimal getPkgsAvl() {
        return this.pkgsAvl;
    }

    public void setPkgsAvl(BigDecimal pkgsAvl) {
        this.pkgsAvl = pkgsAvl;
    }

    public String getPretnum() {
        return this.pretnum;
    }

    public void setPretnum(String pretnum) {
        this.pretnum = pretnum;
    }

    public String getPyrnmix() {
        return this.pyrnmix;
    }

    public void setPyrnmix(String pyrnmix) {
        this.pyrnmix = pyrnmix;
    }

    public String getPpalletid() {
        return this.ppalletid;
    }

    public void setPpalletid(String ppalletid) {
        this.ppalletid = ppalletid;
    }

    public String getPwrhnum() {
        return this.pwrhnum;
    }

    public void setPwrhnum(String pwrhnum) {
        this.pwrhnum = pwrhnum;
    }

    public BigDecimal getPkgsret() {
        return this.pkgsret;
    }

    public void setPkgsret(BigDecimal pkgsret) {
        this.pkgsret = pkgsret;
    }

    public BigDecimal getPkgsmadeava() {
        return this.pkgsmadeava;
    }

    public void setPkgsmadeava(BigDecimal pkgsmadeava) {
        this.pkgsmadeava = pkgsmadeava;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcYm1000wpk0YnretYm165kgsAvlRequest)) return false;
        final UpdateProcYm1000wpk0YnretYm165kgsAvlRequest updateProcYm1000wpk0ynretYm165kgsAvlRequest = (UpdateProcYm1000wpk0YnretYm165kgsAvlRequest) o;
        return Objects.equals(getPprgid(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPprgid()) &&
                Objects.equals(getPkgsAvl(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPkgsAvl()) &&
                Objects.equals(getPretnum(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPretnum()) &&
                Objects.equals(getPyrnmix(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPyrnmix()) &&
                Objects.equals(getPpalletid(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPpalletid()) &&
                Objects.equals(getPwrhnum(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPwrhnum()) &&
                Objects.equals(getPkgsret(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPkgsret()) &&
                Objects.equals(getPkgsmadeava(), updateProcYm1000wpk0ynretYm165kgsAvlRequest.getPkgsmadeava());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPkgsAvl(),
                getPretnum(),
                getPyrnmix(),
                getPpalletid(),
                getPwrhnum(),
                getPkgsret(),
                getPkgsmadeava());
    }
}