/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcYm1311pk0Ym100updMiscInfoRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pYrncod")
    private String pyrncod;

    @JsonProperty("pCNTNUM")
    private String pcntnum;

    @JsonProperty("pCONCAR")
    private BigDecimal pconcar;

    @JsonProperty("pSUPPALWGT")
    private BigDecimal psuppalwgt;

    @JsonProperty("pEMPCON")
    private BigDecimal pempcon;

    @JsonProperty("pQTYREJ")
    private BigDecimal pqtyrej;

    @JsonProperty("pSTKTYP")
    private String pstktyp;

    @JsonProperty("pQTYREC")
    private BigDecimal pqtyrec;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPyrncod() {
        return this.pyrncod;
    }

    public void setPyrncod(String pyrncod) {
        this.pyrncod = pyrncod;
    }

    public String getPcntnum() {
        return this.pcntnum;
    }

    public void setPcntnum(String pcntnum) {
        this.pcntnum = pcntnum;
    }

    public BigDecimal getPconcar() {
        return this.pconcar;
    }

    public void setPconcar(BigDecimal pconcar) {
        this.pconcar = pconcar;
    }

    public BigDecimal getPsuppalwgt() {
        return this.psuppalwgt;
    }

    public void setPsuppalwgt(BigDecimal psuppalwgt) {
        this.psuppalwgt = psuppalwgt;
    }

    public BigDecimal getPempcon() {
        return this.pempcon;
    }

    public void setPempcon(BigDecimal pempcon) {
        this.pempcon = pempcon;
    }

    public BigDecimal getPqtyrej() {
        return this.pqtyrej;
    }

    public void setPqtyrej(BigDecimal pqtyrej) {
        this.pqtyrej = pqtyrej;
    }

    public String getPstktyp() {
        return this.pstktyp;
    }

    public void setPstktyp(String pstktyp) {
        this.pstktyp = pstktyp;
    }

    public BigDecimal getPqtyrec() {
        return this.pqtyrec;
    }

    public void setPqtyrec(BigDecimal pqtyrec) {
        this.pqtyrec = pqtyrec;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcYm1311pk0Ym100updMiscInfoRequest)) return false;
        final UpdateProcYm1311pk0Ym100updMiscInfoRequest updateProcYm1311pk0ym100updMiscInfoRequest = (UpdateProcYm1311pk0Ym100updMiscInfoRequest) o;
        return Objects.equals(getPprgid(), updateProcYm1311pk0ym100updMiscInfoRequest.getPprgid()) &&
                Objects.equals(getPyrncod(), updateProcYm1311pk0ym100updMiscInfoRequest.getPyrncod()) &&
                Objects.equals(getPcntnum(), updateProcYm1311pk0ym100updMiscInfoRequest.getPcntnum()) &&
                Objects.equals(getPconcar(), updateProcYm1311pk0ym100updMiscInfoRequest.getPconcar()) &&
                Objects.equals(getPsuppalwgt(), updateProcYm1311pk0ym100updMiscInfoRequest.getPsuppalwgt()) &&
                Objects.equals(getPempcon(), updateProcYm1311pk0ym100updMiscInfoRequest.getPempcon()) &&
                Objects.equals(getPqtyrej(), updateProcYm1311pk0ym100updMiscInfoRequest.getPqtyrej()) &&
                Objects.equals(getPstktyp(), updateProcYm1311pk0ym100updMiscInfoRequest.getPstktyp()) &&
                Objects.equals(getPqtyrec(), updateProcYm1311pk0ym100updMiscInfoRequest.getPqtyrec());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPyrncod(),
                getPcntnum(),
                getPconcar(),
                getPsuppalwgt(),
                getPempcon(),
                getPqtyrej(),
                getPstktyp(),
                getPqtyrec());
    }
}