/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcYm4000pk0Ym410ackPalletRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pWrhNum")
    private String pwrhNum;

    @JsonProperty("pDateRec")
    private Date pdateRec;

    @JsonProperty("pYrnCod")
    private String pyrnCod;

    @JsonProperty("pContractid")
    private String pcontractid;

    @JsonProperty("pYnItemNo")
    private String pynItemNo;

    @JsonProperty("pContainerSeq")
    private String pcontainerSeq;

    @JsonProperty("pPalletSeq")
    private String ppalletSeq;

    @JsonProperty("pPalletCat")
    private String ppalletCat;

    @JsonProperty("pConWgt")
    private String pconWgt;

    @JsonProperty("pNumCon")
    private String pnumCon;

    @JsonProperty("pConcar")
    private String pconcar;

    @JsonProperty("pCarpall")
    private String pcarpall;

    @JsonProperty("pPalletId")
    private String ppalletId;

    @JsonProperty("pTotact")
    private Integer ptotact;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPwrhNum() {
        return this.pwrhNum;
    }

    public void setPwrhNum(String pwrhNum) {
        this.pwrhNum = pwrhNum;
    }

    public Date getPdateRec() {
        return this.pdateRec;
    }

    public void setPdateRec(Date pdateRec) {
        this.pdateRec = pdateRec;
    }

    public String getPyrnCod() {
        return this.pyrnCod;
    }

    public void setPyrnCod(String pyrnCod) {
        this.pyrnCod = pyrnCod;
    }

    public String getPcontractid() {
        return this.pcontractid;
    }

    public void setPcontractid(String pcontractid) {
        this.pcontractid = pcontractid;
    }

    public String getPynItemNo() {
        return this.pynItemNo;
    }

    public void setPynItemNo(String pynItemNo) {
        this.pynItemNo = pynItemNo;
    }

    public String getPcontainerSeq() {
        return this.pcontainerSeq;
    }

    public void setPcontainerSeq(String pcontainerSeq) {
        this.pcontainerSeq = pcontainerSeq;
    }

    public String getPpalletSeq() {
        return this.ppalletSeq;
    }

    public void setPpalletSeq(String ppalletSeq) {
        this.ppalletSeq = ppalletSeq;
    }

    public String getPpalletCat() {
        return this.ppalletCat;
    }

    public void setPpalletCat(String ppalletCat) {
        this.ppalletCat = ppalletCat;
    }

    public String getPconWgt() {
        return this.pconWgt;
    }

    public void setPconWgt(String pconWgt) {
        this.pconWgt = pconWgt;
    }

    public String getPnumCon() {
        return this.pnumCon;
    }

    public void setPnumCon(String pnumCon) {
        this.pnumCon = pnumCon;
    }

    public String getPconcar() {
        return this.pconcar;
    }

    public void setPconcar(String pconcar) {
        this.pconcar = pconcar;
    }

    public String getPcarpall() {
        return this.pcarpall;
    }

    public void setPcarpall(String pcarpall) {
        this.pcarpall = pcarpall;
    }

    public String getPpalletId() {
        return this.ppalletId;
    }

    public void setPpalletId(String ppalletId) {
        this.ppalletId = ppalletId;
    }

    public Integer getPtotact() {
        return this.ptotact;
    }

    public void setPtotact(Integer ptotact) {
        this.ptotact = ptotact;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcYm4000pk0Ym410ackPalletRequest)) return false;
        final UpdateProcYm4000pk0Ym410ackPalletRequest updateProcYm4000pk0ym410ackPalletRequest = (UpdateProcYm4000pk0Ym410ackPalletRequest) o;
        return Objects.equals(getPprgid(), updateProcYm4000pk0ym410ackPalletRequest.getPprgid()) &&
                Objects.equals(getPwrhNum(), updateProcYm4000pk0ym410ackPalletRequest.getPwrhNum()) &&
                Objects.equals(getPdateRec(), updateProcYm4000pk0ym410ackPalletRequest.getPdateRec()) &&
                Objects.equals(getPyrnCod(), updateProcYm4000pk0ym410ackPalletRequest.getPyrnCod()) &&
                Objects.equals(getPcontractid(), updateProcYm4000pk0ym410ackPalletRequest.getPcontractid()) &&
                Objects.equals(getPynItemNo(), updateProcYm4000pk0ym410ackPalletRequest.getPynItemNo()) &&
                Objects.equals(getPcontainerSeq(), updateProcYm4000pk0ym410ackPalletRequest.getPcontainerSeq()) &&
                Objects.equals(getPpalletSeq(), updateProcYm4000pk0ym410ackPalletRequest.getPpalletSeq()) &&
                Objects.equals(getPpalletCat(), updateProcYm4000pk0ym410ackPalletRequest.getPpalletCat()) &&
                Objects.equals(getPconWgt(), updateProcYm4000pk0ym410ackPalletRequest.getPconWgt()) &&
                Objects.equals(getPnumCon(), updateProcYm4000pk0ym410ackPalletRequest.getPnumCon()) &&
                Objects.equals(getPconcar(), updateProcYm4000pk0ym410ackPalletRequest.getPconcar()) &&
                Objects.equals(getPcarpall(), updateProcYm4000pk0ym410ackPalletRequest.getPcarpall()) &&
                Objects.equals(getPpalletId(), updateProcYm4000pk0ym410ackPalletRequest.getPpalletId()) &&
                Objects.equals(getPtotact(), updateProcYm4000pk0ym410ackPalletRequest.getPtotact());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPwrhNum(),
                getPdateRec(),
                getPyrnCod(),
                getPcontractid(),
                getPynItemNo(),
                getPcontainerSeq(),
                getPpalletSeq(),
                getPpalletCat(),
                getPconWgt(),
                getPnumCon(),
                getPconcar(),
                getPcarpall(),
                getPpalletId(),
                getPtotact());
    }
}