/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateProcYm1000wpk0YnretYm165discardRequest implements Serializable {


    @JsonProperty("pPrgid")
    private String pprgid;

    @JsonProperty("pRetnum")
    private String pretnum;

    @JsonProperty("pYrnmix")
    private String pyrnmix;

    @JsonProperty("pPalletid")
    private String ppalletid;

    public String getPprgid() {
        return this.pprgid;
    }

    public void setPprgid(String pprgid) {
        this.pprgid = pprgid;
    }

    public String getPretnum() {
        return this.pretnum;
    }

    public void setPretnum(String pretnum) {
        this.pretnum = pretnum;
    }

    public String getPyrnmix() {
        return this.pyrnmix;
    }

    public void setPyrnmix(String pyrnmix) {
        this.pyrnmix = pyrnmix;
    }

    public String getPpalletid() {
        return this.ppalletid;
    }

    public void setPpalletid(String ppalletid) {
        this.ppalletid = ppalletid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateProcYm1000wpk0YnretYm165discardRequest)) return false;
        final UpdateProcYm1000wpk0YnretYm165discardRequest updateProcYm1000wpk0ynretYm165discardRequest = (UpdateProcYm1000wpk0YnretYm165discardRequest) o;
        return Objects.equals(getPprgid(), updateProcYm1000wpk0ynretYm165discardRequest.getPprgid()) &&
                Objects.equals(getPretnum(), updateProcYm1000wpk0ynretYm165discardRequest.getPretnum()) &&
                Objects.equals(getPyrnmix(), updateProcYm1000wpk0ynretYm165discardRequest.getPyrnmix()) &&
                Objects.equals(getPpalletid(), updateProcYm1000wpk0ynretYm165discardRequest.getPpalletid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPprgid(),
                getPretnum(),
                getPyrnmix(),
                getPpalletid());
    }
}