/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryYm650TstrcodResponse implements Serializable {


    @ColumnAlias("ITEMDES3")
    private String itemdes3;

    @ColumnAlias("ITEMCOD")
    private String itemcod;

    @ColumnAlias("ITEMDES")
    private String itemdes;

    public String getItemdes3() {
        return this.itemdes3;
    }

    public void setItemdes3(String itemdes3) {
        this.itemdes3 = itemdes3;
    }

    public String getItemcod() {
        return this.itemcod;
    }

    public void setItemcod(String itemcod) {
        this.itemcod = itemcod;
    }

    public String getItemdes() {
        return this.itemdes;
    }

    public void setItemdes(String itemdes) {
        this.itemdes = itemdes;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryYm650TstrcodResponse)) return false;
        final QryYm650TstrcodResponse qryYm650tstrcodResponse = (QryYm650TstrcodResponse) o;
        return Objects.equals(getItemdes3(), qryYm650tstrcodResponse.getItemdes3()) &&
                Objects.equals(getItemcod(), qryYm650tstrcodResponse.getItemcod()) &&
                Objects.equals(getItemdes(), qryYm650tstrcodResponse.getItemdes());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemdes3(),
                getItemcod(),
                getItemdes());
    }
}