/*Copyright (c) 2016-2017 cmt.mu All Rights Reserved.
 This software is the confidential and proprietary information of cmt.mu You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with cmt.mu*/
package com.mu.cmt.pfs.pfsdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class QryYm650MatdiameterUomResponse implements Serializable {


    @ColumnAlias("ITEMCOD")
    private String itemcod;

    public String getItemcod() {
        return this.itemcod;
    }

    public void setItemcod(String itemcod) {
        this.itemcod = itemcod;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof QryYm650MatdiameterUomResponse)) return false;
        final QryYm650MatdiameterUomResponse qryYm650matdiameterUomResponse = (QryYm650MatdiameterUomResponse) o;
        return Objects.equals(getItemcod(), qryYm650matdiameterUomResponse.getItemcod());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getItemcod());
    }
}